### ISSUE TITLE
Store used extensions in project

### ISSUE THREAD

**Issue by piw-piw** [TurboWarp/extensions#10]
Store used extensions in project.
For example in the same comment with TW settings.

**Comment by mollthecoder** [comment]
> Store used extensions in project. For example in the same comment with TW settings.

This is very experimental and in a stage where this is not likely to happen yet, but probably will sooner or later.

**Comment by piw-piw** [comment]
But this is possible.

**Comment by Dhuls-Scratch** [comment]
Not happening. See TurboWarp/scratch-gui#431
> Scratch once received a CVE for accidentally allowing this: [GHSA-vc9j-fhvv-8vrf](https://github.com/advisories/GHSA-vc9j-fhvv-8vrf)
> 
> Custom extensions are frankly a terrible hack and aren't something that will be seeing any significant improvements any time soon.
