### ISSUE TITLE
LilyMakesThings: McUtils BUG

### ISSUE THREAD

**Issue by veggiecan0419** [TurboWarp/extensions#1002]
## @LilyMakesThings 
There is a strange bug in your McUtils extension.
### The `place order` block breaks when a boolean is placed in it,
![Bugs](https://github.com/TurboWarp/extensions/assets/137440114/26feb3b7-94ef-4884-b493-2ffc649aaeec)
### unless you use couplers' `[STRING]` boolean.
![Fine](https://github.com/TurboWarp/extensions/assets/137440114/2997b05a-6896-4b5b-9006-f524369cb460)
And, for some reason, couplers' equivalent doesn't do that.

**Comment by veggiecan0419** [comment]
It also is like that for other booleans, whether they are returning `true` or `false`

**Comment by LilyMakesThings** [comment]
I'll fix that right now, thank you for notifying me of this

**Comment by GarboMuffin** [comment]
fixed by https://github.com/TurboWarp/extensions/pull/1003, thanks for reporting this extremely critical bug

**Comment by veggiecan0419** [comment]
Thanks
