### ISSUE TITLE
Should custom blocks return multiple variables

### ISSUE THREAD

**Issue by VoxelDoesCode** [TurboWarp/extensions#1012]
I've noticed in several scratch projects, when there is a case where the custom reporters block could go in, that they actually return multiple variables instead of just one. (Example, when returning properties of a circle: `_circle.x`, `_circle.y`, `_circle.radius` (or a more visual example: [This project.](https://scratch.mit.edu/projects/74017044/)) ).

Is there a way to implement something like this where a custom block has the ability to cleanly return multiple variables? I guess a workaround is to have local variables and have the custom block have an if-else statement around its return blocks to decide which output it wants to store in what variable. But if I were to do it that way I would have to run the same equations multiple times just so I can output all the parameters I would want, when I could have only run it once.

**Comment by VoxelDoesCode** [comment]
I guess that COULD work, but how would we differentiate between each output? Maybe `return (var) as [name]`?

**Comment by SurvExe1Pc** [comment]
you could return a json value

**Comment by VoxelDoesCode** [comment]
Just tested it out. This will work perfectly! Thanks!
![image](https://github.com/TurboWarp/extensions/assets/95713843/cd506780-90f7-479c-b721-1fabdf98aa23)

**Comment by SurvExe1Pc** [comment]
np
