### ISSUE TITLE
Development server opens editor with mixed content

### ISSUE THREAD

**Issue by jumpingtj** [TurboWarp/extensions#1024]
When clicking "Open Extension" in a local development server, it opens a page something like: https://turbowarp.org/editor?extension=http://localhost:8000/example.js
However, some browsers (like Safari) disallow mixed content, so an https page can't run content from the http server.

**Comment by jumpingtj** [comment]
(On Safari): [blocked] The page at https://turbowarp.org/editor?extension=http://localhost:8000/example.js was not allowed to run insecure content from http://localhost:8000/example.js.

**Comment by SurvExe1Pc** [comment]
thats a problem with safari, i mean firefox, chrome(chrome, opera, brave, edge) exists also.

**Comment by SurvExe1Pc** [comment]
its just apple being apple(stupid)

**Comment by horizontal-shading** [comment]
2 to the power of 10.

**Comment by GarboMuffin** [comment]
http://localhost is supposed to be considered a secure context. if your browser violates the spec, that's not my problem, use another one

**Comment by GarboMuffin** [comment]
fundamentally it's always going to need to fetch information from localhost *somehow*

**Comment by jumpingtj** [comment]
So there's no way around the problem?
