### ISSUE TITLE
Thoughts on AI-generated extensions?

### ISSUE THREAD

**Issue by NexusKitten** [TurboWarp/extensions#1033]
_This issue is not meant to refer to extensions that use artificial intelligence APIs, it's strictly meant to pertain to extensions generated mostly or entirely via Chat-GPT or other AI language models._

Lots of people have recently noticed that Chat-GPT and other AI language models can generate working extension scripts for TurboWarp if given the correct instructions. However, this can be an issue considering **it does not use TurboWarp Extension Syntax**; it uses the syntax of old ScratchX extensions. While this doesn't affect much on the front-end, it's a lot less efficient on the backend, not to mention messy.

Another issue that stems from this is that people are disregarding the [Extension Documentation](https://docs.turbowarp.org/development/extensions/introduction) and [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md) in favor for what the AI generates. However, **most AI language models use outdated sources, and don't know about either of these things.**

I'm not the maintainer of this repository so I can't exactly say not to do this, however **as an active reviewer, it makes it very difficult to review an extension entirely in the wrong syntax.** This also means AI generated extensions take longer to review and are more prone to bugs.

All-in-all, I personally think it'd be a good idea to add to CONTRIBUTING.md or make a pinned issue regarding fully AI-generated extensions, however I didn't want to primitively write either of these without some feedback.

**Comment by CubesterYT** [comment]
I agree on this one. It's one thing to sometimes use AI to help you script certain parts of your extension, but making it do all the work to no effort on your end feels like something we should regulate. Especially when it doesn't follow Docs or Guidelines. It eventually makes an entire mess of the extension making process, and it would be best to make sure extensions made in AI only should be stopped.

**Comment by GarboMuffin** [comment]
> it makes it very difficult to review an extension entirely in the wrong syntax

Don't waste your time trying. Just leave a comment with a link to the docs. If they never fix it then it just becomes yet another dead PR.

**Comment by GarboMuffin** [comment]
Realistically we can't ban AI and no one reads CONTRIBUTING.md :(

At the very least, it is quite obvious when someone hasn't even looked at the documentation or any other extensions. In such cases you don't need to review any further. If they can't do their part, then you don't need to reciprocate.

**Comment by horizontal-shading** [comment]
> Realistically we can't ban AI and no one reads CONTRIBUTING.md :(
> 
> At the very least, it is quite obvious when someone hasn't even looked at the documentation or any other extensions. In such cases you don't need to review any further. If they can't do their part, then you don't need to waste your time.

I thought you typed in all lowercase?

**Comment by GarboMuffin** [comment]
Why do you care so much?

**Comment by snowboyz0825** [comment]
I've taught it to make extension using the documentation and _tried_ to put in the contributing stuff myself. I'm not going to argue, you guys clearly know what you're talking about much more than me, but how I taught it was using the documentation in a shortened form - 
[Tutorial.txt](https://github.com/TurboWarp/extensions/files/12652042/Tutorial.txt)
I don't know what's up with the syntax, here's an example extension
[keypressed - Copy.txt](https://github.com/TurboWarp/extensions/files/12652171/keypressed.-.Copy.txt)
yeah I know it's a txt file I couldn't upload .js files
Anyways, unless chatgpt is just pulling it out of it's ass, what exactly is different about the syantax so that I could try to train it to use that syntax?
I'm commenting this so you guys better know how people do it and hopefully at least make people more mindful while doing it

**Comment by NexusKitten** [comment]
> [snip](https://github.com/TurboWarp/extensions/issues/1033#issuecomment-1724175746)

The issue isn't that we're trying to train an AI to create TurboWarp extensions, but rather the AI itself. No AI will be perfect-- even if we give it extremely precise instructions and tell it to never go against those instructions, there'll always be times when it'll mess up or contradict itself. The problem is that most people using AI to generate extensions are doing so because they don't know JavaScript or JSON, and so they won't pick up on these errors.

**Comment by snowboyz0825** [comment]
Fair enough. When I do it, I make sure to test everything extensively, but there's only so much I can catch. If I were to go through contributing again, find out how to out it through the checker-thing, would it be a perfectly viable extension? well except for the fact that it exists in the turbowarp blocks, but this one reports when no key is being pressed and will report basically any key

**Comment by GarboMuffin** [comment]
See https://github.com/TurboWarp/extensions/pull/1035
