### ISSUE TITLE
New TurboWarp feature idea: Scenes

### ISSUE THREAD

**Issue by DevelopCMD** [TurboWarp/extensions#1034]
What the Scenes feature does is that it allows you switch between different stages. This feature would be useful if you were making an OS with multiple apps, and each app would be its own stage.

**Comment by DevelopCMD** [comment]
You could also name the stages, which would be easier to recognize, and the scenes would be stored in separate folders, if the project was packaged.

**Comment by NexusKitten** [comment]
While this is a fun concept, it'd be very resource intensive to implement. There's a lot to manage with it-- how do you swap scenes? How do you transfer data between scenes? Does a scene still run if another one is open? Does changing scenes trigger a green flag press? etc...
It'd require rewriting a lot of VM, which I don't think Garbo has the resources for right now.

**Comment by DevelopCMD** [comment]
Basically, the 1st scene will be the main scene, which is basically the parent of the scenes, and when it is switched to another scene, the previous scene is suspended, saving memory. Also, to change scenes, there would probably be blocks that allow you to do that. Changing scenes does not trigger a green flag press; the previous scene is stopped, and the switched scene is started.

**Comment by gomiigg** [comment]
So is this kind of like states in HaxeFlixel?

**Comment by NexusKitten** [comment]
> Basically, the 1st scene will be the main scene, which is basically the parent of the scenes, and when it is switched to another scene, the previous scene is suspended, saving memory. Also, to change scenes, there would probably be blocks that allow you to do that. Changing scenes does not trigger a green flag press; the previous scene is stopped, and the switched scene is started.
I don't think you're quite catching my drift-- this would be a really large undertaking for one developer. It would require rewriting a lot of code, and it would also be really difficult to figure out the best way to go about it (from both a community side and a computational side). I personally think resources are better spent elsewhere, considering Garbo is already stretched really thin as is.

**Comment by snowboyz0825** [comment]
> What the Scenes feature does is that it allows you switch between different stages. This feature would be useful if you were making an OS with multiple apps, and each app would be its own stage.

You can _kinda_ do this with shovel utils
![block_9_18_2023-11_17_39 AM](https://github.com/TurboWarp/extensions/assets/101284660/83082a7c-3d90-4b89-ae1c-6c1a73774308)
Ok it ended up being mostly a saving algorithm thingy, but the point is it saves all of the data and then you can have it load a project from somewhere else.

**Comment by DevelopCMD** [comment]
Maybe this: Each scene could be its own project, and if it was switched to a different scene, the previous scene would be paused, similar to the pause button.

**Comment by CubesterYT** [comment]
@DevelopCMD, now that's entering the realm of never going to happen. This is a great concept, but so much needs to happen for this to be done, even if, theoretically this idea goes through, projects would be so large it's not even funny. On a possible level, making a system like this just isn't worth it. The best we can say is try making it yourself through some trickery in your games, using lists and stuff to save game state, and whatnot. I've seen good tutorials by griffpatch that allow you to make saves for your game and stuff.
