### ISSUE TITLE
Extension Idea: .ini(save data) parser

### ISSUE THREAD

**Issue by gomiigg** [TurboWarp/extensions#1038]
![image](https://github.com/TurboWarp/extensions/assets/91437192/6ea10e39-2396-4a4a-8eb3-069387b07a21)

Can a file as large as this be saved in local storage or the `app` folder when packaged? Is there also a way to do this in TW without needing an extension?

**Comment by idoinfactexist** [comment]
you can use cloud variables in the packager to achieve a similar effect. in the cloud variables section, in the first drop down either select "store in local storage" or "advanced" depending on what you need

**Comment by ClaytonTDM** [comment]
You can also use the local storage extension
![image](https://github.com/TurboWarp/extensions/assets/71360210/a3b04a9a-e6c3-4199-9f57-dbc1a8e3c569)

**Comment by CubesterYT** [comment]
Doesn't seem possible, considering our limited capabilities, like imagine someone trying this in HTML packaged projects or similar... Best to just stick to Local Storage.

**Comment by yuri-kiss** [comment]
It is 100% possible if they would be fine with just wanting a parser for the INI data.
