### ISSUE TITLE
Submit Sandboxed Extension

### ISSUE THREAD

**Issue by CS2627883** [TurboWarp/extensions#104]
I just creating [an extension](https://github.com/CS2627883/Turbowarp-Encoding-Extension) and I was about to submit it. However, I noticed that CONTRIBUTING.md only talks about unsandboxed extensions, and mine is sandboxed.
Should I rewrite my extension to be unsandboxed, then submit it?

**Comment by GarboMuffin** [comment]
If the extension doesn't actually use any unsandboxed features, it can run in either sandboxed or unsandboxed mode.

**Comment by GarboMuffin** [comment]
Read the links at the top of CONTRIBUTING.md for more information. It's explained in there.
