### ISSUE TITLE
LogIn

### ISSUE THREAD

**Issue by kurisotofaa** [TurboWarp/extensions#1046]
Hello guys, I dont know if this is a feature yet, but I would really want a user that plays on desktop to login to his game account in my game, and get his "saves: (local variables) on his "Game Account", and also get those saves on mobile for the same game. Can anyone implement this feature, if there is already a way to do it, tell me how.

**Comment by HBDeveloper11** [comment]
I actually like this feature, for example, if I was making an OS, then it would require the user to log in to his/her account, which would be very useful. I like this feature.

**Comment by snowboyz0825** [comment]
> Hello guys, I dont know if this is a feature yet, but I would really want a user that plays on desktop to login to his game account in my game, and get his "saves: (local variables) on his "Game Account", and also get those saves on mobile for the same game. Can anyone implement this feature, if there is already a way to do it, tell me how.

I think the only way this could be done is with a sever in the middle. The account which can be logged in however pulls data from a cloud variable, and there would be an intermediate server account that saves it within a list and then "sends" it. 

Another way you could do it is using the cloudlink extension, but honestly, I just don't like messing with it

**Comment by kurisotofaa** [comment]
hi guys, i figured something out. You can use the gamejolt api extension, you can login with your gamejolt account (you can integrate the login ingame) and you have some cool
things like cloud/user variables, leaderboards, throphies (achievements). I’ll try integrating it in my game, but at least for now, everythings working…

**Comment by softedco** [comment]
or you can just
![image](https://github.com/TurboWarp/extensions/assets/100989385/25a0cde4-192f-48c6-a1c5-4e63c5072e86)
jk

**Comment by Thebloxers998** [comment]
> or you can just ![image](https://private-user-images.githubusercontent.com/100989385/271827313-25a0cde4-192f-48c6-a1c5-4e63c5072e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzA3MzIsIm5iZiI6MTczMjIzMDQzMiwicGF0aCI6Ii8xMDA5ODkzODUvMjcxODI3MzEzLTI1YTBjZGU0LTE5MmYtNDhjNi1hMWM1LTRlNjNjNTA3MmU4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQyMzA3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjVmY2E5NDA4ZWJmYTIyNmE5NjQzMDFhODZhMGQ2Y2QwMzJkZDE3YmJlNDM1NTdkNGIwYzRiNzAyM2NkMWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XdbsHATh9huEPi6rAqYRqnI7nudh1LRn97izYAU_GFE) jk

Lol
