### ISSUE TITLE
Looks+ suggestion: Add a PNG variant of the "replace (color) with (color) in (image data)" block

### ISSUE THREAD

**Issue by Meehdrescher** [TurboWarp/extensions#1077]
![grafik](https://github.com/TurboWarp/extensions/assets/83909483/453d94e3-060c-4835-8136-f7e77939f4c2) 
(this is the block I mean)

I haven't found a block that allows me to replace colors in bitmap images anywhere, and it doesn't seem to work if I convert the bitmap into an SVG before running it through the block as the output stays the same. 
This could be very useful for things like car customization where you could change the paintjob color, especially combined with the color picker extension, since I could make all the cars have the same base color and then change it on the fly while the project is running.

**Comment by SharkPool-SP** [comment]
I made a block for this, its in my extension, Image Effects. Its also on my Gallery:
https://sharkpools-extensions.vercel.app/

**Comment by Meehdrescher** [comment]
> I made a block for this, its in my extension, Image Effects. Its also on my Gallery: https://sharkpools-extensions.vercel.app/

Works like a charm, I've been able to make fully customizable cars with this in just a few minutes...
and I wanted to let you know of one thing I don't quite like about your website. Gamepad Extended shows Martinelplayz as the only creator of the extension, however, I've supplied at least half of the added code.

**Comment by SharkPool-SP** [comment]
> > I made a block for this, its in my extension, Image Effects. Its also on my Gallery: https://sharkpools-extensions.vercel.app/
> 
> 
> 
> Works like a charm, I've been able to make fully customizable cars with this in just a few minutes...
> 
> and I wanted to let you know of one thing I don't quite like about your website. Gamepad Extended shows Martinelplayz as the only creator of the extension, however, I've supplied at least half of the added code.

Hmm, Martinelplayz never told me you worked on it too. Do you mind telling me who else helped made it? I'll change the credits.

**Comment by Meehdrescher** [comment]
#1020  just a merged version of #881 by [DNin01](https://github.com/DNin01) and #1018 and me and he took all the credit for it

**Comment by SharkPool-SP** [comment]
> #1020  just a merged version of #881 by [DNin01](https://github.com/DNin01) and #1018 and me and he took all the credit for it

Thanks for letting me know. I'll fix the credits to include you two and remove him. Check the site for an update in about 4-ish hours. I'm at school right now

**Comment by CubesterYT** [comment]
@SharkPool-SP NOO IM THR ONLY INE WGO DESERVESD CREDIT!!786!!!-

**Comment by SharkPool-SP** [comment]
> @SharkPool-SP NOO IM THR ONLY INE WGO DESERVESD CREDIT!!786!!!- 

Huh

**Comment by SharkPool-SP** [comment]
> #1020 just a merged version of #881 by [DNin01](https://github.com/DNin01) and #1018 and me and he took all the credit for it

Kay, fixed the credits! :)
Thanks for letting me know!

**Comment by Meehdrescher** [comment]
> Kay, fixed the credits! :) Thanks for letting me know!
No problem, and thank you for adding my suggestion to your extension!

**Comment by TJM0NKEY** [comment]
> I made a block for this, its in my extension, Image Effects. Its also on my Gallery: https://sharkpools-extensions.vercel.app/

Hello Sharkpooles, i have a question, how does this extension work, like how to i get it to replace a certain colour on bitmap, what blocks do i use and combine

**Comment by SharkPool-SP** [comment]
> > I made a block for this, its in my extension, Image Effects. Its also on my Gallery: https://sharkpools-extensions.vercel.app/
> 
> 
> 
> Hello Sharkpooles, i have a question, how does this extension work, like how to i get it to replace a certain colour on bitmap, what blocks do i use and combine

Use looks+ to get the data uri of the bitmap costume, replace the color, then use skins to display the output
