### ISSUE TITLE
Various Extension Images Changed

### ISSUE THREAD

**Issue by xTvii** [TurboWarp/extensions#1079]
I've noticed that a _lot_ of the images in extensions don't really follow the "scratch extension style" which is what TurboWarp follows as well.

I've remade all of them to fit the style better. I hope you enjoy them!

**Fetch**
![Fetch(2)](https://github.com/TurboWarp/extensions/assets/137563418/8d700b36-4c5f-4152-8fba-297606066771)
**IFrame**
![IFrame](https://github.com/TurboWarp/extensions/assets/137563418/27e929bb-924b-4f05-9f1f-87702c34c236)
**Clipboard**
![Clipboard](https://github.com/TurboWarp/extensions/assets/137563418/0c633237-2e24-4b1c-b399-265f535e0ca1)
**Pen Plus**
![Pen Plus](https://github.com/TurboWarp/extensions/assets/137563418/f21275a2-f07e-449f-8eaf-8717dd244803)
**Sensing Plus**
![Sensing Plus](https://github.com/TurboWarp/extensions/assets/137563418/2f998b0d-3860-4943-a69d-9769ccb5ab72)
**Browser Fullscreen**
![Browser Fullscreen](https://github.com/TurboWarp/extensions/assets/137563418/91b1d061-c2be-48c3-82ad-d50fc4a31449)
**Screen Resolution**
![Screen Resolution](https://github.com/TurboWarp/extensions/assets/137563418/9cf6dc6f-31d6-470b-a64c-d945b90b5624)
**Deltatime**
![Deltatime](https://github.com/TurboWarp/extensions/assets/137563418/aa082120-2211-45fa-97ae-0ed08977772e)
**All Menus**
![All Menus](https://github.com/TurboWarp/extensions/assets/137563418/f31e8486-319b-4805-91af-ea538ce5e3b5)
**JSON**
Font used is _Gotham_
![JSON](https://github.com/TurboWarp/extensions/assets/137563418/b140d041-7ade-4b78-9ae1-73489fd311ea)
**Numerical Encoding**
Font used is _Gotham_
![Numerical Encoding](https://github.com/TurboWarp/extensions/assets/137563418/9f2444cc-1b99-4799-bd1d-014144660e63)
**S-Grab**
![S-Grab](https://github.com/TurboWarp/extensions/assets/137563418/0694fdcd-bc19-42e3-95b9-2fdf6a9138f0)
**Graphics 2D**
![Graphics 2D](https://github.com/TurboWarp/extensions/assets/137563418/21c3d3cc-eb3f-4937-ba73-0d8f3eaefd69)
**Data Analysis**
![Data Analysis](https://github.com/TurboWarp/extensions/assets/137563418/b4ea12e6-0f2f-4192-833a-495ec370f10b)
**Longman Dictionary**
![Longman Dictionary](https://github.com/TurboWarp/extensions/assets/137563418/8241fa06-b5aa-41f7-88a3-50daca4c9416)

**Comment by xTvii** [comment]
#90

**Comment by veggiecan0419** [comment]
> **Longman Dictionary**
 > ![LongmanDictionary](https://user-images.githubusercontent.com/137563418/272688817-8241fa06-b5aa-41f7-88a3-50daca4c9416.svg)

Could you add the following logo ⬇️  on the cover instead of `Ld` please?

![Longman Dictionary Logo](https://github.com/TurboWarp/extensions/assets/137440114/ad1e2c4d-a09a-42bf-b604-5dd9db32e7ce)

(https://www.ldoceonline.com/external/images/logo_home_smartphone.svg?version=1.2.61)

**Comment by xTvii** [comment]
@veggiecan0419

Thank you for the suggestion! Here's the fix:
![Longman Dictionary(1)](https://github.com/TurboWarp/extensions/assets/137563418/4fca4dd8-7353-4d2e-bc9a-f95ddb0f94eb)

**Comment by veggiecan0419** [comment]
@xTvii 
That looks lovely

**Comment by snowboyz0825** [comment]
All of them are great, but I don't get the clipboard one

**Comment by CubesterYT** [comment]
> All of them are great, but I don't get the clipboard one

@snowboyz0825, it's a clipboard..?
This is a clipboard in real life:
![download](https://github.com/TurboWarp/extensions/assets/78769806/6e62c31f-7b6a-4c98-a2ff-9296c287fb2a)
and:
![download](https://github.com/TurboWarp/extensions/assets/78769806/cae18783-f663-45a7-906d-604dc359ccee)

**Comment by gomiigg** [comment]
I feel the iFrame one could use a different or darker color, as it's a little hard to make out the little branchy logo thing in the middle. (I forgot what that was called)

**Comment by Pizzalover4783** [comment]
Is it just me, or do a lot of these just feel empty or soulless? While making all the thumbnails look the same is good for consistency, I think it also makes some of these extensions lose a good bit of their individuality in the process. Not to mention some of these thumbnails (particularly ones like Graphics 2D, Numerical Encoding and Fetch), just seem like they use too little of the space available, especially when compared to their current thumbnails. It also doesn't help that quite a few of these seem to reuse the same background with only changes to the color and orientation. Overall, while I do like some these changes, I just think that many of these thumbnails are a bit of a downgrade from the original.

**Comment by xTvii** [comment]
> Is it just me, or do a lot of these just feel empty or soulless? While making all the thumbnails look the same is good for consistency, I think it also makes some of these extensions lose a good bit of their individuality in the process. Not to mention some of these thumbnails (particularly ones like Graphics 2D, Numerical Encoding and Fetch), just seem like they use too little of the space available, especially when compared to their current thumbnails. It also doesn't help that quite a few of these seem to reuse the same background with only changes to the color and orientation. Overall, while I do like some these changes, I just think that many of these thumbnails are a bit of a downgrade from the original.

I mean, it's partially due to the fact that some of them _(notably All Menus, Clipboard and JSON)_ kind of stick out like sore thumbs.
When you have a bunch of well-designed images, adding new ones that disregard the **clear visual format** that basically every other extension image follows makes them look odd.

Personally, I just remade the images to fit the style better. If you don't think they're good, then cool. I actually hand-picked the ones that I felt looked _off_ - and that has a lot of critera - to remake. I think the remakes for Pen and Sensing Plus, Browser Fullscreen, Clipboard, and All Menus were **very** much-needed.

> It also doesn't help that quite a few of these seem to reuse the same background with only changes to the color and orientation.

It's probably better to use the same background over and over than use no background _(JSON, sorry i'm picking away on this one)_ or a background that hurts the eyes _(Clipboard, kind of. Those colours **do not** match)_.


> Not to mention some of these thumbnails (particularly ones like Graphics 2D, Numerical Encoding and Fetch), just seem like they use too little of the space available

Doesn't _Pen_, up there as one of the most used extensions _(probably)_ use, like, a quarter of the page?

**Comment by Pizzalover4783** [comment]
While I do agree that some of the current thumbnails (Mainly the examples given in your original reply) needs some changes, I still think that some of the thumbnails you chose (Graphics 2D, 
Longman Dictionary, Numerical Encoding) worked better off as is. The fact that they don't look like everything else is WHY they looked good, at least to me anyway.

As to mention some of your other points, while reusing backgrounds is indeed better than no backgrounds, the extra bit of effort that comes into making unique backgrounds helps makes a huge difference.

As as for the space usage, just because an official Scratch thumbnail used for one of the most used extensions has too much empty space doesn't automatically justify the practice. If you're going to replicate the style, the least you could do is spice things up by using more of your space on, say, a unique background.

**Comment by CST1229** [comment]
> It also doesn't help that quite a few of these seem to reuse the same background with only changes to the color and orientation.

Vanilla Scratch also does this.
![image](https://github.com/TurboWarp/extensions/assets/68464103/82e115fa-ddfc-45db-a8ff-096a51f29820)

**Comment by LilyMakesThings** [comment]
> Vanilla Scratch also does this. ![image](https://user-images.githubusercontent.com/68464103/273320971-82e115fa-ddfc-45db-a8ff-096a51f29820.png)

To a much lesser extent, and it never reuses rotations as much as the gallery does right now.

I do very much like these thumbnails, nice job!

**Comment by Skyhigh173** [comment]
JSON: `{"key":"value"}` but not `{"key","value"}`

**Comment by xTvii** [comment]
Thanks for pointing all those issues out, guys!

@Skyhigh173 I'll make sure to fix that soon.

@Pizzalover4783 @LilyMakesThings I'm working on changing up the blob backgrounds, with two exceptions: Pen Plus and Sensing Plus. I don't think they need a unique background, considering the other "<blank> Plus" extensions (excluding Motio) use it.

**Comment by xTvii** [comment]
Alright! I've fixed the overusage of blobs alongside other changes! Here's everything I've made different:

![Fetch(3)](https://github.com/TurboWarp/extensions/assets/137563418/7718cbd2-6657-41f0-b73e-9caae0827714)
![IFrame(1)](https://github.com/TurboWarp/extensions/assets/137563418/fd741423-3f21-44c5-bd2a-d192a503c496)
![All Menus(1)](https://github.com/TurboWarp/extensions/assets/137563418/4969bca2-428b-42fb-b20b-94b8fba49f4b)
![JSON(1)](https://github.com/TurboWarp/extensions/assets/137563418/891bd686-281d-4399-a45e-87c7c4d38721)
![Graphics 2D(1)](https://github.com/TurboWarp/extensions/assets/137563418/0b1e3a4e-eeb0-4678-ab5a-986e35c29993)
![Data Analysis(1)](https://github.com/TurboWarp/extensions/assets/137563418/6e2e142e-6eb0-4166-a0a7-9c0e4f66c661)

**Comment by LilyMakesThings** [comment]
These are brilliant! And I agree that sensing and pen plus don't need different backgrounds. Fantastic job!

**Comment by Pizzalover4783** [comment]
These look significantly better

**Comment by xTvii** [comment]
Thank you! :)

**Comment by gomiigg** [comment]
I think the All Menus blocks could be a little larger or "zoomed in" because it might be hard to read at that size

**Comment by David-Orangemoon** [comment]
Hey if anyone sees this in the future I would like to let people know that I don't really want Pen+'s thumbnail changed due to the fact that said extension exists in multiple places and I want to keep the same sort of theme its had since 2021.

**Comment by xTvii** [comment]
Which one? There's two and I planned to change V7 as it has text and that's described as something to be changed in the update.

**Comment by xTvii** [comment]
I mean, I can happily just keep them the same.

**Comment by David-Orangemoon** [comment]
> Which one? There's two and I planned to change V7 as it has text and that's described as something to be changed in the update.

V7 as the website and shader editor have similarly styled logos and designs.
