### ISSUE TITLE
HTTP extension - Is there a way to get resources from "HTTP" websites

### ISSUE THREAD

**Issue by BlestLace** [TurboWarp/extensions#1083]
I am trying to access an HTTP website (specifically http://onj3.andrelouis.com/phonetones/), and get this error in the Chrome console:
`Mixed Content: The page at 'https://turbowarp.org/editor' was loaded over HTTPS, but requested an insecure resource 'http://onj3.andrelouis.com/phonetones/'. This request has been blocked; the content must be served over HTTPS.`

Is there a way to bypass this error and get that said HTTP resource from the extension?

**Comment by BlestLace** [comment]
I just found something.
There is no way to bypass this issue, unlike other HTTPS errors because the request is instructing the browser to allow nothing but a secure connection.

**Comment by GarboMuffin** [comment]
One common approach that you would likely need anyways even for HTTPS urls is to use a "CORS proxy"

**Comment by BlestLace** [comment]
I've looked into one CORS proxy extension but I didn't really know how to use it.

**Comment by BlestLace** [comment]
I've figured it out. Thanks for the help!

**Comment by BlestLace** [comment]
I have another question. How can I play sound from the website using the CORS proxy? I tried to combine the sound extension with the CORS proxy but it just won't play.

**Comment by GarboMuffin** [comment]
What URL are you trying to use?

**Comment by BlestLace** [comment]
I put it in the main issue post: http://onj3.andrelouis.com/phonetones/

**Comment by BlestLace** [comment]
If you need the CORS proxy, I believe it's using corsproxy.io
I am using a PenguinMod extension (https://extensions.penguinmod.site/extensions/NamelessCat/corsproxy.js) 
and loading it in TurboWarp.
