### ISSUE TITLE
Manipulate Lists and Variables in Extension

### ISSUE THREAD

**Issue by CS2627883** [TurboWarp/extensions#109]
I am implementing save codes in a project. My save codes work by adding all the data to a list and encoding the list into a string with a delimiter between items. However, the save codes can get massive, and in turbowarp, they take several minutes to parse. I have tried optimizing my script, enabling run without screen refresh, etc. - but it's still too slow.

My solution was to rewrite the parsing script in javascript, and access it via a custom extension in my project. This works great, and the save codes get parsed almost instantly. The javascript code is simple: ```var result = savecode.split(",");```

But my extension needs to manipulate a list. In scratch, you can use list functions like `add [thing] to [mylist]`.
According to [Leopard](https://leopardjs.com/manual?p=variables), you can access all variables and lists using `this.stage.vars` in javascript. However, `this` represents a different object in my extension class. When I try using `this.stage.vars.Result = result;`, I get an error:
```js
Custom extension block error TypeError: Cannot read properties of undefined (reading 'vars')
```
So, how can I access lists and variables in my extension? My extension needs to be sandboxed, by the way.

**Comment by CS2627883** [comment]
My Code:
```js
//This is for personal use

(function(Scratch) {
    'use strict';
	//if (!Scratch.extensions.unsandboxed) {
	//	throw new Error('MyBackend must be run unsandboxed');
	//}
    class MyBackend {
    progress = 0;
    getInfo() {
        return {
            id: 'mypersonalbackenddonotuse',
            name: 'Backend',
            blocks: [{
                opcode: 'MyBackendFunction',
                blockType: Scratch.BlockType.COMMAND,
                text: 'Backend Function [DATA]',
                arguments: {
                    DATA: {
                        type: Scratch.ArgumentType.STRING,
                        defaultValue: ''
                    }
                }
            },
			{
                opcode: 'MyBackendFunction2',
                blockType: Scratch.BlockType.COMMAND,
                text: 'Backend Function 2 [DATA]',
                arguments: {
                    DATA: {
                        type: Scratch.ArgumentType.STRING,
                        defaultValue: ''
                    }
                }
            },
            {
                opcode: 'GetProgress',
                blockType: Scratch.BlockType.REPORTER,
                text: 'progress',
            }]
        }
    }
    _Decode(todecode) {
        if (todecode == "") {
            return "";
        }
        var decoded = "";
        // Create regex to split by char length
        const regex = new RegExp('.{1,' + 6 + '}', 'g');
        // Split into array of characters
        var encodedchars = todecode.match(regex)
        for (let i = 0; i < encodedchars.length; i++) {
            // Get character from char code
            var decodedchar = String.fromCharCode(encodedchars[i]);
            decoded += decodedchar;
        }
        return decoded;
    }
    MyBackendFunction(args) {
        this.progress = 0;
        var z = this._Decode(String(args.DATA));
        this.stage.vars.BackendResult = z.split("|");
    }
    MyBackendFunction2(args) {
        this.progress = 0;
        var z = String(args.DATA)
        var a = z.substring(1, z.length - 1);
        var b = z.split(",");
        var u = [];
        for (let i = 0; i < b.length; i++) {
            if (!(u.includes(b[i]) || b[i].includes("~") || b[i].includes("|"))) {
                u.push(b[i]);
            }
        }
        this.stage.vars.BackendResult = u;
    }
    GetProgress(args) {
        return this.progress;
    }
}

Scratch.extensions.register(new MyBackend());
})(Scratch);
```

**Comment by CST1229** [comment]
> According to [Leopard](https://leopardjs.com/manual?p=variables)

By the way, Leopard's JavaScript conversion list applies only to projects converted/made with it (which have the Leopard runtime library). It does not apply to actual Scratch extensions.

At least in a sandboxed extension, you can't modify lists or variables.

**Comment by CS2627883** [comment]
> > According to [Leopard](https://leopardjs.com/manual?p=variables)
> 
> By the way, Leopard's JavaScript conversion list applies only to projects converted/made with it (which have the Leopard runtime library). It does not apply to actual Scratch extensions.
> 
> At least in a sandboxed extension, you can't modify lists or variables.

Thank you. Is there anything I can do, then?

**Comment by showierdata9978** [comment]
> My extension needs to be sandboxed, by the way.

why does it need to be sandboxed?

**Comment by GarboMuffin** [comment]
> However, the save codes can get massive, and in turbowarp, they take several minutes to parse

Unless your save codes are tens of megabytes long, I suspect that this is something wrong with your scripts

**Comment by CS2627883** [comment]
> > My extension needs to be sandboxed, by the way.
> 
> why does it need to be sandboxed?
The turbowarp documentation says that unsandboxed extensions must be loaded from extensions.turbowarp.org, and I don't think it would be appropriate to put an extension that just does `String.split(",")` in the official extensions gallery.

**Comment by GarboMuffin** [comment]
I'll close this by reiterating some things earlier:

1. If all you're doing is splitting by a comma, this *absolutely should not be taking several minutes*. This project can decode a 700,000 character string in 0.05 seconds: https://turbowarp.org/782840280. Unless your strings are tens of megabytes (at which point you have other issues), this shouldn't be the performance bottleneck.
1. Sandboxed extensions cannot interact with the VM (but you shouldn't need to anyways; see 1)
1. A string splitting extension or block would be accepted to turbowarp.org (but you shouldn't need to use one anyways; see 1)

If this doesn't resolve your issue, just comment

**Comment by GarboMuffin** [comment]
I suspect the issue you're seeing if the script is taking several minutes is that you're repeatedly calling a sandboxed block which requires a forced 1 frame delay. The solution here is to:

 - rewrite it in Scratch
 - call the block fewer times if you can
 - submit it to extensions.turbowarp.org. We're okay with accepting niche extensions there. They just might not make it onto the homepage.

**Comment by CS2627883** [comment]
> > However, the save codes can get massive, and in turbowarp, they take several minutes to parse
> 
> Unless your save codes are tens of megabytes long, I suspect that this is something wrong with your scripts

I thought that too - I've never had this issue before. I just did some testing, and it looks like I made a big mistake. I was decoding the save data from numbers back into text with my encoding extension, then iterating over the `decoded` reporter block of my extension. I was grabbing each letter with `letter [i] of [decoded]`. Since my extension is sandboxed, this means that every call to the `decoded` block caused my script to wait for a frame -  which made my script work at a rate of 1 letter per frame, 30 letters per second.

**Comment by CS2627883** [comment]
> I suspect the issue you're seeing if the script is taking several minutes is that you're repeatedly calling a sandboxed block which requires a forced 1 frame delay. The solution here is to:
> 
> * rewrite it in Scratch
> * call the block fewer times if you can
> * submit it to extensions.turbowarp.org. We're okay with accepting niche extensions there. They just might not make it onto the homepage.

LOL, nice guess!
