### ISSUE TITLE
A 3D extension that lets you make platformer games, maze games, ect

### ISSUE THREAD

**Issue by Gaypatapon** [TurboWarp/extensions#1093]
Creating a 3D engine can be hard sometimes, and yeah i know you can make a raycaster script on scratch and simulate 3D but i meant making a 3D patformer with all the 3D axis, 3D maze games on scratch only has x and z axis while the y axis is only for simulating the walls, i was thinking of having blocks that lets you import 3D models and a block that lets you animate your models, new blocks like change z or set z, blocks like create a block (x) (y) (z), blocks that lets you set gravity, physics, and more, i have seen great 3D scratch games that are platformers but the problem is that the code is super complex and hard to understand which is why i am suggesting a 3d extension.

**Comment by HBDeveloper11** [comment]
I actually like the idea of making a 3D engine in TurboWarp, maybe someone who has a lot of knowledge of making TurboWarp extensions (ex. LilyMakesThings), can make something like this.

**Comment by gomiigg** [comment]
You might have bitten off more than you can chew with this one

**Comment by Gaypatapon** [comment]
> You might have bitten off more than you can chew with this one

Yeah you're right but still a good idea

**Comment by Stiwen02** [comment]
Maybe the 3D extension is for drawing wireframes with the pen extension? Maybe blocks like "draw cube at x y z, size x y z" and "draw line from x y z to x y z" would store positions in a list and the "draw to screen" block would draw the pixels in the list while sorting them.
By sorting I mean that the pixels closer to the camera are drawn last, so they're always fully shown. In the image you can see that the green cube is drawn before the white line that's close to the camera, but the green cube is drawn after the white line that's further from the camera.
![image](https://github.com/TurboWarp/extensions/assets/146366486/881e64f0-a669-4a28-8c33-8786b06a0124)

**Comment by Xeltalliv** [comment]
I am (slowly) making one:
![image](https://github.com/TurboWarp/extensions/assets/90340988/1a2a13aa-0a2c-45b6-9dd1-f865a86395a8)
It is just for drawing, so no physics or collision

**Comment by Xeltalliv** [comment]
> ЧЕЛ, ДАЙ МНЕ ЭТО РАСШИРЕНИЕ!/DUDE, GIVE ME THIS EXTENSION!

Оно не закончено и использовать то, что есть сейчас, для чего-либо кроме "просто поексперементировать" нельзя. Я всё ещё буду менять существующие блоки и изменю ID разширения, так что проекты созданные с версией разширения которая сейчас - сломаються и даже не будут открываться (будет ошибка при открытии проекта). Если уж так сильно хочеться, недоделаная версия сейчас опубликована в одной из веток моего форка этого репозитория. Где именно - ищи сам.

**Comment by LilyMakesThings** [comment]
This can be closed
