### ISSUE TITLE
Will there be new blocks for Encoding extension?

### ISSUE THREAD

**Issue by ghost** [TurboWarp/extensions#1095]

**Comment by SurvExe1Pc** [comment]
i made a pr to add stuff but it was never merged so yeah lol, then i reset my repo cause it was a mess so i just have a old copy of my updated version of it when i can get on i will make a pr to add stuff to it
________________________________
From: horizontal-shading ***@***.***>
Sent: Thursday, October 12, 2023 6:45 AM
To: TurboWarp/extensions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TurboWarp/extensions] Will there be new blocks for Encoding extension? (Issue #1095)

**Comment by Stiwen02** [comment]
I've written an extension for myself before that's for cloud variables and I could make a pull request to add the extension to this repository, but I'm not sure if the blocks are hard to understand for other people.
![image](https://github.com/TurboWarp/extensions/assets/146366486/5663ab2f-bdf7-47a0-8672-6105492abf84)
