### ISSUE TITLE
Suggestion: Expose called block id in third argument or util

### ISSUE THREAD

**Issue by softedco** [TurboWarp/extensions#1104]
I am currently making a reflection extension and I need to know the id of the block that is called so that I can return the opcode of it's child or if it's data_variable, return the name of the variable like this:
![image](https://github.com/TurboWarp/extensions/assets/100989385/8038f718-a58d-4f30-8e6e-9bd354157fce)
This would also allow blocks for per-instance data storing, though there are sub-optimal solutions already. Is this possible?

**Comment by LilyMakesThings** [comment]
util.thread.peekStack()

**Comment by softedco** [comment]
> `util.thread.peekStack()` returns the opcode of the block itself but if you root around the thread object you should be able to get what you're looking for

Thanks for the method!
Regarding the thread object, there is no way to distinguish ids under the same opcode from one another so the solution would be very unreliable, hence the issue
