### ISSUE TITLE
cl4 Branding is MIT

### ISSUE THREAD

**Issue by showierdata9978** [TurboWarp/extensions#111]
![image](https://user-images.githubusercontent.com/68120127/210263346-8a296a58-f055-4d7e-ac9f-2ab35656a71f.png)

**Comment by softedco** [comment]
Why wouldn't it be, the extension is there and it has that branding

**Comment by GarboMuffin** [comment]
"The cloud icon is from the Cloudlink extension itself" implies MIT but I will make it more explicit

If the Cloudlink people want to see a different icon there, they are free to submit a new one
