### ISSUE TITLE
Python Javascript And Some other languages

### ISSUE THREAD

**Issue by Wojtek9388** [TurboWarp/extensions#1136]
please add stuff to code in javascript python and some other stuff

**Comment by CubesterYT** [comment]
What? What are you trying to tell us? This is a Repository for Javascript Extensions for TurboWarp.

**Comment by NotFenixio** [comment]
Do you mean executing JavaScript and Python code?

If yes, the JavaScript part would be easy to implement but extremely dangerous, because you could execute arbitrary code on others' computers. For the Python part, Brython would be an option (see [1](https://brython.info/tests/editor.html?lang=es), [2](https://brython.info)).

**Comment by Wojtek9388** [comment]
yes i do mean that fenixio and i know its dagerous but i would like to be able to do some stuff with js and python

**Comment by GarboMuffin** [comment]
Extensions run in a browser so they have to be JavaScript


If you try really hard then you could compile the Python interpreter to run in a browser but making that work will be just as hard as learning JavaScript in the first place and is generally not actually usable for anything

**Comment by CubesterYT** [comment]
You could, like Garbo said, reimplement the compiler, but another option is using WebAssembly. It's a upcoming technology that allows you to run/interpret/compile code from other languages directly in the browser.

**Comment by GarboMuffin** [comment]
that's what I mean, if you try hard to you can WebAssembly a Python interpreter into a browser, but you still have to make it interact with the project runner (JavaScript) on your own, so just writing JavaScript in the first place would be easier

**Comment by FurryR** [comment]
![image](https://github.com/TurboWarp/extensions/assets/55276797/649482e4-918d-452d-8a30-1048cfd76d4e)

Your wish comes true

**Comment by unknown07724** [comment]
@FurryR I feel like adding python functions is safer than just letting people use a python terminal

**Comment by Drago-Cuven** [comment]
and i'm on the way to add lua.

**Comment by Wojtek9388** [comment]
> ![image](https://private-user-images.githubusercontent.com/55276797/345476113-649482e4-918d-452d-8a30-1048cfd76d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTkxNTUsIm5iZiI6MTcyMTQxODg1NSwicGF0aCI6Ii81NTI3Njc5Ny8zNDU0NzYxMTMtNjQ5NDgyZTQtOTE4ZC00NTJkLThhMzAtMTA0OGNmZDc2ZDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MmY5MmRjOGNlMzE1MjQ0N2IwMDhjZTA0ODc2MmE1Y2Q0MjlmY2QwNDY5YmQ3OGE3MjQxNWM0NGNmNDFjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFgnmuclXPSQaWeF12OTxnRoAMhWGRlb_StDSdaFpFQ)
> 
> Your wish comes true

holy shit can you send the extention?

**Comment by Wojtek9388** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/55276797/345476113-649482e4-918d-452d-8a30-1048cfd76d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTkxNTUsIm5iZiI6MTcyMTQxODg1NSwicGF0aCI6Ii81NTI3Njc5Ny8zNDU0NzYxMTMtNjQ5NDgyZTQtOTE4ZC00NTJkLThhMzAtMTA0OGNmZDc2ZDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MmY5MmRjOGNlMzE1MjQ0N2IwMDhjZTA0ODc2MmE1Y2Q0MjlmY2QwNDY5YmQ3OGE3MjQxNWM0NGNmNDFjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFgnmuclXPSQaWeF12OTxnRoAMhWGRlb_StDSdaFpFQ)
> > > Your wish comes true
> > 
> > 
> > holy shit can you send the extention?
> 
> yo did you ever get it 😭

no 😭

**Comment by CubesterYT** [comment]
Just contact FurryR directly on Discord
