### ISSUE TITLE
An extension to stop specific sounds or play sounds from a certain time

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/extensions#114]
I'm thinking of the following features that could either go in a new extension called something like "Sound Control" or become part of the Sound extension that was just added.

- `stop sound (sound v)` (Would stop the sound you selected)
- `start sound (sound v) from (1.5) secs` (Would play the sound you selected starting at the time you specified)
- `stop all sounds in this sprite` (Would stop all of the sounds that the sprite was playing. Could potentially be a dropdown so you could select other sprites too)

You could use these features to do various things, for example:
- To pause and resume music or narration
- To stop sounds but not music

**Comment by TrueFantom** [comment]
I've thought about it myself, but don't know how to do this. If you succeed, extension will be amazing!

**Comment by TrueFantom** [comment]
Suggestion:

Blocks for working with sound effects.

- `set (sound effect v) effect for (sound v) to (number)`
- `change (sound effect v) effect for (sound v) by (number)`
- `clear sound effects for (sound v)`
- `(sound effect v)` (Reporter for this sprite)
- `(sound effect v) of (sound v)` (Reporter)

Blocks for working with sound volume.

- `set volume for (sound v) to (number)`
- `change volume for (sound v) by (number)`
- `volume of (sound v)` (Reporter)

Blocks for working with sound speed.

- `set speed for (sound v) to (number)` (Would be great to have a negative speed)
- `change speed for (sound v) by (number)` (Would be great to have a negative speed)
- `sound speed` (Reporter for this sprite)
- `sound speed of (sound v)` (Reporter)

Some more blocks.

- `is (sound v) playing?` (Boolean)
- `playing sounds count` (Reporter)
- `all playing sounds split by (string)` (Reporter) (Return sound names) (Split is space by default)

**Comment by TrueFantom** [comment]
Design suggestion:

`color1: '#c6003f',`
![color](https://user-images.githubusercontent.com/116278271/211031815-df13e397-fa69-42a1-932c-dc0555df8d0a.svg)

`const icon = 'data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHdpZHRoPSIyMjUuMzU0OCIgaGVpZ2h0PSIyMjUuMzU0OCIgdmlld0JveD0iMCwwLDIyNS4zNTQ4LDIyNS4zNTQ4Ij48ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMTI3LjMyMjcyLC02Ny4zMjI2KSI+PGcgZGF0YS1wYXBlci1kYXRhPSJ7JnF1b3Q7aXNQYWludGluZ0xheWVyJnF1b3Q7OnRydWV9IiBmaWxsLXJ1bGU9Im5vbnplcm8iIHN0cm9rZS13aWR0aD0iMCIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgc3Ryb2tlLWRhc2hhcnJheT0iIiBzdHJva2UtZGFzaG9mZnNldD0iMCIgc3R5bGU9Im1peC1ibGVuZC1tb2RlOiBub3JtYWwiPjxwYXRoIGQ9Ik0xMjcuMzIyNzMsMTgwYzAsLTYyLjIzMDAxIDUwLjQ0NzM5LC0xMTIuNjc3NCAxMTIuNjc3NCwtMTEyLjY3NzRjNjIuMjMwMDEsMCAxMTIuNjc3NCw1MC40NDczOSAxMTIuNjc3NCwxMTIuNjc3NGMwLDYyLjIzMDAxIC01MC40NDczOSwxMTIuNjc3NCAtMTEyLjY3NzQsMTEyLjY3NzRjLTYyLjIzMDAxLDAgLTExMi42Nzc0LC01MC40NDczOSAtMTEyLjY3NzQsLTExMi42Nzc0eiIgZmlsbD0iIzAwMDBmZiIgc3Ryb2tlPSJub25lIi8+PHBhdGggZD0iTTI0MC4wMDAwNCwxODBsLTk3LjUyMDY1LDU2LjMwMzU3Yy0yMC4xMTUzMywtMzQuODQwNzcgLTIwLjExNTMzLC03Ny43NjYzNyAwLC0xMTIuNjA3MTRjMjAuMTE1MzMsLTM0Ljg0MDc3IDU3LjI4OTk5LC01Ni4zMDM1NyA5Ny41MjA2NSwtNTYuMzAzNTd2MTEyLjYwNzE0IiBmaWxsPSIjZmYwMDAwIiBzdHJva2U9IiNmZmZmZmYiLz48cGF0aCBkPSJNMjQwLjAwMDAyLDE4MHYtMTEyLjYwNzE0YzQwLjIzMDY2LDAgNzcuNDA1MzIsMjEuNDYyOCA5Ny41MjA2NSw1Ni4zMDM1N2MyMC4xMTUzMywzNC44NDA3NyAyMC4xMTUzMyw3Ny43NjYzNyAwLDExMi42MDcxNGwtOTcuNTIwNjUsLTU2LjMwMzU3IiBmaWxsPSIjMDBmZjAwIiBzdHJva2U9IiNmZmZmZmYiLz48L2c+PC9nPjwvc3ZnPjwhLS1yb3RhdGlvbkNlbnRlcjoxMTIuNjc3Mjc1OjExMi42Nzc0MDUtLT4=';`
![sound](https://user-images.githubusercontent.com/116278271/211032257-261f8537-e137-42b3-ad5d-fc5a3487d8fd.svg)

baner
![sound baner](https://user-images.githubusercontent.com/116278271/211032364-9630b38b-5104-4d5a-9ee4-b75055fd8fd8.svg)

**Comment by SharkPool-SP** [comment]
Try this, It has everything youre looking for, and more!
**Tune Shark V3**
You can find it here:
**https://sharkpools-extensions.vercel.app/**
or
**https://github.com/TurboWarp/extensions/pull/1489**

Load it _unsandboxed_

**Comment by SharkPool-SP** [comment]
Sound expanded also achieves this now
