### ISSUE TITLE
Variable and list not compatible with cloud variables

### ISSUE THREAD

**Issue by InfinityLoopGames** [TurboWarp/extensions#1142]
I recently made a game in TurboWarp, packaged it and posted on itch.io and my website I made.

For some reason, the cloud variables do not work on both.

Here are the links. 
https://infinityloopgames.itch.io/teamtap
https://infinityloop-files.netlify.app/game-teamtap

Project created in TurboWarp
Project connected to wss://clouddata.turbowarp.org

I'm not sure why it doesn't work. Actually, none of my packaged games seem to work correctly with cloud data. I just didn't care too much, those other games didn't need cloud data to work. However, but this game relies heavily on it.

My other games are at https://infinityloop1.netlify.app/games

**Comment by InfinityLoopGames** [comment]
Ok, thanks for the explanation. Will changing the data minimally to where it knows there is a change in the data work? Example: Every second or two, every player will change every cloud variable by 0?

Or will I have to replace all the variable & list blocks?

**Comment by GarboMuffin** [comment]
it could help but we should be able to make that extension properly compatible

**Comment by InfinityLoopGames** [comment]
Ok, I'll change that and see if that will work as a temporary fix.

**Comment by GarboMuffin** [comment]
extension should now just support cloud variables
