### ISSUE TITLE
Sample project relicensing

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#1145]
I've sort of just realized we never decided on a license for the sample projects, so they've been GPLv3'd this entire time as that's the default for things in this repository. That's a problem as we want these to be something people can base their projects on, but they are unknowingly being subject to the GPL's virality clauses. Not ideal.

My proposal is that we relicense them under CC-BY 4.0 https://creativecommons.org/licenses/by/4.0/:

 - GPLv3 compatible
 - credit required (we can add comments inside the sample projects)
 - no GPL virality or share-alike clause, commercial use allowed
 - standard code licenses don't apply well to things like images/sounds/etc. inside the sample projects
 - matches how people are actually going to use them anyways

**Comment by GarboMuffin** [comment]
@LilyMakesThings @DNin01 @Xeltalliv @David-Orangemoon

You contributed sample projects so this would require your consent

**Comment by Xeltalliv** [comment]
I consent

**Comment by David-Orangemoon** [comment]
Ok

**Comment by DNin01** [comment]
Yeah, I think a Creative Commons license is a better fit for them. I'd be fine with CC-BY 4.0.

Does that apply to the assets they re-use from other sources? Most of mine just use TurboWarp-logo-related things, the Dango from Twemoji, and some simple shapes and icons, but one of them uses Turbo Robot, which was made for TurboWarp by a Scratch user. Do we need to add any notes/credits there?

**Comment by GarboMuffin** [comment]
It would be a good idea to credit things appropriately

**Comment by LilyMakesThings** [comment]
this is fine
