### ISSUE TITLE
Dynamic Imports with Custom Extensions?

### ISSUE THREAD

**Issue by NotJosh440** [TurboWarp/extensions#1157]
I'm not entirely the best with using the custom extensions but I was wondering if you could do something along the lines:
`import ThisImport from "thisimport.js";`
and I get an error like "Cannot use import statement outside a module."
Trying to use `require("thisimport.js");` and I get "require is not defined" in the console.
edit: not sure if this is the right place to post this and if its not where would I put this? I was brought here by a reddit post

**Comment by David-Orangemoon** [comment]
Require is node js so it cannot be used
And since extensions aren't ran as modules they cannot use import my recommendation is to fix up the file you want to import for a non module file mining it give credits and put it in your extensions script.

**Comment by GarboMuffin** [comment]
Nothing technically stops you from using a dynamic import() if for some reason you can't statically include it in the JS, it just won't be accepted here
