### ISSUE TITLE
Lack of hierarchy will not scale for personal extensions

### ISSUE THREAD

**Issue by True-Fantom** [TurboWarp/extensions#116]
Currently unsandboxed custom extensions are limited to this repository. And considering #61 it is unlikely that another way of placing them will appear in the near future. This is where the problem arises, which I myself have already encountered 3 times. If any extension already exists, and one wants to add a similar one or make an alternative version, it will clog the directory and will not be accepted. This greatly limits the extension-creators! TurboWarp is a platform for everyone, and it would be right to keep this policy in relation to custom extensions!

Personally, I came up with such a solution method:
The ability to create a personal folder in /extensions/ that will not interfere with the main directory.
![Screenshot_430](https://user-images.githubusercontent.com/116278271/211087326-6592fffe-175e-4e13-a009-8a40ef88b1e9.png)
Or create a separate folder in the main.
![Screenshot_431](https://user-images.githubusercontent.com/116278271/211089224-0c1130a4-8e1e-4541-8525-18748286e755.png)

This is just my suggestion for a solution, but the problem somehow needs to be fixed.

**Comment by GarboMuffin** [comment]
We should make it so that you can use folders in `extensions`, yeah

**Comment by softedco** [comment]
For now you can make changes to already existing extensions, the only limitations you have on doing that are the ones explicitly stated in CONTRIBUTING.md

**Comment by GarboMuffin** [comment]
we do user folders now
