### ISSUE TITLE
Can I create C-SHAPED blocks in a Turbowarp extension?

### ISSUE THREAD

**Issue by sfederici** [TurboWarp/extensions#1162]
I hope I didn't study the whole extentions' documentation to do something that I can't do.

What I need to do is to create a new C-SHAPED block (the old "forever if" control block, that was available in Scratch 1.4). But, in the block types, in the whole documentation, and in the extensions in the gallery I couldn't find any example of such a block.

Are C-SHAPED blocks something that cannot be created in Scratch/TurboWarp extensions? Or did I simply miss the relevant steps? Thanks in advance for your help

**Comment by Stiwen02** [comment]
Unfortunately in the “Wrapping up” section is mentioned that C-Shaped blocks aren't supported yet. https://docs.turbowarp.org/development/extensions/wrapping-up#things-that-are-not-supported-yet

**Comment by sfederici** [comment]
:-(

**Comment by CubesterYT** [comment]
Hello again @sfederici! C shaped blocks are not yet displayed in the documentation, but C blocks are now supported! It's been implemented recently, so the documentation hasn't been updated. The block type is "Scratch.BlockType.LOOP" and "Scratch.BlockType.CONDITIONAL". You can find examples hidden in the test folder of this repository.

**Comment by sfederici** [comment]
Excellent, going to experiment

**Comment by sfederici** [comment]
So, everything worked very well! In the end, I could add my C-SHAPED "forever if" block to the Control category by:
- creating a new extension with the "control" ID, then overriding the standard "Control" category 
- creating a new C-SHAPED "forever if" block in the extension by using the new LOOP Scratch.BlockType
- adding all standard Control blocks to my extension by using the new XML Scratch.BlockType 

Every old project that I created with my custom version of Turbowarp desktop (containing the "forever if" block) now loads and runs just fine in the Turbowarp after my extension is loaded.

What I need now is [the "load-extensions" addon to be updated](https://github.com/TurboWarp/desktop/discussions/857), so that even a custom extension (pasted in the "text" tab) is loaded at startup. If this is not possible, all my work is useless, as I can't ask my students to load the extension in the offline Turbowarp desktop (we use the desktop version as we need to avoid not to be able to teach labs when internet is down) every time they open Turbowarp. 

In the meantime, if someone wants to play with the "forever if" block (resurrected from Scratch 1.4) you can load the "foreverif.js" extension and then test it on the "pong.sb3" project included [here](https://github.com/TurboWarp/extensions/files/13461533/Archivio.zip)

**Comment by CubesterYT** [comment]
Let's go!

**Comment by horizontal-shading** [comment]
Foreverif.js doesn't work.

**Comment by gomiigg** [comment]
Tested this on TW Desktop on Mac. The extension loads fine but does not seem to work. The blocks appear but any code inside them is not run.

**Comment by sfederici** [comment]
> Tested this on TW Desktop on Mac. The extension loads fine but does not seem to work. The blocks appear but any code inside them is not run.

Interesting. Did you disable the compiler? As @CST1229 realized, the yield should be removed and replaced with a simple return. But I don't need the compiler, so I didn't updated it yet.

**Comment by CST1229** [comment]
> the yield should be removed and replaced with a simple return

*I meant a util.startBranch, like
```js
const condition = Scratch.Cast.toBoolean(args.CONDITION);
// If the condition is true (repeat IF), start the branch.
if (condition) {
	util.startBranch(1, true);
} else {
	// The compiler doesn't support util.yield() yet, so this is a workaround
	util.startBranch(2, true);
}
```

**Comment by Colin1248** [comment]
how do I put text in between 2 branches like the if-else block?

**Comment by CubesterYT** [comment]
@Colin1248 Like this:
`
text: ["if [CONDITION]", "else"]
`
