### ISSUE TITLE
Extension working on the online version of Turbowarp but not working on the deskop version

### ISSUE THREAD

**Issue by sfederici** [TurboWarp/extensions#1163]
I created an extension that adds the "forever if" block of Scratch 1.4 back to Turbowarp. The source code, foreverif.js, is [here](https://github.com/TurboWarp/extensions/files/13461533/Archivio.zip) (the zip includes a pong.sb3 test file).

When I test it by running [https://turbowarp.org/editor?extension=http://localhost:8000/sfederici/foreverif.js](https://turbowarp.org/editor?extension=http://localhost:8000/sfederici/foreverif.js)

everything works fine. The "forever if" blocks are visibile in the script area and when I run the project everything works as expected (the bottom paddle moves left and right by using the arrow keys and the ball bounces and breaks the green bricks).

Instead, if I load the extension in Turbowarp 1.9.2 by pasting the code in the "text" tab of the custom extension loading dialog
- the prog.sb3 project can still be loaded and the "forever if" blocks are visible **but**
- the blocks do not run as expected, that is the scripts embedded in the "forever if" blocks are not run

Is there a clear reason that I don't see why this happens?

**Comment by CST1229** [comment]
I think this is caused by the compiler not supporting `util.yield()` (for me, on the project you linked the paddle does move if you hold an arrow key while pressing the green flag), and you might just have the Disable compiler in editor addon enabled on web.
I have found a weird workaround though: running a nonexistent branch in loop mode, e.g 2 if the block has one branch.

**Comment by sfederici** [comment]
Yes! Excellent! By disabling the compiler (that I don't need for my students and that it is disabled in my current custom Turbowarp for other incompatibilities, with the Turbowarp debugger if I'm not wrong) everything works even in the desktop version.

Thanks a lot, really
