### ISSUE TITLE
Make an accocunt, or discord account connector plugin

### ISSUE THREAD

**Issue by Tycho10101** [TurboWarp/extensions#1165]
I'd be nice if we could use discord as an authentication

**Comment by Tycho10101** [comment]
hello?

**Comment by GaypataponALT** [comment]
> hello?

you need to add a description

**Comment by GaypataponALT** [comment]
also i agree with you, we need that extention

**Comment by InfinityLoopGames** [comment]
Like something that would connect to Discord API and get stats about users and servers?

**Comment by Tycho10101** [comment]
> > hello?
> 
> you need to add a description

thanks for telling me that
fixed it

**Comment by GaypataponALT** [comment]
No problem 👍
