### ISSUE TITLE
why can't run extensions

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/extensions#1166]
![image](https://github.com/TurboWarp/extensions/assets/118588391/809bd1fe-7659-4487-b399-c619f15877f6)

such as encoding , notifications.

**Comment by GarboMuffin** [comment]
Encoding's Chinese localization has a bug, will be fixed shortly

Notifications hasn't been touched for a month, what error does it give you?

**Comment by qxsck** [comment]
> 编码的中文本地化有一个bug，将很快修复
> 
> 通知已经一个月没有触碰了，它会给你什么错误？

like this
