### ISSUE TITLE
is there a way to embed games inside the project?

### ISSUE THREAD

**Issue by GaypataponALT** [TurboWarp/extensions#1170]
I tried embedding a html game inside the project but nothing shows up, so is there a way to embed games on the project??

**Comment by GaypataponALT** [comment]
btw this is my new acc (AGAIN)

**Comment by GaypataponALT** [comment]
pls help :(

**Comment by SurvExe1Pc** [comment]
not if it uses javascript

**Comment by softedco** [comment]
If your game is hosted on a website you can embed it

**Comment by GaypataponALT** [comment]
> If your game is hosted on a website you can embed it

it isnt hosted on a website, i compiled a project to html and i want to embed it inside the project

**Comment by GaypataponALT** [comment]
> So you want to put a project in a project?

yes thats what im trying to do

**Comment by GaypataponALT** [comment]
is there a way to do it??

**Comment by CubesterYT** [comment]
I don't even know if this will work, but open the html file you downloaded in a notepad or something, copy everything inside of it, add the iframe extension, and paste the html code in the iframe html block specifically.

**Comment by GaypataponALT** [comment]
> I don't even know if this will work, but open the html file you downloaded in a notepad or something, copy everything inside of it, add the iframe extension, and paste the html code in the iframe html block specifically.

but isnt the text too much?

**Comment by GaypataponALT** [comment]
nope i tried it, it doesnt show up

**Comment by GaypataponALT** [comment]
i even tried the file extension and it still doesnt work, i also tried zip but that doesnt work too, please can anyone help me with this

**Comment by GarboMuffin** [comment]
"tried the file extension" and "tried zip" are not enough for us to be able to help you. post some actual code so we can see why it doesn't work

**Comment by GaypataponALT** [comment]
> "tried the file extension" and "tried zip" are not enough for us to be able to help you. post some actual code so we can see why it doesn't work

i think its best that i compile it to zip and then post it on github, it acually worked
