### ISSUE TITLE
Disable Box2d

### ISSUE THREAD

**Issue by SebasMCYT** [TurboWarp/extensions#1171]
You can enable Box2d physics on a sprite with this block:

![image](https://github.com/TurboWarp/extensions/assets/126848249/bbe939e8-1678-44ab-81a8-b9874ce9f06b)

I heavily rely on this extension for one of my projects, but recently I ran into the problem that there is no "disable" block.

Could it be added?

**Comment by wolfieboy09** [comment]
Well, let me look in the code for a way to disable it, and make a pull request for you

**Comment by SebasMCYT** [comment]
Any progress on this?

**Comment by GarboMuffin** [comment]
yeah it's done
