### ISSUE TITLE
How do i move the iframe with viewport on?

### ISSUE THREAD

**Issue by GaypataponALT** [TurboWarp/extensions#1174]
I tried making a fake OS for my game and i wanted to add a web app but if i set the iframe to scale then the entire iframe became messed up because of the small screen resolution but if i set it to viewport then the iframe cant move and i dont wanna change my screen size for the project, can anyone who worked on the iframe extention help me?

**Comment by GaypataponALT** [comment]
also the OS on my website is not the latest one, the latest one is in my computer

**Comment by GarboMuffin** [comment]
post some example scripts, they work fine for us

**Comment by GaypataponALT** [comment]
> post some example scripts or videos, they work fine for us

![Untitled26_20231202230319](https://github.com/TurboWarp/extensions/assets/152406097/f61e6856-8bb7-4bf9-aee7-b74e3b94d708)
I drew a example on viewpoint and scale iframe

**Comment by GaypataponALT** [comment]
With scale everything is too large to see in iframe and with viewpoint everything is not too big but you can move the iframe with viewpoint

**Comment by GaypataponALT** [comment]
Is my example okay?

**Comment by GarboMuffin** [comment]
Okay, I tested it again and moving the frame with viewport scaling is broken. I will get that fixed

**Comment by GaypataponALT** [comment]
Ok, thanks

**Comment by GaypataponALT** [comment]
Thank you for fixing it
