### ISSUE TITLE
encode turbowarp extensions such that they can be loaded from projects on scratch

### ISSUE THREAD

**Issue by TheAwesome98-Real** [TurboWarp/extensions#1185]
it would be useful if there were a way to export projects that use turbowarp-specific features in a way that scratch could load them. this way, you could do something like
```
if <is turbowarp?> {
  open file ( ... )
} else {
  broadcast (import list)
}
```
my idea was that they could be encoded in custom blocks, like this:
![image](https://github.com/TurboWarp/extensions/assets/59254971/4b54920d-1ea0-42d7-9320-7931f59f617b)
(i've not written the full url for security reasons. it seems dangerous for a scratcher to suddenly have full access to an entire browser. you could, however, change this, if you see fit.)
there are a few problems with this approach:
- security issues, as previously stated
- these blocks do nothing, and there is no guarantee they're in an `if <is turbowarp?> { }` block
- there is no way to encode arguments in reporters
- this may confuse new scratchers. this could be mitigated with a comment, i suppose? we could avoid technical language so that younger scratchers could understand what the blocks are for.

**Comment by Ashimee** [comment]
this is what addon blocks do, but different

**Comment by Mickmick2012** [comment]
I Remember that Garbomuffin said No because more people will start uploading turbowarp only things on Scratch (From what i remember)

**Comment by Ashimee** [comment]
this is also true yeah
________________________________

**Comment by TheAwesome98-Real** [comment]
> this is what addon blocks do, but different

i think you might've misunderstood this issue (or maybe i misunderstood the comment)

**Comment by TheAwesome98-Real** [comment]
> I Remember that Garbomuffin said No because more people will start uploading turbowarp only things on Scratch (From what i remember)

that is a good point. i can't think of a solution to that at all.

**Comment by InfinityLoopGames** [comment]
If you're suggesting changing blocks so they can be compatible with scratch, that wouldn't work because there are no blocks for setting pointer-lock, or some of the other extensions. There is no way to do that in Scratch.

**Comment by Ashimee** [comment]
> > this is what addon blocks do, but different
> 
> i think you might've misunderstood this issue (or maybe i misunderstood the comment)

the debugger blocks are just fake custom blocks which is why you can save a project with debugger blocks and still use it even without the addon

**Comment by TheAwesome98-Real** [comment]
> If you're suggesting changing blocks so they can be compatible with scratch, that wouldn't work because there are no blocks for setting pointer-lock, or some of the other extensions. There is no way to do that in Scratch.

i think you should re-read my issue, because no, that was not what i was suggesting at all. /nm

**Comment by DNin01** [comment]
This would probably encourage people to create projects that don't work on Scratch and then share them on Scratch anyway, which is against the premise of the Scratch website. I can tell by section 4.4 on their terms of use, which states that you may not share projects that were created using modified versions of the Scratch editor (and was probably more useful back in the Scratch 1.x days when we didn't have a website player, to prevent people from asking people to download modified versions of Scratch to run projects), and from common sense that the team probably wouldn't be very happy if more people started doing this.
