### ISSUE TITLE
Empty defaultValue for NUMBER argument❓

### ISSUE THREAD

**Issue by True-Fantom** [TurboWarp/extensions#119]
It doesn 't work in extensions , but it does in Scratch
![Screenshot_180](https://user-images.githubusercontent.com/116278271/211208260-9b2067f7-0d8f-4253-92bf-673397887b29.png)
![Screenshot_181](https://user-images.githubusercontent.com/116278271/211208265-4358f164-1072-4d8a-b237-fedf0582a3cf.png)
![Screenshot_177](https://user-images.githubusercontent.com/116278271/211208269-f54c5203-6226-422a-95dd-6b8b5041f084.png)

**Comment by TrueFantom** [comment]
And it is contained in Scratch
![Screenshot_177](https://user-images.githubusercontent.com/116278271/211160871-35f5d485-a368-4c20-921d-5a67df1e4ee6.png)

**Comment by OeildeLynx31** [comment]
You can try to use '\'.

**Comment by True-Fantom** [comment]
@OeildeLynx31 Thanks for the answer, but I think it's not very convenient(

And I had a bug with displaying panel with numbers because of this...
