### ISSUE TITLE
Suggestion: Prohibit extensions for money making in CONTRIBUTING.md

### ISSUE THREAD

**Issue by softedco** [TurboWarp/extensions#1195]
Every now and then an issue or a discussion pops up suggesting adding an extension that will allow showing ads, making in-app purchases or other things that are used to make money off of user action. Due to various reasons these types of extensions can't be on turbowarp so I suggest stating that in the contributing documentation. That will prevent people from wasting their time making a zillionth issue saying that we should add an ads extension or a discussion saying should we add an ads extension question mark. This would also make it so if someone still does that the contributors could easily point them to the documentation instead of finding and tagging that one closed issue that had everything explained.

**Comment by CubesterYT** [comment]
Perfect, this is exactly what we need.

**Comment by PPPDUD** [comment]
Most kids nowadays don't make enough money; don't make the problem worse.

**Comment by GarboMuffin** [comment]
> Most kids nowadays don't make enough money; don't make the problem worse.

Nobody here is saying that you can't make money off of TurboWarp -- you very much can and in fact we **legally can't stop you from doing that**.

We're just saying that as volunteers, we're not allowing those to be added here.

Remember again that everything here needs to be GPLv3 compatible and I guarantee whatever advertising library you find will definitely not publish their source code in the "preferred form of the work for making modifications to it"

**Comment by softedco** [comment]
> Most kids nowadays don't make enough money; don't make the problem worse.

Nothing will change apart from the fact that people would stop wasting their time, such extensions were not accepted before and the issue suggests formally letting people know about that.
