### ISSUE TITLE
Need Feedback: Game Settings UI Extension for Scratch

### ISSUE THREAD

**Issue by six-ddc** [TurboWarp/extensions#1196]
I'm working on something cool for Scratch creators – a plugin to make designing game settings UIs a breeze. 🚀

The effect of the imagined blocks is probably like this:

<img width="480" alt="图片" src="https://github.com/TurboWarp/extensions/assets/10087571/60e60ed8-8d5b-442a-b932-5f9b929d5667">

I'm really keen to get your take on this:
- Would this make your life easier when building games in Scratch?
- Any pain points you've hit with UI stuff in Scratch?
- What features would you love to see in this extension?

Super excited to hear your thoughts.

**Comment by LilyMakesThings** [comment]
This is really not the place to be discussing Gandi IDE projects.

**Comment by six-ddc** [comment]
@LilyMakesThings Sorry, this is a misunderstanding. It is not about discussing Gandi IDE. I want to submit this Extension PR to TurboWarp, just want to understand everyone's needs here. If it is not appropriate, I can close this issue.

**Comment by Martinelplayz** [comment]
> @LilyMakesThings Sorry, this is a misunderstanding. It is not about discussing Gandi IDE. I want to submit this Extension PR to TurboWarp, just want to understand everyone's needs here. If it is not appropriate, I can close this issue.

your saying you'd port this to turbowarp? that'd be pretty cool!

**Comment by SharkPool-SP** [comment]
this is just better input

**Comment by LilyMakesThings** [comment]
> this is just better input

It's not the same extension, just a similar concept that's been executed differently
