### ISSUE TITLE
Clipping & Blending: More blending method

### ISSUE THREAD

**Issue by YogaindoCR** [TurboWarp/extensions#1240]
Image are taken from Sprite Effect on PenguinMod
![image](https://github.com/TurboWarp/extensions/assets/132117105/54bdfe98-5319-473b-bdea-d61c6264a6ed)
It would be great if this blending effect added to this Extensions

**Comment by CubesterYT** [comment]
@SharkPool-SP, What are your thoughts on this situation, Captain

**Comment by SharkPool-SP** [comment]
> @SharkPool-SP, What are your thoughts on this situation, Captain

@YogaindoCR Ill take a look and see if this is possible, it should be a part of the rendering system.

**Comment by SharkPool-SP** [comment]
Yeah @CubesterYT @YogaindoCR These blending types dont exists. They are exclusive to svgs

**Comment by YogaindoCR** [comment]
> Yeah @CubesterYT @YogaindoCR These blending types dont exists. They are exclusive to svgs (costume wise)

Oh alright, Your "Sprite Effect" Extension can be the alternative for this, A Really Cool extension by the way.

**Comment by SharkPool-SP** [comment]
> > Yeah @CubesterYT @YogaindoCR These blending types dont exists. They are exclusive to svgs (costume wise)
> 
> Oh alright, Your "Sprite Effect" Extension can be the alternative for this, A Really Cool extension by the way.

Tysm! :)
It is pr-ed here, so whenever it gets merged, it will be fun
