### ISSUE TITLE
Deltatime's DT variable is using 1 fps as reference

### ISSUE THREAD

**Issue by PixelGuy123** [TurboWarp/extensions#1249]
If you try now the extension with Scratch's default 30 fps, you'll realize the deltatime variable is REALLY low, like, 0.03 for some reason, when you use 1 fps instead, you notice it turns into 1, basically implying it is using 1 fps as reference. And I can't figure out if there's any setting I'm not seeing for it

https://github.com/TurboWarp/extensions/assets/89644121/443e2c3e-91c3-4879-a83c-44c77ab2d540

**Comment by GarboMuffin** [comment]
Delta time tells you how many seconds have passed since the previous frame. You can convert it to whatever you want by just multiplying.

**Comment by GarboMuffin** [comment]
Sure the extension could just multiply by 30 for you, but then other people will need to divide by 30. Having it be in seconds makes operations like "make this sprite move left at 50 pixels per second" much simpler to reason about and is more "pure", mathematically.

The whole point of delta time is that you aren't tying to framerate so having the blocks operate with a "reference" framerate of 30 FPS would be very arbitrary

**Comment by PixelGuy123** [comment]
I actually forgot to test this method, thanks to clarifying it!
