### ISSUE TITLE
Animated Text gets cut off when a block from More Motion is used

### ISSUE THREAD

**Issue by XShrunk** [TurboWarp/extensions#1251]
i dont know if this happens with other blocks or extensions, i havent tested it further, but here when the size is reduced the text gets cut off. the width does not change. however it is fixed if, after reducing the size, you show the sprite and show the text back again
![image](https://github.com/TurboWarp/extensions/assets/79948572/ea6860fc-7282-45f6-a4b0-fcf9ea4df121)
![image](https://github.com/TurboWarp/extensions/assets/79948572/f8c4f2b3-e422-49d9-8912-db74c32ddd3c)

**Comment by SharkPool-SP** [comment]
is this still happening? Seems fine to me

**Comment by SharkPool-SP** [comment]
closing to inactivity. It seems to have been fixed as well
