### ISSUE TITLE
Unknown extension error.

### ISSUE THREAD

**Issue by ZekusV** [TurboWarp/extensions#126]
I have lost a projects source to the 'Could not load project: Error: Unknown extension' error because I am unable to open it.
Is there a way I can get the original project back without it loading the non-existing extension?

**Comment by showierdata9978** [comment]
download the SB3, unzip it, open project.json, scroll til you see extentions, delete that extention, rezip it all back into an SB3

**Comment by Mickmick2012** [comment]
![image](https://user-images.githubusercontent.com/110345721/211375850-808f6964-c1b9-441b-a167-3de571d647e8.png)

**Comment by Mickmick2012** [comment]
download 1.7.0beta0 for more info about the extension name

**Comment by Mickmick2012** [comment]
look at the extension name
![image](https://user-images.githubusercontent.com/110345721/211376728-36ceba50-dcb8-4b8e-bf51-db3344e3c961.png)
rename and replace ".sb3" by ".zip"
![image](https://user-images.githubusercontent.com/110345721/211376913-2061bf6d-d89f-4344-912a-d577baee390a.png)
![image](https://user-images.githubusercontent.com/110345721/211377330-de072c76-c7b3-49aa-85c8-cc4eca87605f.png)
unzip it
open "project.Json" with notepad or something like that (but not Word)
![image](https://user-images.githubusercontent.com/110345721/211377674-c0ddbdfe-160a-4cd5-ae7b-70cbb33ef5c0.png)
press control and f (f for find)
type in "Extensions"
![image](https://user-images.githubusercontent.com/110345721/211378011-7e0000ef-c571-4f72-bdb8-a891de5839af.png)
press enter
you will find "extension" Highlight
after normaly you will find urls 
delete all of them if you want or you can delete the one that dosen't work
save the file (with the same name)
press control + A
right click and zip it
rename back to projectname.sb3
run it and see

**Comment by Mickmick2012** [comment]
Oh and btw you need to load the url BEFORE you open the project with 1.6.2 and earlier

**Comment by GarboMuffin** [comment]
if you're still stuck on this, please comment and it will be reopened
