### ISSUE TITLE
How can I add my own extension to TurboWarp?

### ISSUE THREAD

**Issue by WAYLIVES** [TurboWarp/extensions#1312]
**How can I add my own extension to TurboWarp? There's probably a help for that, but I can't find that help.**

**Comment by CST1229** [comment]
https://docs.turbowarp.org/development/extensions/introduction

**Comment by WAYLIVES** [comment]
> https://docs.turbowarp.org/development/extensions/introduction

Thanks, but that's not what I mean. xD I mean, how do I add my extensions to the gallery?

**Comment by David-Orangemoon** [comment]
> > https://docs.turbowarp.org/development/extensions/introduction
> 
> Thanks, but that's not what I mean. xD I mean, how do I add my extensions to the gallery?

Submit a pr with your extension in a folder with your name under the extensions folder.

**Comment by WAYLIVES** [comment]
> > > https://docs.turbowarp.org/development/extensions/introduction
> > 
> > 
> > Thanks, but that's not what I mean. xD I mean, how do I add my extensions to the gallery?
> 
> Submit a pr with your extension in a folder with your name under the extensions folder.

ok, thank you
