### ISSUE TITLE
iframe bug

### ISSUE THREAD

**Issue by PlayfulMathematician** [TurboWarp/extensions#1316]
iframes just don't work even with internet

**Comment by LilyMakesThings** [comment]
Can you give us more information? Screenshots perhaps? This is extremely vague.

We can't even begin to fix your issue if you don't tell us what's wrong.

**Comment by PlayfulMathematician** [comment]
https://github.com/Team-Oneninet/TurbOS/issues/2

**Comment by LilyMakesThings** [comment]
![image](https://github.com/TurboWarp/extensions/assets/127533508/9ed87346-8b94-416f-b075-0a144d60e725)

Websites need to give Iframes embed permissions in order for them to be viewed analogously to viewing them through a browser. Very few websites will grant this and usually have some kind of embed option with less features.

**Comment by Team-Oneninet** [comment]
Is there a way around this using custom Javascript?

**Comment by PlayfulMathematician** [comment]
edited iframes is very difficult

**Comment by Mistium** [comment]
> edited iframes is very difficult

https://github.com/TurboWarp/extensions/issues/1334

**Comment by GarboMuffin** [comment]
does iframes plus even solve the most-websites-opt-out-problem?

**Comment by Mistium** [comment]
> does iframes plus even solve the most-websites-opt-out-problem?

I think? It can load any website cos it's at the browser level, can you give me a url example that would not be able to load normally?

**Comment by LilyMakesThings** [comment]
> > does iframes plus even solve the most-websites-opt-out-problem?
> 
> I think? It can load any website cos it's at the browser level, can you give me a url example that would not be able to load normally?

https://turbowarp.org/

**Comment by Mistium** [comment]
![Screenshot 2024-03-09 at 18 44 54](https://github.com/TurboWarp/extensions/assets/92952823/6eaf3c39-8ce6-4282-a5a0-f5c01fd0e624)

turbowarp tries but you have prevention measures

**Comment by Mistium** [comment]
![Screenshot 2024-03-09 at 18 45 28](https://github.com/TurboWarp/extensions/assets/92952823/b86f518b-782d-4ba3-9a87-bd70636c8738)

does display the url tho

**Comment by CST1229** [comment]
> I think? It can load any website cos it's at the browser level, can you give me a url example that would not be able to load normally?

https://google.com/

**Comment by Mistium** [comment]
> > I think? It can load any website cos it's at the browser level, can you give me a url example that would not be able to load normally?
> 
> https://google.com/

google works, ive tested

**Comment by Mistium** [comment]
https://github.com/TurboWarp/extensions/assets/92952823/cd43020f-4e64-40a1-9491-32bb92e5ef25

proof im not bamboozling
