### ISSUE TITLE
How to make button event

### ISSUE THREAD

**Issue by StioStudio** [TurboWarp/extensions#133]
I know that buttons is not really working in extensions, but is it some way I can get the button element in a easy way. I want to do button.onclick = ()=>{do something}

**Comment by softedco** [comment]
I have an ugly solution to this, you can make a reporter block that does this:

![image](https://user-images.githubusercontent.com/100989385/211532345-4bbe920d-4f0f-4625-ac81-207e8ecc491a.png)

**Comment by StioStudio** [comment]
> I have an ugly solution to this, you can make a reporter block that does this:
> 
> ![image](https://user-images.githubusercontent.com/100989385/211532345-4bbe920d-4f0f-4625-ac81-207e8ecc491a.png)

I don't think that works, but I can check

**Comment by softedco** [comment]
> > I have an ugly solution to this, you can make a reporter block that does this:
> > ![image](https://user-images.githubusercontent.com/100989385/211532345-4bbe920d-4f0f-4625-ac81-207e8ecc491a.png)
> 
> I don't think that works, but I can check

It works, I tested it.

**Comment by StioStudio** [comment]
> > > I have an ugly solution to this, you can make a reporter block that does this:
> > > ![image](https://user-images.githubusercontent.com/100989385/211532345-4bbe920d-4f0f-4625-ac81-207e8ecc491a.png)
> > 
> > 
> > I don't think that works, but I can check
> 
> It works, I tested it.

Thanks :D
