### ISSUE TITLE
Iframe Plus

### ISSUE THREAD

**Issue by Mistium** [TurboWarp/extensions#1334]
I made an iframe extension a while back that allows you to place unlimited iframes with 0 restrictions on site contents and cors and edit them in real time, at runtime. some bugs with a few blocks sure...

https://github.com/Mistium/Origin-OS/blob/main/Extensions/iframeplus.js

![iframePlus](https://raw.githubusercontent.com/Mistium/Origin-OS/main/Extensions/Iframeplus.png)

**Comment by Mistium** [comment]
(the current iframe extension isn't the best)

**Comment by LilyMakesThings** [comment]
If you don't like the current iframe extension, you're free to submit an update or your own take

**Comment by Mistium** [comment]
> If you don't like the current iframe extension, you're free to submit an update or your own take

i literally just put in a pull request for my extensions but i think that i have a few errors that wouldn't actually affect the extension but are just bad practices lol

**Comment by Mistium** [comment]
https://github.com/TurboWarp/extensions/pull/1335

**Comment by qxsck** [comment]
can it add iframes in the same time?

**Comment by Mistium** [comment]
> can it add iframes in the same time?

unlimited

**Comment by Mistium** [comment]
https://github.com/Mistium/Origin-OS/blob/main/Extensions/iframeplus.js

**Comment by qxsck** [comment]
> > can it add iframes in the same time?
> 
> unlimited, you can put down and manage as many iframes as you want

so good

**Comment by CubesterYT** [comment]
Closing as not planned since iFrame Plus isn't technically valid for this repository.
