### ISSUE TITLE
Text Extension: New Block Idea

### ISSUE THREAD

**Issue by YogaindoCR** [TurboWarp/extensions#1352]
Can we have this block?
![image](https://github.com/TurboWarp/extensions/assets/132117105/da19c0f7-6942-4f1d-aaeb-031e4e30c631)

**Comment by CST1229** [comment]
This is workaroundable with the JSON extension:
![image](https://github.com/TurboWarp/extensions/assets/68464103/62871850-eec7-4256-ab9c-dd15dad98740)

**Comment by YogaindoCR** [comment]
> This is workaroundable with the JSON extension: ![image](https://private-user-images.githubusercontent.com/68464103/311720784-322d5a99-b133-4c67-b0ef-0e15ca584e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDgyNzEsIm5iZiI6MTcxMDMwNzk3MSwicGF0aCI6Ii82ODQ2NDEwMy8zMTE3MjA3ODQtMzIyZDVhOTktYjEzMy00YzY3LWIwZWYtMGUxNWNhNTg0ZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA1MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTA3MjJhMTRlNzUwZGQ0NTUyOGQwZDE0MDQwNTUxOTE0MTY2M2Q2ZDJkMjNkNWI5ZjY2ZGVlMjMwZjM5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fj7Ct7INRgAOEstWNz8vcZJaXtRa3Q6QnXtDJ432wGw)

Oh i didn't know it was possible with json before, This is helpful Thanks
