### ISSUE TITLE
Sound Expanded Volume Controls Do Not Work

### ISSUE THREAD

**Issue by ziqiangao** [TurboWarp/extensions#1355]
The volume control blocks, change volume by, specifically does not work and instead it is zero when run.

Load the extension and click the change volume by block, turn on the volume monitor

**Comment by SharkPool-SP** [comment]
> The volume control blocks, change volume by, specifically does not work and instead it is zero when run.
> 
> Load the extension and click the change volume by block, turn on the volume monitor

should be fixed now

**Comment by ziqiangao** [comment]
The change volume block now works, the set volume does not work however
