### ISSUE TITLE
VM override not working

### ISSUE THREAD

**Issue by veggiecan0419** [TurboWarp/extensions#1356]
Hi everyone, I am coding an extension that needs to override a VM function, but I can't get it to work

```javascript
(function(Scratch) {
  "use strict";

  if (!Scratch.extensions.unsandboxed) {
    throw new Error("The console log moves extension must run unsandboxed");
  }

  const sMotion = Scratch.vm.runtime.ext_scratch3_motion;
  let oldMoveSteps = sMotion.moveSteps;
  sMotion.moveSteps = function(args, util) {
    oldMoveSteps(args, util);
    console.log("moveSteps called");
  }

  class consoleLogMoves {
    getInfo() {
      return {
        id: "moveLogger0419",
        name: "console log moves",
        blocks: [
        ],
      };
    }

  }
  Scratch.extensions.register(new consoleLogMoves());
})(Scratch);
```
Can someone please explain why this doesn't work.
(I need to override it with something else, but first this needs to work)

**Comment by LilyMakesThings** [comment]
overriding the exports used by the compiler sometimes doesn't work

**Comment by veggiecan0419** [comment]
Is there a way one can force the issue? Or is there another way that might work?

**Comment by GarboMuffin** [comment]
in that specific case, you want to override _moveSteps not moveSteps

**Comment by veggiecan0419** [comment]
So its basically not possible?

**Comment by CST1229** [comment]
> So basically its not possible?

I think it is (_moveSteps is another function defined in ext_scratch3_motion)

**Comment by GarboMuffin** [comment]
I thought my answer was enough but here's a code sample

```js
vm.runtime.ext_scratch3_motion._moveSteps = (a, b) => { console.log(a, b); }
```

**Comment by veggiecan0419** [comment]
@GarboMuffin Sorry!

**Comment by veggiecan0419** [comment]
But why does it only work with _moveSteps?

**Comment by GarboMuffin** [comment]
most of the builtin blocks are given special treatment by compiler so overriding all of them might be difficult or not possible at all. good luck with whatever you're doing. may not be able to help much
