### ISSUE TITLE
gamejolt might have banned turbowarp.org from making api requests

### ISSUE THREAD

**Issue by softedco** [TurboWarp/extensions#1367]
When making a request it says that the response header doesn't allow turbowarp.org
Status code 429.

I've had concerns about this, after all, exposing a lot of inexperienced people to a very simplified framework for making requests makes it so there is a very low bar for entry to basically do a decentralized ddos of the api. The status code says it's too many requests which confirms it.

I don't know if there are any ways to fix this or if it's even possible. I kind of expected this to happen but I also hoped it won't, which made it so I didn't find it necessary to enforce some kind of etiquette for people making requests, regardless of which it is still on me.

**Comment by Drago-Cuven** [comment]
still works for me

**Comment by softedco** [comment]
> still works for me
> 

well then this issue post was useless
