### ISSUE TITLE
Allow for WASM extensions

### ISSUE THREAD

**Issue by reesericci** [TurboWarp/extensions#1392]
Hello -

I recently wrote an extension with Go and WebAssembly but was unable to use this repository as my web server because it only serves .js files (and not .wasm), and seemingly wants every extension to only be a one-file script when I need a folder to store all the code. Will it be possible to accommodate my extension?

Here is my git repo for more context: https://sr.ht/~reesericci/turbowarp.sh/

**Comment by GarboMuffin** [comment]
You can plop the extra files into website/whatever/\*.wasm and it'll be served at /whatever/\*.wasm

**Comment by GarboMuffin** [comment]
It looks like your wasm files are 6MB so putting them in the repository probably wouldn't make sense. Some external blob host seems reasonable. Anything in this list is exempted from Scratch.fetch() permission prompts: https://github.com/TurboWarp/scratch-gui/blob/299aa08a38670ebc424e37e04c69e30088f6e023/src/containers/tw-security-manager.jsx#L51-L83 (can be expanded on request)

if you want it to be merged here, so we can set up a place to host those files for you

We haven't seen extensions with such huge non-JS dependency trees before so we don't really have a great solution

**Comment by reesericci** [comment]
I was thinking of publishing it as an NPM package - would that make sense?

**Comment by GarboMuffin** [comment]
yes

**Comment by reesericci** [comment]
I uploaded it to NPM (https://npmjs.com/@turbowarp.sh/client) - but in the process of that I was able to embed the WASM inside my javascript file so the extension actually bundles to one, 8mb file. Should I submit the complete extension or should I write a loader that fetches the 8mb file from NPM.

**Comment by reesericci** [comment]
Submitted a PR for my extension: https://github.com/TurboWarp/extensions/pull/1396
