### ISSUE TITLE
Support for list input type

### ISSUE THREAD

**Issue by zacoons** [TurboWarp/extensions#1420]
It'd be great if users could put a list as an input to my block.
e.g.
![image](https://github.com/TurboWarp/extensions/assets/73414084/a4a4ca36-5cc7-4868-bbd3-e18ba1438a82)

My current workaround is to just have them put in the name of the list and then my code looks for that list in the vm variables.
But that's kinda janky and it would cause issues when they rename their list.

**Comment by LilyMakesThings** [comment]
you tried using a dynamic menu?..

**Comment by zacoons** [comment]
@LilyMakesThings u mean have a menu from which they can pick the name of a list?
not a bad idea, I'll see how it goes.

**Comment by zacoons** [comment]
Nope, doesn't update the value when the list is renamed. But it's better than what I had before so I'll keep it for now. I still think it'd be a good idea to add support for list inputs to blocks.

**Comment by LilyMakesThings** [comment]
> Nope, doesn't update the value when the list is renamed. But it's better than what I had before so I'll keep it for now. I still think it'd be a good idea to add support for list inputs to blocks.
> 
> ![image](https://private-user-images.githubusercontent.com/73414084/324293329-a1f474d2-b06d-458e-bcac-e71310f1485c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDM5MzAsIm5iZiI6MTcxMzc0MzYzMCwicGF0aCI6Ii83MzQxNDA4NC8zMjQyOTMzMjktYTFmNDc0ZDItYjA2ZC00NThlLWJjYWMtZTcxMzEwZjE0ODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIzNTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWE3OTk0ODIwMDAyYTIwZGViNThiMTc3YmIzMzE2ODMyNDg0MzlkYTZjOGJhN2Q3MTc5NzMwOTY5MTU0MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LvfdUj4N1LmrFVxS_SV-076D4qPP2Wi01ljweb5SZP8)

Use variable IDs instead then, and have the menu display the name as the text and the id as the value
