### ISSUE TITLE
Make Numerical Encoding length prefixed encoding, or make it an option

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/extensions#1449]
As it stands, numerical encoding is really, really inefficient. It (from what I can tell) converts each character into a 5 character long string using it's Unicode. What we can instead do is get whatever the characters Unicode is (e.g. 65 for A) and then "preface it" with how many characters that Unicode is. For example, A would be 256, 2 being how many characters it needs to read after is. 
If we encode the string "Hello World" using both methods, the current extension yields
000072000101000108000108000111000032000087000111000114000108000100 - 66 characters, horrible for limited cloud variables. If we instead use "Length Prefixed Encoding" we get
27231013108310831112322873111311431083100 - 41 characters. 
I also think that the extension should be a reporter, as having to run a block and then run the reporter just seems weird (I suppose with longer strings it could be a performance thing, but I believe we can leave both functionalities in just in case.)
We could probably just leave the old blocks in and make them invisible for compatibility reasons, or make it a new extension entirely. I might make it myself, but I well and truly know almost nothing about coding turbowarp extensions

**Comment by snowboyz0825** [comment]
Nothing beats coding your own thing, but I feel like we should at least work to make the thing we have integrated the best it can be

**Comment by GarboMuffin** [comment]
we could do a lot better than either if we did a proper base 10 encoding

**Comment by GarboMuffin** [comment]
proper base 10 encoding mean something that uses actual binary options in the same way that base 64 and base 85 encodings do

**Comment by GarboMuffin** [comment]
In V2 "Hello World" encodes to 331736654417855136778673441731 - 30 characters
