### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by veggiecan0419** [TurboWarp/extensions#1454]
Hi everyone! I have a question.

Why is it
```javascript
Scratch.ArgumentType.COLOR
```
But
```javascript
extensions: ["colours_motion"]
```
?

Why is **color** spelled the American way in one place, but not the other?

**Comment by CubesterYT** [comment]
This is because the extension parameter is based off internal Scratch code, such as blockly from 2012, which is spelt that way, and the .COLOR is based off recent scratch and turbowarp.

**Comment by CubesterYT** [comment]
We can't change the internal one without severely breaking compatibility.
