### ISSUE TITLE
Extension that can send messages using chat app webhooks.

### ISSUE THREAD

**Issue by ZekusV** [TurboWarp/extensions#148]
It would be cool to have an extension that allows sending messages to a chat app server using a chat app webhook url.

**Comment by DNin01** [comment]
Sounds like it could cause security issues. Is there any situation where you would find this useful?

**Comment by CST1229** [comment]
> Sounds like it could be a security problem having projects being able to send whatever messages they want as the user. Is there any situation where you would find this useful?

"send whatever messages they want as the user"
No, this is for interacting with Discord _webhooks_ (Discord's bot feature made to specifically send messages by posting to a URL), not the user. This is probably already possible with the fetch extension.

**Comment by matej2005** [comment]
Hi, I don't normally program in js, but somehow I managed to get it working. 
[https://github.com/matej2005/TurboWarp-extension/blob/main/discord.js](https://github.com/matej2005/TurboWarp-extension/blob/main/discord.js)

"This is probably already possible with the fetch extension." I tried but it didn't work.

**Comment by GarboMuffin** [comment]
TurboHook
