### ISSUE TITLE
Files extension issue with images and audio

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#149]
I wanted to make a extension that goes with the files extension.
Basically you can use the open file reporter block to open a image or sound, and have it be applied to the current editing target. Issue is that the block doesn't return image data, it returns a string.
A check for the extension of the file, and the type of data it sends would be nice, since having 2 extensions with different ways of opening files would be really messy.
If that's not something that you wanna do or can't do because of some kind of limitations, a way for me to add that in my extension is appreciated.

**Comment by TheAwesome98-Real** [comment]
for sounds, maybe you could convert it into a data url and play it with the sounds extension?

**Comment by TheShovel** [comment]
> for sounds, maybe you could convert it into a data url and play it with the sounds extension?

I have some blocks that can load sounds and sprites from a link in my utils extension, but I tried to make a data url to do what I just said, and it just doesn't work. It's not a valid link, even tho the code executes with no errors or warnings.

**Comment by GarboMuffin** [comment]
This is now possible as https://github.com/TurboWarp/extensions/pull/173 was merged
