### ISSUE TITLE
Steamworks API extension?

### ISSUE THREAD

**Issue by Sammyueru** [TurboWarp/extensions#150]
I bet you could add it using something like [https://github.com/Spacetech/greenworks](https://github.com/Spacetech/greenworks) as the original greenworks**.js** is no longer in development
However the one I linked is

**Comment by GarboMuffin** [comment]
Unfortunately even these extensions are not capable of running native code necessary to integrate with the Steam API

**Comment by Sammyueru** [comment]
> Unfortunately even these extensions are not capable of running native code necessary to integrate with the Steam API

Dang well maybe someday
