### ISSUE TITLE
pen v7 breaks my project

### ISSUE THREAD

**Issue by penta-quark-neutro** [TurboWarp/extensions#1508]
project designed with pen v6.
The v7 update causes the triangles to not be drawn.
with v6
![Captura de pantalla (472)](https://github.com/TurboWarp/extensions/assets/134885702/01b7001d-4bdc-4da9-9f16-e46a51b718d4)
with v7
![Captura de pantalla (473)](https://github.com/TurboWarp/extensions/assets/134885702/598424c0-dd02-48a5-bedf-5254c9b77b81)

**Comment by GarboMuffin** [comment]
@David-Orangemoon

**Comment by David-Orangemoon** [comment]
Ill look into it

**Comment by David-Orangemoon** [comment]
@penta-quark-neutro could you send the project file?

**Comment by penta-quark-neutro** [comment]
here the project. 
Several others rely on this to function so it is important.
[Motor 3D.zip](https://github.com/user-attachments/files/15542511/Motor.3D.zip)
