### ISSUE TITLE
Simple3d does not work properly in Turbowarp Packager

### ISSUE THREAD

**Issue by WDGASTERtim** [TurboWarp/extensions#1513]
all textures become black when the project is packaged
![test 06 06 2024 12_32_49](https://github.com/TurboWarp/extensions/assets/108210308/0d5cbfc1-f89c-41c4-8f31-7606db1b952e)

**Comment by Xeltalliv** [comment]
Did it show this popup? The latest version of Simple3D (1.0.3) should normally do that when the project is incorrectly packaged.
Packaged to html:
![image](https://github.com/TurboWarp/extensions/assets/90340988/133d8d78-e95b-4f98-9287-e5886963b671)
Packaged to Electron:
![image](https://github.com/TurboWarp/extensions/assets/90340988/d0b714ee-b499-4f2c-9bee-79ee0a168f1b)

**Comment by WDGASTERtim** [comment]
it really worked, thanks, but there is no notification when this function is enabled

**Comment by Xeltalliv** [comment]
Were you using an offline editor? It currently has a bit outdated version of Simple3D from before that notification was added.

**Comment by GarboMuffin** [comment]
based on the window having the turbowarp icon, it looks like it's a packager preview window, so that would explain it
