### ISSUE TITLE
Smalruby TurboWarp extension.

### ISSUE THREAD

**Issue by HangingWithCMM** [TurboWarp/extensions#1538]
Is there any extensions that adds the Ruby tab from Smalruby? (See image below).

![image](https://github.com/TurboWarp/extensions/assets/87918339/19e2df8e-2dfa-46ad-a4cd-8acfbf0b086b)

I would just use Smalruby but I enjoy all the other features that TurboWarp has. Is there an extension or addon that adds this to the editor? If not could one be made?

**Comment by SharkPool-SP** [comment]
in other words, text based coding

**Comment by unknown07724** [comment]
wouldn't that involve editing the GUI and possibly the VM?
is that not even allowed

**Comment by LilyMakesThings** [comment]
> wouldn't that involve editing the GUI and possibly the VM? is that not even allowed

it's discouraged, hard-coding features solely for extensions is a slippery slope.

**Comment by AshimeeAlt** [comment]
~~Like all of my prs are for that~~ lol
________________________________
