### ISSUE TITLE
Translate all the extensions

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#1539]
- [x] 0832/rxFS2
 - [x] 0832/rxFS
 - [x] Alestore/nfcwarp
 - [x] ar
 - [x] battery
 - [x] bitwise
 - [x] box2d
 - [x] Clay/htmlEncode
 - [x] clipboard
 - [x] clouddata-ping
 - [x] cloudlink
 - [x] codeGIO/ExtraUtilities
 - [x] cs2627883/numericalencoding
 - [x] CST1229/images
 - [x] CST1229/zip
 - [x] CubesterYT/KeySimulation
 - [x] CubesterYT/TurboHook
 - [x] CubesterYT/WindowControls
 - [x] cursor
 - [x] DNin/wake-lock
 - [x] DT/cameracontrols
 - [x] encoding
 - [x] fetch
 - [x] files
 - [x] gamejolt
 - [x] gamepad
 - [x] godslayerakp/http
 - [x] godslayerakp/ws
 - [x] iframe
 - [x] itchio
 - [x] JeremyGamer13/tween
 - [x] lab/text
 - [x] Lily/AllMenus
 - [x] Lily/Assets
 - [x] Lily/Cast
 - [x] Lily/ClonesPlus
 - [x] Lily/CommentBlocks
 - [x] Lily/HackedBlocks
 - [x] Lily/ListTools
 - [x] Lily/lmsutils
 - [x] Lily/LooksPlus
 - [x] Lily/McUtils
 - [x] Lily/MoreEvents
 - [x] Lily/MoreTimers
 - [x] Lily/Skins
 - [x] Lily/SoundExpanded
 - [x] Lily/TempVariables2
 - [x] Lily/TempVariables
 - [x] Lily/Video
 - [x] local-storage
 - [x] Longboost/color_channels
 - [x] mbw/xml
 - [x] mdwalters/notifications
 - [x] Medericoder/textcase
 - [x] navigator
 - [x] NexusKitten/controlcontrols
 - [x] NexusKitten/moremotion
 - [x] NexusKitten/sgrab
 - [x] NOname-awa/cn-number
 - [x] NOname-awa/global-coordinate
 - [x] NOname-awa/graphics2d
 - [x] NOname-awa/math-and-string
 - [x] NOname-awa/more-comparisons
 - [x] NOname-awa/regular-expression
 - [x] NOname-awa/sort-unique-words
 - [x] numerical-encoding-2
 - [x] obviousAlexC/newgroundsIO
 - [x] obviousAlexC/penPlus
 - [x] obviousAlexC/SensingPlus
 - [ ] penplus
 - [x] pointerlock
 - [x] PwLDev/vibration
 - [x] qxsck/data-analysis
 - [x] qxsck/var-and-list
 - [x] rixxyx
 - [x] runtime-options
 - [x] SharkPool/Font-Manager
 - [x] shreder95ua/resolution
 - [x] -SIPC-/consoles
 - [x] -SIPC-/recording
 - [x] -SIPC-/time
 - [x] Skyhigh173/bigint
 - [x] Skyhigh173/json
 - [x] sound
 - [x] stretch
 - [x] text
 - [x] TheShovel/CanvasEffects
 - [x] TheShovel/ColorPicker
 - [x] TheShovel/CustomStyles
 - [x] TheShovel/LZ-String
 - [x] TheShovel/profanityAPI
 - [x] TheShovel/profanity
 - [x] TheShovel/ShovelUtils
 - [x] true-fantom/base
 - [x] true-fantom/couplers
 - [x] true-fantom/math
 - [x] true-fantom/network
 - [x] true-fantom/network-m
 - [x] true-fantom/regexp
 - [x] turboloader/audiostream
 - [x] utilities
 - [x] veggiecan/browserfullscreen
 - [x] veggiecan/LongmanDictionary
 - [x] veggiecan/mobilekeyboard
 - [x] vercte/dictionaries
 - [x] WP-Studio01/text2speech
 - [x] Xeltalliv/clippingblending
 - [ ] Xeltalliv/simple3D
 - [x] XeroName/Deltatime
 - [x] XmerOriginals/closecontrol
 - [x] ZXMushroom63/searchApi

update list with

```bash
#!/bin/bash
set -euo pipefail
for i in $(find . -type f | grep '\.js$' | grep -v "docs-example" | sort); do
    slug="$(echo $i | sed 's/.\///' | sed 's/\.js//')"
    if [[ "$(cat $i)" =~ "Scratch.translate" ]]; then
        echo " - [x] $slug"
    else
        echo " - [ ] $slug"
    fi
done
```

**Comment by AshimeeAlt** [comment]
Oh, my, god.

**Comment by GarboMuffin** [comment]
We're not going to bother translating the old pen+, so the only thing left is Simple 3D

**Comment by GarboMuffin** [comment]
@Xeltalliv do you think it is viable for Simple 3D to have translations, noting that the people who will be writing those translations will not have a background in 3D graphics?
