### ISSUE TITLE
Shouldn't `package.json` include BSD-3-Clause as one of the licenses?

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/extensions#1551]
[`Xeltalliv/simple3D`](https://github.com/TurboWarp/extensions/blob/master/extensions/Xeltalliv/simple3D.js) contains code under a BSD-3-Clause license, so technically it should be noted in the package metadata. I assume this was just forgotten.

@GarboMuffin

**Comment by GarboMuffin** [comment]
yes it should

**Comment by Xeltalliv** [comment]
It might've been forgotten even earlier considering Pen Plus V5 also uses that library.

https://github.com/TurboWarp/extensions/blob/60d8a9b13f9b99e72d2e8b6780bfde699ecd2a7b/extensions/penplus.js#L69-L104
