### ISSUE TITLE
How do can i make the http extention get images from sites like deviantart, image boards, ect??

### ISSUE THREAD

**Issue by GaypataponALT** [TurboWarp/extensions#1566]
i remember trying to see if getting the art from url works with the http extention but the status says it failed, is there a way around this?

**Comment by yuri-kiss** [comment]
No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output.

**Comment by GaypataponALT** [comment]
> No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output. (also maybe run this url through a corsproxy so that cors does not get in the way).

oh, i wished they can fetch binary data :(

**Comment by GaypataponALT** [comment]
> No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output. (also maybe run this url through a corsproxy so that cors does not get in the way).

btw how can i run the url through a corsproxy? is there a corsprocy extention?

**Comment by yuri-kiss** [comment]
> > No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output. (also maybe run this url through a corsproxy so that cors does not get in the way).
> 
> btw how can i run the url through a corsproxy? is there a corsprocy extention?



> > No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output. (also maybe run this url through a corsproxy so that cors does not get in the way).
> 
> btw how can i run the url through a corsproxy? is there a corsprocy extention?

**Comment by CST1229** [comment]
> try using the images extension and converting its output.

Creator of the Images extension here, please use Skins instead.

**Comment by yuri-kiss** [comment]
> > try using the images extension and converting its output.
> 
> Creator of the Images extension here, please use Skins instead.

I was expecting this

**Comment by GaypataponALT** [comment]
> > > No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output. (also maybe run this url through a corsproxy so that cors does not get in the way).
> > 
> > 
> > btw how can i run the url through a corsproxy? is there a corsprocy extention?
> 
> > > No sadly you cant fetch binary data with any extensions currently, try using the images extension and converting its output. (also maybe run this url through a corsproxy so that cors does not get in the way).
> > 
> > 
> > btw how can i run the url through a corsproxy? is there a corsprocy extention?
> 
> use the encoding extension and a join block, an example corsproxy is `corsproxy.io` or `allorigins.win`.
> 
> ![image](https://private-user-images.githubusercontent.com/135030944/342457935-6f80246e-a984-4660-a558-e104b66a7f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMjMyMjgsIm5iZiI6MTcxOTMyMjkyOCwicGF0aCI6Ii8xMzUwMzA5NDQvMzQyNDU3OTM1LTZmODAyNDZlLWE5ODQtNDY2MC1hNTU4LWUxMDRiNjZhN2Y5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxMzQyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDg2MWFkNjkyYTI4ZTY0ZjEwNDhjNWI2NjAyYTBjMmJiMTZiNmIxM2Q0OGEyNWFhZWUzYThjMDc0NGQ0OGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yFoeP57mkJmAV9BDfKt8JF7rHfYFeqUZrX4F0mVWOpA)
> 
> ^ That is your url that you should use in this case (i used `https://example.com/my-image.png` as the image example and `corsproxy.io` as the corsproxy)

but if the link is https://tbib.org/index.php?page=post&s=view&id=0000000 or https://www.furaffinity.net/view/00000000/ for example then how do i actually fetch art from there? the zero's is just an example

**Comment by GaypataponALT** [comment]
i'm making a game where you press a button and it will show you random art that it fetches

**Comment by AshimeeAlt** [comment]
😭 i clicked the link
________________________________

**Comment by SharkPool-SP** [comment]
is this resolved?
