### ISSUE TITLE
Request for comment: Putting extensions in folders by author

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#157]
## The problem

The current organization of `extensions` is unsustainable considering the end goal is for everyone to submit every extension

When someone submits an extension called eg. `encoding` or `networking`, because we don't have folders, I set the bar very high for merging

## Proposed solution

Extensions are instead added in folders, eg. `fetch.js` would now be `GarboMuffin/fetch.js` and accessible at https://extensions.turbowarp.org/GarboMuffin/fetch.js

This has benefits:

 - People can make their own extensions that use common names like "fetch" without polluting everything
 - Extension authors are given credit more visibly

Problems:

 - The URLs are ugly, but we generally want people to use the "Copy URL" or "Open Extension" buttons anyways so it's not that bad.

Eventually we may decide that some of these extensions are worthy of being accessible without a username. Using the build server and script, we can either:

 - Tell the build script to copy GarboMuffin/fetch.js to just fetch.js
 - Rename the extension to just fetch.js and tell the build server to copy it to GarboMuffin/fetch.js

Either way projects that use the old URL won't break.

The code for making folders work has already been written and merged.

Thoughts?

**Comment by showierdata9978** [comment]
this is great!

**Comment by infernostars** [comment]
> *snip*
> Eventually we may decide that some of these extensions are worthy of being accessible without a username. Using the build server and script, we can either:
> 
> * Tell the build script to copy GarboMuffin/fetch.js to just fetch.js
> * Rename the extension to just fetch.js and tell the build server to copy it to GarboMuffin/fetch.js
> 
> *snip*

I think that the former would probably be better since they are still all in their own directories for development. Issue arises if the extension has multiple developers though - how is that treated? especially if they both already have their own extensions

**Comment by softedco** [comment]
> 
> I think that the former would probably be better since they are still all in their own directories for development. Issue arises if the extension has multiple developers though - how is that treated? especially if they both already have their own extensions
> 

I believe contributions on someone else's extensions would be treated like regular pull requests but with an additional reviewer being the extension's author
