### ISSUE TITLE
I keep getting a error

### ISSUE THREAD

**Issue by unknown07724** [TurboWarp/extensions#1580]
the error is Uncaught ReferenceError: unlockAchievement is not defined

the code snippet is

unlockAchievement(); {
       console.log('unlocked Achievement');
      }

**Comment by CubesterYT** [comment]
In the name of the function, remove the ; from the ()

**Comment by veggiecan0419** [comment]
> In the name of the function, remove the ; from the ()

```javascript
unlockAchievement() { 
  // Remove the  ; ↑
  console.log('unlocked Achievement');
}
```
@unknown07724 
Like this.

**Comment by unknown07724** [comment]
the extension is for people to use the google play games SDK, next Goal is Crazygame's SDK

**Comment by unknown07724** [comment]
It didn't work

**Comment by unknown07724** [comment]
wait I forgor To add the semicolon
