### ISSUE TITLE
My packaged games takes a long time to load

### ISSUE THREAD

**Issue by GaypataponALT** [TurboWarp/extensions#1582]
I don't like how my uploaded game on newgrounds takes so much time to load the game, is there a way to fix this?

**Comment by GarboMuffin** [comment]
if you post the link we can possibly help you figure out why

**Comment by GaypataponALT** [comment]
> Quote reply
> Reference

https://www.newgrounds.com/portal/view/937495
https://www.newgrounds.com/portal/view/937499

**Comment by GarboMuffin** [comment]
For one you should probably not disable the progress bar so people know that it's loading...

Your project is 5MB and the packager itself takes about 1MB, so you have to wait for it to load around 6MB. That's not that unreasonable. Most of your 5MB is taken up by the two background songs which are 2MB each

**Comment by snowboyz0825** [comment]
If it's any help you may be able to remove some assets and then have them "Load in the background" by hosting the assets on some sort of github repository and then loading them "In the background" each time the project starts. If want you could even have them download once and then have them stored in the local storage extension, though according to the documentation the local storage is limited to 5 MB, so be careful. Just keep in mind that you're not removing loading time, just reallocating it to once the game is actually run
