### ISSUE TITLE
Javascript functions extension

### ISSUE THREAD

**Issue by unknown07724** [TurboWarp/extensions#1585]
Extension for Javascript functions like alert,confirm and prompt

**Comment by CubesterYT** [comment]
Refer to PR #570

**Comment by GarboMuffin** [comment]
if you want something that is just alert/confirm/prompt then we can talk about that...

**Comment by unknown07724** [comment]
Not eval and other dangerous stuff

**Comment by unknown07724** [comment]
more like alert,confirm and other safe javascript functions like fetch but fetch already has it's own extension

**Comment by unknown07724** [comment]
if eval gets added make it very sandboxed like you need to enable it and stuff can just not work if it is a computer virus waiting to happen

**Comment by unknown07724** [comment]
I now have v0.1 done (alert only)

**Comment by CodeFoxy-Github** [comment]
Lily's Toolbox have it 
![image](https://github.com/TurboWarp/extensions/assets/96522178/4ebcbade-dcdc-4eb1-b68e-a12ad568545b)

**Comment by unknown07724** [comment]
Imma add some more blocks
