### ISSUE TITLE
When creating two clones with separate text in the animated text extension in quick succession they will show the same text

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/extensions#1597]
I could not think of a better way to describe it than just the title. Here's an example project
[https://raw.githubusercontent.com/snowboyz0825/snowscodestuff/main/SB3s/Bug%20example%202.sb3](https://raw.githubusercontent.com/snowboyz0825/snowscodestuff/main/SB3s/Bug%20example%202.sb3)

**Comment by SharkPool-SP** [comment]
Your clone ID variable isnt "sprite only". When the clones create and initialize, the variable has already changed and its too late

**Comment by snowboyz0825** [comment]
> Your clone ID variable isnt "sprite only". When the clones create and initialize, the variable has already changed and its too late

...I'll see myself out lmao
