### ISSUE TITLE
Add a JavaScript extenstion

### ISSUE THREAD

**Issue by Cbr2011** [TurboWarp/extensions#160]
What I mean is add a extension that let you use JavaScript coding in a block like if I type `warn('This is a warning!')` in the block it will run the JavaScript code.

**Comment by GarboMuffin** [comment]
We will not add blocks that allow projects to run arbitrary untrusted JS on our websites

You are free to send custom extensions that run whatever custom JS you need, just not ones that let projects specify arbitrary JS

**Comment by Cbr2011** [comment]
oh ok, Thanks for letting me know

**Comment by Mickmick2012** [comment]
this is why rixxyx is not running unsandboxed
