### ISSUE TITLE
JSON Extension: Numbers return as strings without the compiler

### ISSUE THREAD

**Issue by sf97ahgf** [TurboWarp/extensions#1600]
I've noticed this when making my Discord bot in Turbowarp, and I felt it would be funny if I disabled the compiler. After I did that, I noticed that the bot wouldn't even connect to Discord. I compared the two authorization strings and I noticed that the "op" variable was a string instead of a number when running without the compiler.

**Comment by GarboMuffin** [comment]
if you're making an extension, you're supposed to do any and all casting yourself

if you're using an extension by someone else, tell them to fix their casting

**Comment by GarboMuffin** [comment]
ok, if you're manually constructing json objects then that could matter since it can't assume what data types you want. the compiler does some tricks to optimize projects and this is one of the side effects

**Comment by GarboMuffin** [comment]
You can do things like adding zero or joining a variable with an empty string to cast manually. Or use the cast extension. If data types matter you should be doing this as again you don't really know what data types your blocks will be stored as
