### ISSUE TITLE
The zip extension cannot read the image file

### ISSUE THREAD

**Issue by fg133266** [TurboWarp/extensions#1601]
![Snipaste_2024-07-11_23-06-06](https://github.com/TurboWarp/extensions/assets/143243975/912ea8c9-8d64-481e-bd50-3a06820a147f)
I tried to read the zip the way it did in the image, and although it returned the URI, none of the image processing extensions could read properly

**Comment by David-Orangemoon** [comment]
Huh thats odd could you send the Uri or image. I see youve tried with pen+ which supports non svg images.

**Comment by fg133266** [comment]
> 呵呵，这很奇怪，你能发送 Uri 或图像吗？我看到你已经尝试过支持非 svg 图像的 pen+。除非你不想使用pen+服装系统，这是可以理解的。

[lol.zip](https://github.com/user-attachments/files/16179923/lol.zip)

**Comment by snowboyz0825** [comment]
I have actually made something using custom reporters than can turn a png to an svg, if you'd like I could send it to you but I'd have to modify it a bit

**Comment by fg133266** [comment]
> I have actually made something using custom reporters than can turn a png to an svg, if you'd like I could send it to you but I'd have to modify it a bit

Yes, you just need to make sure that the image can be read correctly in the zip ;-;

**Comment by snowboyz0825** [comment]
> > I have actually made something using custom reporters than can turn a png to an svg, if you'd like I could send it to you but I'd have to modify it a bit
> 
> Yes, you just need to make sure that the image can be read correctly in the zip ;-;

[https://raw.githubusercontent.com/snowboyz0825/snowscodestuff/main/Scratch%20Code/PNG%20to%20SVG.sprite3](https://raw.githubusercontent.com/snowboyz0825/snowscodestuff/main/Scratch%20Code/PNG%20to%20SVG.sprite3)

**Comment by fg133266** [comment]
> > > 我实际上已经使用自定义记者制作了一些东西，可以将 png 转换为 svg，如果您愿意，我可以将其发送给您，但我必须对其进行一些修改
> > 
> > 
> > 是的，您只需要确保在zip ;-;中可以正确读取图像即可
> 
> https://raw.githubusercontent.com/snowboyz0825/snowscodestuff/main/Scratch%20Code/PNG%20to%20SVG.sprite3 请记住，这会创建一个临时服装，可以在运行后删除，但由于添加服装会自动将当前服装设置为添加的服装，所以很糟糕

![Snipaste_2024-07-13_03-35-00](https://github.com/user-attachments/assets/72f6cbc8-acfd-4b53-9f08-03ccdf13933e)
It does convert PNG to SVG, but it doesn't seem to be of much use for PNG in zip

**Comment by snowboyz0825** [comment]
I think zip was working fine but whatever it was you used to convert it was messing up or possibly skins, unless I'm misunderstanding your issue

**Comment by fg133266** [comment]
> 我认为zip工作正常，但无论您用来转换什么，它都会搞砸或可能是皮肤，除非我误解了您的问题

The zip extension doesn't seem to parse the image file in the archive properly and convert it to a URI, or am I using it in the wrong way? ;-;

**Comment by fg133266** [comment]
https://github.com/user-attachments/assets/a7a363da-beaf-4180-b618-c0e0e26e467e

**Comment by CST1229** [comment]
it might be taking the type of the data URL into account (so you'll have to replace `data:application/octet-stream` with `data:image/png`)?

**Comment by fg133266** [comment]
> 它可能考虑了数据 URL 的类型（因此您必须替换为 ）？`data:application/octet-stream``data:image/png`

It works! Thank you
