### ISSUE TITLE
Add "New Key named (  )" block to json extension

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/extensions#1602]
Before anyone says anything, I know you can do this using the set key block. My only issue is that this is rather counter-intuitive, and it took me a while to find it. A new block that adds a key to json would be helpful and more organized, as well as more intuitive.

**Comment by CubesterYT** [comment]
But that's just bloat

**Comment by snowboyz0825** [comment]
> But that's just bloat

I feel like we should try to make it as intuitive as possible, it is based on scratch which as based towards kids at it's core. Maybe we could rename the block, but I can't think if what we could rename it. It's essentially making the front end look somewhat nicer despite making the backend a little bit more bloated.

**Comment by SharkPool-SP** [comment]
> > But that's just bloat
> 
> 
> 
> I feel like we should try to make it as intuitive as possible, it is based on scratch which is based towards kids at it's core. Maybe we could rename the block, but I can't think if what we could rename it. It's essentially making the front end look somewhat nicer despite making the backend a little bit more bloated.

Scratch is based towards kids. Turbowarp (extension side) is supposed to be based for more advanced/older users.

**Comment by snowboyz0825** [comment]
I feel like it'd be good to add, but there's no use in arguing about it or point in having an open issue with it, so I'm just gonna take the L and close with this

**Comment by GarboMuffin** [comment]
What would the new key block do? Just set it to null?

**Comment by snowboyz0825** [comment]
> What would the new key block do? Just set it to null?

Admittedly I do not really know how json works too well, but I was thinking something like this
![newkey](https://github.com/user-attachments/assets/b88dd281-0afe-4940-9e0b-d45a81039fdf)
but after thinking through it better it really is just bloat

**Comment by GarboMuffin** [comment]
That is literally the same as the set block
