### ISSUE TITLE
JSON Extension not recognizing key

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/extensions#1614]
In this JSON,
[cat.json](https://github.com/user-attachments/files/16239590/cat.json)
if you take the value of the "Catagories" key (ignore the typo I'm to lazy to change my code) and then take all the keys of "All Events" within that it will not show "flower_dance". I'm 99% sure that my JSON is formatted correctly because I [used this site to type it](https://jsoneditoronline.org/#left=local.facafi&right=local.hosuqa) and if I go to the tree view it shows it properly. There's definitely the chance that I'm missing something but it really does seem like a bug. I also double checked it with a few other sites but those seemed like those were basically just text editors

**Comment by veggiecan0419** [comment]
@snowboyz0825 No, its not a problem with the extension, nor the formatting. You just forgot to add `flower_dance` to `All events`. You only added it to `Events`, not `All Events`. See below:
It is included in `Events`:
![Events](https://github.com/user-attachments/assets/67c27d32-33eb-4520-9ddd-9f5cf4d50e1a)
But not `All Events`:
![All Events](https://github.com/user-attachments/assets/a71df19a-c528-4132-96d9-631c5404aab4)

**Comment by snowboyz0825** [comment]
That's embarrassing, sorry for the borderline spam
