### ISSUE TITLE
[Question] Which browser do I need to use for AR?

### ISSUE THREAD

**Issue by Cbr2011** [TurboWarp/extensions#162]
Every time I try to load AR I get the `invalid AR session id` error. Which browser do I need to use?

**Comment by GarboMuffin** [comment]
@Xeltalliv

**Comment by Xeltalliv** [comment]
> Every time I try to load AR I get the `invalid AR session id` error. 

I'm not familiar with this error message and couldn't find any information on it either. Can you share a screenshot of it?

> Which browser do I need to use?

It worked on Google Chrome and Samsung Internet and didn't work on Firefox (AR haven't been added there yet, so makes sense). (tested on Android 10)

Which browser on which OS have you tried it on?

**Comment by Cbr2011** [comment]
Opera GX

**Comment by Cbr2011** [comment]
Opera GX

**Comment by Cbr2011** [comment]
Opera GX.

**Comment by Cbr2011** [comment]
The error says Project attempted to start AR even though it's not available. The reason: WebXR exist in the browser you are using, but 'immersive-ar' session type is not supported

**Comment by Xeltalliv** [comment]
> Opera GX. Windows.

In general AR only works on mobile devices (phones, tablets) since it requires at least camera, gyroscope and accelerometer.
Currently in-browser AR only works on Android devices which support [Google's ARCore](https://play.google.com/store/apps/details?id=com.google.ar.core).

**Comment by Cbr2011** [comment]
so how am I gonna enter AR mode if I can't edit on turbowarp on phone?

**Comment by Xeltalliv** [comment]
That is still an unresolved issue. Currently the solution is to develop on the PC and copy project to the phone to test it.

There is also ar emulator extension currently in development, which simulates AR without actual AR by using fullscreen and WASD controls. It has the same extension id and blocks, so TurboWarp treats both of them like the same extension and it's easy to swap between them.

**Comment by Cbr2011** [comment]
ar emulator extension? That makes things easier. Is it in beta or a closed beta [meaning visitors can't access it, only the team can]

**Comment by Xeltalliv** [comment]
currently only I have access to it

**Comment by Cbr2011** [comment]
oh it's a closed beta. Well that solves my problem. Right now as I said the emulator is in closed beta meaning you have to wait a month or week to get it.

**Comment by Johny-adri2** [comment]
so where is the extension?

**Comment by GarboMuffin** [comment]
https://extensions.turbowarp.org/

**Comment by LilyMakesThings** [comment]
> > 
> 
> I mean is AR emulator extension in developing yet?

It already exists, https://extensions.turbowarp.org/

**Comment by CST1229** [comment]
> > I mean is AR emulator extension in developing yet?
> 
> It already exists, [extensions.turbowarp.org](https://extensions.turbowarp.org/)

> AR **emulator**

As in, probably the extension Xeltalliv mentioned in this comment, which I'm pretty sure is not public yet:
> There is also ar emulator extension currently in development, which simulates AR without actual AR by using fullscreen and WASD controls. It has the same extension id and blocks, so TurboWarp treats both of them like the same extension and it's easy to swap between them.

**Comment by Xeltalliv** [comment]
> I mean is AR emulator extension in developing yet?

It's currently in the same state as it was when I wrote that comment. I got distracted making other (also currently not published) extensions and forgot about it.
