### ISSUE TITLE
How to use the stretch extension to perform a left-hand stretch

### ISSUE THREAD

**Issue by fg133266** [TurboWarp/extensions#1632]
I'm trying to use the diagram to make the character stretch to the left instead of centering, but no matter what I'm filling in the divisor, he doesn't seem to get it right, and I suspect I'm stupid ;-;

**Comment by fg133266** [comment]
![Snipaste_2024-07-29_09-37-03](https://github.com/user-attachments/assets/273b8d05-e2b5-44ea-b7ef-ba209927031c)

**Comment by GarboMuffin** [comment]
The easiest way could be modifying your costume and use the fact that the image does not need to be centered at the crosshair

![image](https://github.com/user-attachments/assets/bba3f1cb-fbf3-4dae-9824-31e8e193930c)

Or you move the sprite at the same time as the stretch, which works too
