### ISSUE TITLE
registery extension

### ISSUE THREAD

**Issue by unknown07724** [TurboWarp/extensions#1652]
it will have `add key (type) (value)`
and a few other blocks
not sure if electron can support stuff like this

**Comment by Thebloxers998** [comment]
What's a **registety** extension

**Comment by CST1229** [comment]
> What's a **registety** extension

they might be referring to the Windows Registry, but that isn't cross-platform at all

**Comment by unknown07724** [comment]
yes that is what I am referring too, it isn't cross platform but it doesn't have a storage limit

**Comment by Thebloxers998** [comment]
> yes that is what I am referring too, it isn't cross platform but it doesn't have a storage limit

Ok?
