### ISSUE TITLE
Positron: a extension with lots of stuff

### ISSUE THREAD

**Issue by unknown07724** [TurboWarp/extensions#1663]
mostly browsers, some DOM access and a hint of positron settings

**Comment by unknown07724** [comment]
![positron_banner](https://github.com/user-attachments/assets/9dc300a0-61f2-40cc-b8f7-44176ee71c42)
banner for the extension

**Comment by unknown07724** [comment]
some parts used AI to create them because I believe it would probably take hours, and it works


the code:
`

const Icon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAG8klEQVR4Xu1dXVIbORCWxjjkbeMyseEp5gQJJ1jvCQInCJwg3CBwAuAE8Z4g5gTrnGDhBDFPgIPL5i0bw2hbg531mplRSyONJFuqSqUK67e//lOrpaEkFKsUoFZHD4OTAIBlJggABADUKHA9GrXWHsgb3vphjVxt1Wp9tZ7stnJWAgaD0TtCHt8ySluMsTYh9BWQCv6GKheEsDGltMcYGUck+tpo1OBv7hVnABiNRq8mk8f3jNA2EK0N1qmlmVxjwliPcFCq0bkrEmMdgMHg7kPMyC4QZlczwfO7Y6wbUdKtVivntVptXOrYc4NZAYBz+8+H+CNw+iHMhasWm4UTvwNScWZDKkoFgBvOaBJ/YgQ43j7hn4EOxOjE1ei4TCBKAWCO449ssrrE2KfrAEQZqsk4ALd3d7vskZ4YMKoS9FSqOqYRO2hubHSVWiMbGQMg4fpJfALqZh85F0ersd56tbJnShqMAMB9+JjFXzzk+iwmGDMa7W29rvV0c4l2AK4Hd/uU0M+6J+pCf5SSo+br+rHOuWgF4GYwPIHJcddyaQv3lJqN+oGuBWoD4HYw/Oy/vseRVScIWgBYJeLPQXSx2ajv4CDLrlUYgBUlfkJRHZJQCIDr2+ERGKZPRbnA5/ZFQVAGYJm9HVmGgJjW8VazrrTLVwIg8fNJ/BdM1HYgTZZWxurDPuEPlX2CNAB8h/vPJCE+9nDE2KId63gM8aNt2R2zNACrbHSFgMMZw2ZzY09Yb66CFADX30dtyhLuDyWDAhDA25MJ4EkBcHM7/LZE8R0zTMRIf/1FtINVRWgAbLuc4GlcAcU6KKpR1oZ41O+ougYqyXhFKACmhvebTa+HEfZ1q7HRxtDLNrPwOcIR5zbmZA0FgBML8g0AQv7catT3RQwjBMAF7k84yjMAsFIgBMAF7vcVAJj3GQTscsPzQgAgxj+yqftnIuyjBMDchZuzXACSA/WYfhHpsTJ+9xQArjoPwHnI9N5yAbi5vetCxtr7MggsGsNXACAd8hx2x5lZf5kATI0vVz9OFG8BELikmQC4Fm72GoAcNZQDwLADP35wgv09dUP/cyCy9wSZALgW9/FZAsAS9zeb9e00Zk4FgCfR0knMQw/OFK8BACrCJZGdtEsi6QA4mFzlOwBZ7mg6AA4etnsPQMa5cSoALvn/nu+Ef6nwLAZKB2Aw/Btaaj3zTeL5lPVVjQrE93kiFCrtkbvQMA7/p1YYbUG6TXIDU2NJTeTKAgCyDPUWmUMKvSPL92YqAAkM9IzeAYAUfAIA8kyrtYVVAEztAYIKSj+mfKaCTKWeBAAAgJTsuQBAiTYAB4ChMESQAKQK4gwBx5DBDTWQdh/cUKSvZNULChJAiAsA8Ld13iIZBlmN9fj7PcjKz6rFjF3lHW7PN+CeXERi5dTE6ftEbdW5ZrS7BBX0LLwTgnGaqZzVnVQwzpQIFlnrSoWjXTuQ58B5D0DGwXw4kiwilhJtpY4keb+ghvoGYuISU/5/VZ8lgJ+FwC3KVtriQ1qKMkvgG8KuNjNVPSRm4emoXDMvPzSkJiqTFd8Qrq/ClbH0lxlDci6ejmo1VZNz+WghPV2N5vOtCqWn844gMsrf1fyt+FSK9eCpF3QP4Yfc5xyEN2Rc2RX7CADmDEQIwPSeQN+2FHgIwD0Y35bowrYQgOmmzPq7QL4BkOf7zytjFAAuSIF3AOi8qJ0Y4+/DQ4iI8VcR7RTIsacR7qkCQ/F89Loxun/WGUoCZpXBIzJwUINelxcV8+I+aQuQAsBUzpAXlEVOUvblLCkApvuCU/j/I3I+K1UNa3iljfAiFYMqSuWrS3A72yK3c7GltAQkbulT8ha3B9Z3yK6IWNaBi2h+SgDwTl2KE4kWafp3Ubwnb3xlABJJcPAyn2liL/Yv43IW9oLSOgB7sLJGWcXoarEBi51cD9y6VV+GFOggPp9nIRU0v9BVkgRdxNcKwKrYhKI634gKmu906h11ltBFvQdv5xCbn4pVg9pU0PyA030C//yT5gRf7LK017sEP3/fxAdBjQAwW/6S2IUz2OEeye5wsSxgFIDELjy9N81dVa+kIbnZH0X7Kk/SY4mv3QjnDTw9TzjywDbcA/FPVT/IIEP8UgHgg/GTtR8/40PIOeVvPrgWR0oI//JFdGpK3aSBY1wFpQ3qGBBWCD+jixUAFt3WOKa7MJFy36eDjDVagY+yGf5Yp0glWQdgNsFEKiaP8L4mbcPZc1t3avzTczmkB1c9ei+rlW6ZaiYPBGcAWJwk30uQySOAAW/3EPYOHpBtSXhSl/Bgah++T3+RvFFUrfQwT8mLuNXE784CIFpsAtAD4aAQskb6rhJYtA5vARAtzJffAwCWkQoABAAsU8Dy8P8CrMPnjjbGjlkAAAAASUVORK5CYII='

class unknownpositron {
  getInfo() {
    return {
      id: 'unknownpositron',
      name: 'Positron',
      color1: '#683a67', 
      color2: '#18223c',
      color3: '#001220',
      menuIconURI: Icon,
      blockIconURI: Icon,
      blocks: [
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'settings'
        },
        {
          opcode: 'version',
          blockType: Scratch.BlockType.REPORTER,
          text: 'version of positron'
        },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'JS'
        },
        {
            opcode: 'prompt',
            blockType: Scratch.BlockType.REPORTER,
            text: 'prompt [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
          {
            opcode: 'alert',
            blockType: Scratch.BlockType.COMMAND,
            text: 'alert [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'DOM access'
        },
        {
            opcode: 'source_code',
            blockType: Scratch.BlockType.REPORTER,
            text: 'html source code'
          },
        {
            opcode: 'titlechange',
            blockType: Scratch.BlockType.COMMAND,
            text: 'change title to [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
          {
            opcode: 'changeelement',
            blockType: Scratch.BlockType.COMMAND,
            text: 'replace innerhtml of element [ID] with [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
              ID: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'browsers and navigator'
        },
        {
          opcode: 'product',
          blockType: Scratch.BlockType.REPORTER,
          text: 'browser engine'
        },
        {
          opcode: 'useragent',
          blockType: Scratch.BlockType.REPORTER,
          text: 'user agent'
        },
        {
            opcode: 'langauge',
            blockType: Scratch.BlockType.REPORTER,
            text: 'language'
        },
        {
            opcode: 'vendor',
            blockType: Scratch.BlockType.REPORTER,
            text: 'browser vendor'
        },
        {
            opcode: 'BrowserVersion',
            blockType: Scratch.BlockType.REPORTER,
            text: 'browser version'
        },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'dangerous (dont use unless you know what your doing)'
        },
        {
            opcode: 'docwrite',
            blockType: Scratch.BlockType.COMMAND,
            text: 'change html to [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
      ]
    };
  }
  

  titlechange(args) {
    document.title = args.str;
  }
  prompt(args) {
   return prompt(args.str);
  }
  alert(args) {
    alert(args.str);
   }
  source_code(args) {
   return document.documentElement.outerHTML
  }
  docwrite(args) {
    document.write(args.str)
  }
  changeelement(args) {
    document.getElementById(args.ID).innerHTML = args.str;
  }

  version() {
    return 1.0;
  }
  langauge() {
    return navigator.language;
  }
  useragent() {
    return navigator.userAgent;
  }
  product() {
    const userAgent = navigator.userAgent;

        if (/Gecko\//.test(userAgent) && !/like Gecko/.test(userAgent)) {
            return "Gecko";
        } else if (/AppleWebKit/.test(userAgent) && !/Edge\/|Edg\//.test(userAgent)) {
            return "WebKit";
        } else if (/Edg\//.test(userAgent) || /Edge\//.test(userAgent)) {
            return "Chromium";
        } else if (/Chrome\/|CriOS\//.test(userAgent)) {
            return "Chromium";
        } else if (/Trident\//.test(userAgent)) {
            return "Trident";
        } else if (/Presto\//.test(userAgent)) {
            return "Presto";
        } else if (/MSIE/.test(userAgent) || /rv:11/.test(userAgent)) {
            return "Trident (IE)";
        } else {
            return "Unknown";
        }
    }
    BrowserVersion() {
        const userAgent = navigator.userAgent;
        let browserVersion = "Unknown";

        if (/Firefox\/([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/Firefox\/([0-9.]+)/)[1];
        } else if (/Chrome\/([0-9.]+)/.test(userAgent) && !/Edg\//.test(userAgent)) {
            browserVersion = userAgent.match(/Chrome\/([0-9.]+)/)[1];
        } else if (/Edg\/([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/Edg\/([0-9.]+)/)[1];
        } else if (/Safari\/([0-9.]+)/.test(userAgent) && !/Chrome/.test(userAgent)) {
            browserVersion = userAgent.match(/Version\/([0-9.]+)/)[1];  // Safari version is found after "Version/"
        } else if (/Trident\/7.0;.*rv:([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/rv:([0-9.]+)/)[1];  // IE 11+ with Trident engine
        } else if (/MSIE ([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/MSIE ([0-9.]+)/)[1];  // IE 10 and below
        } else if (/OPR\/([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/OPR\/([0-9.]+)/)[1];  // Opera
        }

        return browserVersion;
    }
    vendor() {
        const userAgent = navigator.userAgent;

        if (/Chrome\/|CriOS\//.test(userAgent) && !/Edg\//.test(userAgent)) {
            return "Google Inc.";
        } else if (/Safari\/|AppleWebKit\//.test(userAgent) && !/Chrome/.test(userAgent)) {
            return "Apple Computer, Inc.";
        } else if (/Edg\//.test(userAgent)) {
            return "Microsoft Corporation";
        } else if (/OPR\//.test(userAgent)) {
            return "Opera Software ASA";
        } else if (/Firefox\//.test(userAgent)) {
            return "Mozilla Foundation";
        } else if (/Trident\//.test(userAgent) || /MSIE/.test(userAgent)) {
            return "Microsoft Corporation";
        } else {
            return "Unknown";
        }
    }
}

  


Scratch.extensions.register(new unknownpositron());`

**Comment by unknown07724** [comment]
I did testing and lots of it on one browser though

**Comment by unknown07724** [comment]
> I did testing and lots of it on one browser though

like maybe 5 times so it is probably not a lot

**Comment by unknown07724** [comment]
I feel like this extension has a theme, documents(like the turbowarp webpage)

**Comment by unknown07724** [comment]
also yes you can shoot yourself in the foot via the dangerous blocks, I should really make you have to enable them

**Comment by unknown07724** [comment]
// Name: Positron
// ID: unknownpositron
// Description: access the DOM.
// By: Unknown07724 <https://scratch.mit.edu/users/Unknown07724/>
// License: MPL-2.0

const Icon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAG8klEQVR4Xu1dXVIbORCWxjjkbeMyseEp5gQJJ1jvCQInCJwg3CBwAuAE8Z4g5gTrnGDhBDFPgIPL5i0bw2hbg531mplRSyONJFuqSqUK67e//lOrpaEkFKsUoFZHD4OTAIBlJggABADUKHA9GrXWHsgb3vphjVxt1Wp9tZ7stnJWAgaD0TtCHt8ySluMsTYh9BWQCv6GKheEsDGltMcYGUck+tpo1OBv7hVnABiNRq8mk8f3jNA2EK0N1qmlmVxjwliPcFCq0bkrEmMdgMHg7kPMyC4QZlczwfO7Y6wbUdKtVivntVptXOrYc4NZAYBz+8+H+CNw+iHMhasWm4UTvwNScWZDKkoFgBvOaBJ/YgQ43j7hn4EOxOjE1ei4TCBKAWCO449ssrrE2KfrAEQZqsk4ALd3d7vskZ4YMKoS9FSqOqYRO2hubHSVWiMbGQMg4fpJfALqZh85F0ersd56tbJnShqMAMB9+JjFXzzk+iwmGDMa7W29rvV0c4l2AK4Hd/uU0M+6J+pCf5SSo+br+rHOuWgF4GYwPIHJcddyaQv3lJqN+oGuBWoD4HYw/Oy/vseRVScIWgBYJeLPQXSx2ajv4CDLrlUYgBUlfkJRHZJQCIDr2+ERGKZPRbnA5/ZFQVAGYJm9HVmGgJjW8VazrrTLVwIg8fNJ/BdM1HYgTZZWxurDPuEPlX2CNAB8h/vPJCE+9nDE2KId63gM8aNt2R2zNACrbHSFgMMZw2ZzY09Yb66CFADX30dtyhLuDyWDAhDA25MJ4EkBcHM7/LZE8R0zTMRIf/1FtINVRWgAbLuc4GlcAcU6KKpR1oZ41O+ougYqyXhFKACmhvebTa+HEfZ1q7HRxtDLNrPwOcIR5zbmZA0FgBML8g0AQv7catT3RQwjBMAF7k84yjMAsFIgBMAF7vcVAJj3GQTscsPzQgAgxj+yqftnIuyjBMDchZuzXACSA/WYfhHpsTJ+9xQArjoPwHnI9N5yAbi5vetCxtr7MggsGsNXACAd8hx2x5lZf5kATI0vVz9OFG8BELikmQC4Fm72GoAcNZQDwLADP35wgv09dUP/cyCy9wSZALgW9/FZAsAS9zeb9e00Zk4FgCfR0knMQw/OFK8BACrCJZGdtEsi6QA4mFzlOwBZ7mg6AA4etnsPQMa5cSoALvn/nu+Ef6nwLAZKB2Aw/Btaaj3zTeL5lPVVjQrE93kiFCrtkbvQMA7/p1YYbUG6TXIDU2NJTeTKAgCyDPUWmUMKvSPL92YqAAkM9IzeAYAUfAIA8kyrtYVVAEztAYIKSj+mfKaCTKWeBAAAgJTsuQBAiTYAB4ChMESQAKQK4gwBx5DBDTWQdh/cUKSvZNULChJAiAsA8Ld13iIZBlmN9fj7PcjKz6rFjF3lHW7PN+CeXERi5dTE6ftEbdW5ZrS7BBX0LLwTgnGaqZzVnVQwzpQIFlnrSoWjXTuQ58B5D0DGwXw4kiwilhJtpY4keb+ghvoGYuISU/5/VZ8lgJ+FwC3KVtriQ1qKMkvgG8KuNjNVPSRm4emoXDMvPzSkJiqTFd8Qrq/ClbH0lxlDci6ejmo1VZNz+WghPV2N5vOtCqWn844gMsrf1fyt+FSK9eCpF3QP4Yfc5xyEN2Rc2RX7CADmDEQIwPSeQN+2FHgIwD0Y35bowrYQgOmmzPq7QL4BkOf7zytjFAAuSIF3AOi8qJ0Y4+/DQ4iI8VcR7RTIsacR7qkCQ/F89Loxun/WGUoCZpXBIzJwUINelxcV8+I+aQuQAsBUzpAXlEVOUvblLCkApvuCU/j/I3I+K1UNa3iljfAiFYMqSuWrS3A72yK3c7GltAQkbulT8ha3B9Z3yK6IWNaBi2h+SgDwTl2KE4kWafp3Ubwnb3xlABJJcPAyn2liL/Yv43IW9oLSOgB7sLJGWcXoarEBi51cD9y6VV+GFOggPp9nIRU0v9BVkgRdxNcKwKrYhKI634gKmu906h11ltBFvQdv5xCbn4pVg9pU0PyA030C//yT5gRf7LK017sEP3/fxAdBjQAwW/6S2IUz2OEeye5wsSxgFIDELjy9N81dVa+kIbnZH0X7Kk/SY4mv3QjnDTw9TzjywDbcA/FPVT/IIEP8UgHgg/GTtR8/40PIOeVvPrgWR0oI//JFdGpK3aSBY1wFpQ3qGBBWCD+jixUAFt3WOKa7MJFy36eDjDVagY+yGf5Yp0glWQdgNsFEKiaP8L4mbcPZc1t3avzTczmkB1c9ei+rlW6ZaiYPBGcAWJwk30uQySOAAW/3EPYOHpBtSXhSl/Bgah++T3+RvFFUrfQwT8mLuNXE784CIFpsAtAD4aAQskb6rhJYtA5vARAtzJffAwCWkQoABAAsU8Dy8P8CrMPnjjbGjlkAAAAASUVORK5CYII='

class unknownpositron {
  getInfo() {
    return {
      id: 'unknownpositron',
      name: 'Positron',
      color1: '#683a67', 
      color2: '#18223c',
      color3: '#001220',
      menuIconURI: Icon,
      blockIconURI: Icon,
      blocks: [
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'settings'
        },
        {
          opcode: 'version',
          blockType: Scratch.BlockType.REPORTER,
          text: 'version of positron'
        },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'JS'
        },
        {
            opcode: 'prompt',
            blockType: Scratch.BlockType.REPORTER,
            text: 'prompt [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
          {
            opcode: 'alert',
            blockType: Scratch.BlockType.COMMAND,
            text: 'alert [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'DOM access'
        },
        {
            opcode: 'source_code',
            blockType: Scratch.BlockType.REPORTER,
            text: 'html source code'
          },
        {
            opcode: 'titlechange',
            blockType: Scratch.BlockType.COMMAND,
            text: 'change title to [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
          {
            opcode: 'changeelement',
            blockType: Scratch.BlockType.COMMAND,
            text: 'replace innerhtml of element [ID] with [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
              ID: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
        {
            blockType: Scratch.BlockType.LABEL,
            text: 'browsers and navigator'
        },
        {
          opcode: 'product',
          blockType: Scratch.BlockType.REPORTER,
          text: 'browser engine'
        },
        {
          opcode: 'useragent',
          blockType: Scratch.BlockType.REPORTER,
          text: 'user agent'
        },
        {
            opcode: 'langauge',
            blockType: Scratch.BlockType.REPORTER,
            text: 'language'
        },
        {
            opcode: 'vendor',
            blockType: Scratch.BlockType.REPORTER,
            text: 'browser vendor'
        },
        {
            opcode: 'BrowserVersion',
            blockType: Scratch.BlockType.REPORTER,
            text: 'browser version'
        },
        {
            blockType: Scratch.BlockType.LABEL,
            text: "dangerous (don't use unless you know what your doing)"
        },
        {
            opcode: 'docwrite',
            blockType: Scratch.BlockType.COMMAND,
            text: 'change html to [str]',
            arguments: {
              str: {
                type: Scratch.ArgumentType.STRING
              },
            }
          },
      ]
    };
  }
  

  titlechange(args) {
    document.title = args.str;
  }
  prompt(args) {
   return prompt(args.str);
  }
  alert(args) {
    alert(args.str);
   }
  source_code(args) {
   return document.documentElement.outerHTML
  }
  docwrite(args) {
    document.write(args.str)
  }
  changeelement(args) {
    document.getElementById(args.ID).innerHTML = args.str;
  }

  version() {
    return 1.0;
  }
  langauge() {
    return navigator.language;
  }
  useragent() {
    return navigator.userAgent;
  }
  product() {
    const userAgent = navigator.userAgent;

        if (/Gecko\//.test(userAgent) && !/like Gecko/.test(userAgent)) {
            return "Gecko";
        } else if (/AppleWebKit/.test(userAgent) && !/Edge\/|Edg\//.test(userAgent)) {
            return "WebKit";
        } else if (/Edg\//.test(userAgent) || /Edge\//.test(userAgent)) {
            return "Chromium";
        } else if (/Chrome\/|CriOS\//.test(userAgent)) {
            return "Chromium";
        } else if (/Trident\//.test(userAgent)) {
            return "Trident";
        } else if (/Presto\//.test(userAgent)) {
            return "Presto";
        } else if (/MSIE/.test(userAgent) || /rv:11/.test(userAgent)) {
            return "Trident (IE)";
        } else {
            return "Unknown";
        }
    }
    BrowserVersion() {
        const userAgent = navigator.userAgent;
        let browserVersion = "Unknown";

        if (/Firefox\/([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/Firefox\/([0-9.]+)/)[1];
        } else if (/Chrome\/([0-9.]+)/.test(userAgent) && !/Edg\//.test(userAgent)) {
            browserVersion = userAgent.match(/Chrome\/([0-9.]+)/)[1];
        } else if (/Edg\/([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/Edg\/([0-9.]+)/)[1];
        } else if (/Safari\/([0-9.]+)/.test(userAgent) && !/Chrome/.test(userAgent)) {
            browserVersion = userAgent.match(/Version\/([0-9.]+)/)[1];  // Safari version is found after "Version/"
        } else if (/Trident\/7.0;.*rv:([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/rv:([0-9.]+)/)[1];  // IE 11+ with Trident engine
        } else if (/MSIE ([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/MSIE ([0-9.]+)/)[1];  // IE 10 and below
        } else if (/OPR\/([0-9.]+)/.test(userAgent)) {
            browserVersion = userAgent.match(/OPR\/([0-9.]+)/)[1];  // Opera
        }

        return browserVersion;
    }
    vendor() {
        const userAgent = navigator.userAgent;

        if (/Chrome\/|CriOS\//.test(userAgent) && !/Edg\//.test(userAgent)) {
            return "Google Inc.";
        } else if (/Safari\/|AppleWebKit\//.test(userAgent) && !/Chrome/.test(userAgent)) {
            return "Apple Computer, Inc.";
        } else if (/Edg\//.test(userAgent)) {
            return "Microsoft Corporation";
        } else if (/OPR\//.test(userAgent)) {
            return "Opera Software ASA";
        } else if (/Firefox\//.test(userAgent)) {
            return "Mozilla Foundation";
        } else if (/Trident\//.test(userAgent) || /MSIE/.test(userAgent)) {
            return "Microsoft Corporation";
        } else {
            return "Unknown";
        }
    }
}

  


Scratch.extensions.register(new unknownpositron());

**Comment by unknown07724** [comment]
bro this is getting annoying

**Comment by Drago-Cuven** [comment]
> bro this is getting annoying

patience is key

**Comment by unknown07724** [comment]
I've waited a month and nothing happened

**Comment by Brackets-Coder** [comment]
> I've waited a month and nothing happened

Patience is key. I've waited for my MIDI extension to be reviewed since July and nothing's happened. This repository is notorious for really long wait times.

**Comment by David-Orangemoon** [comment]
> I've waited a month and nothing happened

You might have better luck making a pull request instead of an issue.

**Comment by unknown07724** [comment]
> > I've waited a month and nothing happened
> 
> You might have better luck making a pull request instead of an issue.

no

**Comment by GarboMuffin** [comment]
I don't know when pull requests will be reviewed but if you don't make one then your code will not even be in the queue when that happens

**Comment by RedMan13** [comment]
> some parts used AI to create them because I believe it would probably take hours, and it works

this is a miss-conception about ai
because ai is so bad at writing code it takes 3x as long or more to use ai because you have to debug and fox code you dont even understand and even sometimes require that you completely rewrite the ai's code from scratch

~~also its a shit excuse tomuse ai, you should __**NEVER IN ALL OF TIME**__ use ai to replace you~~

**Comment by unknown07724** [comment]
it will take 5x as long to build myself and 10x to debug it as I am shit at coding

**Comment by RedMan13** [comment]
thats not mathmatically possible
