### ISSUE TITLE
Would the extension gallery work with an animated gif?

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/extensions#1689]
If not I can just work with .svg like everyone else, but a gif would allow animations and be cool for obvious reasons

**Comment by CubesterYT** [comment]
The gallery can use gifs, but it's been exempted from the support banner image types array for whatever reason, so it wouldn't work.

**Comment by Xeltalliv** [comment]
> but a gif would allow animations and be cool for obvious reasons

technically svg images also support animation and animated svgs already work here

**Comment by DNin01** [comment]
Animated GIFs would be inconsistent among the static images, plus too distracting.

**Comment by GarboMuffin** [comment]
you'd better have a *really* good reason...
