### ISSUE TITLE
Request for comment: Proposed APIs to give users control over what websites projects can access

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#169]
# The problem

A project with eg. the fetch extension can talk to any server it wants to without confirmation. This can have privacy and security implications that are not obvious. Should the fetch extension really allow port scanning and IP logging by default? Probably not.

# Proposed solution

Part 1 is to replace every use of `fetch`, `WebSocket`, `Image`, etc. with eg. `Scratch.fetch`, `Scratch.WebSocket`, `Scratch.Image`, etc. Initially these could just be copies of their window.* counterparts. We can probably configure ESLint to error if using the old APIs.

Part 2 is to make those APIs check if the origin they are trying to load is allowed or not. We might present a prompt like this:

> This project is trying to access the website "trampoline.turbowarp.org". 
> Allowing this may share your IP address and approximate location with the website.
> [Deny]
> [Allow once]
> [Always allow trampoline.turbowarp.org]
> [Temporarily allow all websites]

Sort of like our own "google.com wants to know your location [Deny] [Allow]" prompt

Until the user chooses, fetch()'s promise will remain unresolved, WebSocket won't emit open, etc. If user denies, an error will be returned in the same way that the native fetch() would return a rejected promise, WebSocket would emit an error event, etc.

Having an option to allow forever is safe here as this is just fetching; we're not executing arbitrary JS

Depending on how fetch() handles HTTP redirects, we can likely add a builtin exception for trusted static site hosts like *.github.io where there is no privacy concern

We can do a similar thing for window opening and page redirecting:

> This project is trying to open a new tab to "github.com"
> [... the same options ...]

For these we can also add checks to ensure URLs like `javascript:alert(1)` do not run code in just one spot instead of everywhere. We can also probably detect popup blockers.

Extensions running in a sandbox will be exempted from these checks (there is nothing we can do to force them to use Scratch.fetch instead of window.fetch). The prompt to confirm loading them will be updated to mention this.

The packager will always be exempted from these checks.

## Concerns

 - These confirmations will be very annoying very quickly
 - Notification fatigue

**Comment by showierdata9978** [comment]
The only problem i have with this is that users could break projects, because they have required data on another server...

This also breaks CL. As its entire use is connecting to a Cloudlink websocket server

**Comment by GarboMuffin** [comment]
It doesn't "break" cloud link; the user just has to consent to connecting. Perhaps one of the default servers can be added to the list of always allowed websites.

A user denying permission will behave the same as when someone doesn't have an internet connection. Projects should already be designed with that condition in mind.

**Comment by DNin01** [comment]
I don't think the notifications will be a problem, especially if the projects are designed with needing to ask for permission in mind.
