### ISSUE TITLE
TurboWarp blocks "(...) mouse button down?" does not work when Pen+ is rendering triangles

### ISSUE THREAD

**Issue by TheAwesome98-Real** [TurboWarp/extensions#170]
if i'm using Pen+ to render triangles, the mouse button down block (including the one from scratch) always reports false, but if i create a project using sprites, the mouse button down block works as expected.

**Comment by AlexSchoolOH** [comment]
I will try and fix that in version 6 thanks for reporting this bug.

**Comment by GarboMuffin** [comment]
is this fixed in v6?

**Comment by AlexSchoolOH** [comment]
I'm pretty sure since I have gotten mouse interaction working in games. I
think originally it was a thing with their thing of turbowarp since I could
never replicate it.

**Comment by AlexSchoolOH** [comment]
@GarboMuffin It seems to be fixed
