### ISSUE TITLE
Pen+ V7 blocks using the "Pen+ Costume" feature return undefined

### ISSUE THREAD

**Issue by namelessisbackbutnottodobadthingsiswear** [TurboWarp/extensions#1712]
![chrome_DAv5pqvqZM](https://github.com/user-attachments/assets/e01ba183-b019-4a34-8b5f-edd76becc608)
The blocks above return undefined by default (since there's no costumes loaded)

**Comment by David-Orangemoon** [comment]
I'll get to fixing that in the pen-group repo.

**Comment by SharkPool-SP** [comment]
> I'll get to fixing that in the pen-group repo.

did you fix it yet

**Comment by David-Orangemoon** [comment]
Its in the pen group repo. I've been working on other things recently.

**Comment by SharkPool-SP** [comment]
> Its in the pen group repo. I've been working on other things recently.

can you make a quick pr to fix it
