### ISSUE TITLE
String to image/sound extension

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#172]
A extension that creates sprites and sounds in sprites with string input, and also gives string data for a selected costume or sound. This could be used to save and edit user made images in cloud variables, and make it possible to import image/sound files using the Files extension.

**Comment by TheShovel** [comment]
Related to #149

**Comment by GarboMuffin** [comment]
This is now possible as https://github.com/TurboWarp/extensions/pull/173 was merged
