### ISSUE TITLE
Simple3D: How to Import bigger texture?

### ISSUE THREAD

**Issue by YogaindoCR** [TurboWarp/extensions#1731]
How can I import or apply a bigger texture resolution like 2048 x 2048, without changing the game base resolution?
![image](https://github.com/user-attachments/assets/a5524d4e-be1e-40f4-a040-f81fafcd8b14)

**Comment by Xeltalliv** [comment]
You can use:
Asset Manager extension + Files extension (if you only need few files)
Asset Manager extension + running a local web server (if you need to automate a lot of importing)

**Comment by YogaindoCR** [comment]
Got it!
