### ISSUE TITLE
Navigator: How do I make it detect if I'm using Oprea or Opera GX?

### ISSUE THREAD

**Issue by Cbr2011** [TurboWarp/extensions#174]
![image](https://user-images.githubusercontent.com/82298138/215297288-4a41df6b-3c13-4b5c-9e00-cb82ef238d38.png)
So it says I'm using chrome however I'm using Opera GX. Is there a way for it to detect I'm using Oprea?

**Comment by TheShovel** [comment]
OperaGX and Opera are chromium based browsers. Even if Opera is added to the list of browsers in the block, it is more reliable and easy to understand if it is left as Chrome, as they both are almost the same from a programming perspective.

**Comment by Cbr2011** [comment]
ok that makes sense despite the fact the google web store detects I'm using opera the same with other websites.
