### ISSUE TITLE
Is it actually possible to compile scratch projects to c+ or c++??

### ISSUE THREAD

**Issue by GaypataponALT** [TurboWarp/extensions#1755]
If it was possible then can you also compile it for game consoles after compiling it to c+ and c++?

**Comment by CST1229** [comment]
probably very very impractical (and would require the whole runtime and every block and extension to be fully rewritten)

**Comment by GaypataponALT** [comment]
because I have seen people being able to compile it to c++ and someone is even making a compiler for the scratch player

**Comment by ScratchFakemon** [comment]
Theoretically, yes. All Scratch code is just JavaScript, which TurboWarp already compiles to. If you could get this JavaScript and convert it to C or C++, you'd have a game!

**Comment by GarboMuffin** [comment]
Above comment is a gross simplification of reality and will not get you on a good path to success

**Comment by GarboMuffin** [comment]
If you want to go down further than JavaScript then you'll want something that goes directly all the way down. Which TurboWarp doesn't provide and isn't in scope right now

**Comment by ScratchFakemon** [comment]
Yeah. _Very_ theoretical :P
