### ISSUE TITLE
I need ideas for extensions

### ISSUE THREAD

**Issue by unknown07724** [TurboWarp/extensions#1756]
my only ideas are my websites API but that isn't even remotely useful for anyone or WebGL

**Comment by Thebloxers998** [comment]
Have you heard of SupaBase, if not, you should make a supabase API extension, it uses a url and apiKey, I also made one too 

Also I just came here because you needed ideas

**Comment by unknown07724** [comment]
I got an idea, vectors (math not svgs)

**Comment by Thebloxers998** [comment]
> I got an idea, vectors (math not svgs)

Ooo you could do that but how

**Comment by kkk2z** [comment]
Create and delete folders, create and delete files, just like in OS.
Download and upload.
I want such an extension.

**Comment by Thebloxers998** [comment]
> Create and delete folders, create and delete files, just like in OS. Download and upload. I want such an extension.

Doesn't that already exi- ohhhhh i get it

**Comment by SharkPool-SP** [comment]
> Create and delete folders, create and delete files, just like in OS. Download and upload. I want such an extension.

you cant download a folder. Only ZIPs. Which an extension exists for that. However for deleting files and opening folders, you can use my Files Expanded extension, found at:
https://sharkpools-extensions.vercel.app/

**Comment by ScratchFakemon** [comment]
> Create and delete folders, create and delete files, just like in OS. Download and upload. I want such an extension.

rxFS. That's just rxFS.

**Comment by GarboMuffin** [comment]
Above comment is incorrect. rxFS is not useful for what they're asking for.

**Comment by ScratchFakemon** [comment]
> Above comment is incorrect. rxFS is not useful for what they're asking for.

1: That was QUICK
2: Oh. I thought they meant a simulated file system. ¯\_(ツ)_/¯

**Comment by Thebloxers998** [comment]
> > Above comment is incorrect. rxFS is not useful for what they're asking for.
> 
> 1: That was QUICK 2: Oh. I thought they meant a simulated file system. ¯_(ツ)_/¯

I Guess?

**Comment by GaypataponALT** [comment]
Maybe you could do my idea https://github.com/TurboWarp/extensions/issues/1766#issue-2702536736

**Comment by Thebloxers998** [comment]
> Maybe you could do my idea [#1766 (comment)](https://github.com/TurboWarp/extensions/issues/1766#issue-2702536736)

That's very hard

**Comment by GaypataponALT** [comment]
true but it would been cool to see


> > Maybe you could do my idea [#1766 (comment)](https://github.com/TurboWarp/extensions/issues/1766#issue-2702536736)
> 
> That's very hard

true but atleast it would been cool to see

**Comment by Thebloxers998** [comment]
> true but it would been cool to see
> 
> > > Maybe you could do my idea [#1766 (comment)](https://github.com/TurboWarp/extensions/issues/1766#issue-2702536736)
> > 
> > 
> > That's very hard
> 
> true but atleast it would been cool to see

Yea, I do agree with the idea
