### ISSUE TITLE
[BUG] Pen extension doesn't work with Camera Controls extension

### ISSUE THREAD

**Issue by alboxer2000** [TurboWarp/extensions#1774]
When I move the camera and draw with the pen extension (the car in video is drawing), it doesn't go out of the normal camera spot.
[video.webm](https://github.com/user-attachments/assets/97ac3225-cbb7-4af1-9ced-2f8aa3ede054)

**Comment by David-Orangemoon** [comment]
This is because the pen layer is an image that is drawn onto. Thus the image has a fixed size

**Comment by SharkPool-SP** [comment]
this is intentional behaviour, as [David-Orangemoon](https://github.com/David-Orangemoon) said
