### ISSUE TITLE
How do i fix prettier bug

### ISSUE THREAD

**Issue by Thebloxers998** [TurboWarp/extensions#1783]
Im working on this extension: https://github.com/TurboWarp/extensions/pull/1757
The bug says: [warn] Code style issues found in the above file. Run Prettier with --write to fix.

**Comment by CST1229** [comment]
this is not really a bug, but to solve it, i think:
1. if you haven't already, install git (or github desktop) and node.js, clone the repository, install node.js and run `npm ci` in the repository. the same things you'd do to run the `npm run dev` dev server except without actually running that command
2. instead, do `npm run format`
3. commit the changes that command makes

**Comment by Thebloxers998** [comment]
Im on a mobile

**Comment by Thebloxers998** [comment]
> Im on a mobile

What do I do

**Comment by CST1229** [comment]
> > Im on a mobile
> 
> What do I do

nothing, basically just wait for someone to do it for you (or wait to see if #1770 would be merged or not)

**Comment by Thebloxers998** [comment]
> > > Im on a mobile
> > 
> > 
> > What do I do
> 
> nothing, basically just wait for someone to do it for you (or wait to see if #1770 would be merged or not)

Oh Ok  👌
