### ISSUE TITLE
Force Feedback for Gamepad extension

### ISSUE THREAD

**Issue by Mickmick2012** [TurboWarp/extensions#180]
Gamepads and controllers (PS5 dual sense, steerings wheels) have Force feedback
this is how the block will look like : 

`set force feedback force to ( )`

**Comment by CST1229** [comment]
I think that's what the ![rumble](https://user-images.githubusercontent.com/68464103/216717325-9be52901-20b1-4886-b50f-ebb75c358bf2.png) block does.

**Comment by GarboMuffin** [comment]
I know that some modern controllers have some crazy vibration systems that let you get some very detailed effects (never tried personally), but unfortunately the above block is the best that we can do on the web platform.

**Comment by Mickmick2012** [comment]
> but unfortunately the above block is the best that we can do on the web platform.
English is not my main language
Did you say that it may not be possible on the website ?

**Comment by GarboMuffin** [comment]
The gamepad extension already has a block for causing vibrations/haptic feedback. It is probably more than good enough for what you need to do.

More complex effects that take advantage of the full power of some modern controllers is unfortunately probably not possible, but the simple vibration blocks should still work.

**Comment by Mickmick2012** [comment]
nope (at least with my G29)
it does nothing

**Comment by Mickmick2012** [comment]
Oh and there is 2 motors btw

**Comment by GarboMuffin** [comment]
Whoops, I missed when you mentioned steering wheels. Unfortunately I don't have one of those to test.

Can you copy and paste the output of this website here? https://muffin.ink/gamepad

**Comment by Mickmick2012** [comment]
i am currently coding, i will test when i can

**Comment by Mickmick2012** [comment]
`Gamepad #0 id: G29 Driving Force Racing Wheel (Vendor: 046d Product: c24f) connected: true timestamp: 24194 mapping: 
  buttons: 25
    #0: pressed: false value: 0 pressed: false
    #1: pressed: false value: 0 pressed: false
    #2: pressed: false value: 0 pressed: false
    #3: pressed: false value: 0 pressed: false
    #4: pressed: false value: 0 pressed: false
    #5: pressed: false value: 0 pressed: false
    #6: pressed: false value: 0 pressed: false
    #7: pressed: false value: 0 pressed: false
    #8: pressed: false value: 0 pressed: false
    #9: pressed: false value: 0 pressed: false
    #10: pressed: false value: 0 pressed: false
    #11: pressed: false value: 0 pressed: false
    #12: pressed: false value: 0 pressed: false
    #13: pressed: false value: 0 pressed: false
    #14: pressed: false value: 0 pressed: false
    #15: pressed: false value: 0 pressed: false
    #16: pressed: false value: 0 pressed: false
    #17: pressed: false value: 0 pressed: false
    #18: pressed: false value: 0 pressed: false
    #19: pressed: false value: 0 pressed: false
    #20: pressed: false value: 0 pressed: false
    #21: pressed: false value: 0 pressed: false
    #22: pressed: false value: 0 pressed: false
    #23: pressed: false value: 0 pressed: false
    #24: pressed: false value: 0 pressed: false
  axes: 10
    #0: 0.0030670166015625
    #1: 1
    #2: 1
    #3: 0
    #4: 0
    #5: 1
    #6: 0
    #7: 0
    #8: 0
    #9: 1.2857143878936768
  hapticActuators: unsupported
  vibrationActuator: unsupported`

**Comment by Mickmick2012** [comment]
weirdly it says that there is no vibration

**Comment by Mickmick2012** [comment]
and the wrong numbers of axes are reported

**Comment by GarboMuffin** [comment]
What browser and operating system are you using? Chrome-based browsers are the most likely to work. Unfortunately if the browser doesn't give us access then there's nothing we can do

**Comment by Mickmick2012** [comment]
Brave (Chromium based), Windows 11
