### ISSUE TITLE
See if gamepad vibration can work in Firefox

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#181]
we currently use https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/vibrationActuator which doesn't work in Firefox. we may be able to use https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/hapticActuators as an alternative

**Comment by DNin01** [comment]
I was thinking the same thing.

**Comment by GarboMuffin** [comment]
hapticActuators is an empty list with an Xbox controller in Firefox on Windows 10 and Linux, so this is not usable

It's probably for WebXR controllers
