### ISSUE TITLE
RixxyX: time block mishap

### ISSUE THREAD

**Issue by yuri-kiss** [TurboWarp/extensions#1812]
The `time` reporter only updates the time when it is called which means for it to accurately report any sort of time it would have to be shown, and even then its off sometimes.

<strike>Lemons working on a PR to fix this.</strike>

**Comment by SharkPool-SP** [comment]
Is lemon still working on the pr

**Comment by yuri-kiss** [comment]
> Is lemon still working on the pr

no bro gave up

you should do it /hj

**Comment by SharkPool-SP** [comment]
> > Is lemon still working on the pr
> 
> no bro gave up
> 
> you should do it /hj

i can

**Comment by RixInGithub** [comment]
waht
