### ISSUE TITLE
Cloudlink credit information

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#186]
@MikeDev101 

Do you or any other cloudlink people want to be listed here, and if so, what names & links should be listed? (scratch.mit.edu links okay, other links may not be)

![image](https://user-images.githubusercontent.com/33787854/218248493-2f9bc442-4ada-43d0-82e5-12324818dc42.png)

**Comment by MikeDev101** [comment]
It should just be my alias, MikeDEV, and should link to the CL repository in Github.
