### ISSUE TITLE
An error report: crash of the page

### ISSUE THREAD

**Issue by OeildeLynx31** [TurboWarp/extensions#187]
When I have run the program below with the [numericalencoding.js](https://github.com/TurboWarp/extensions/blob/master/extensions/cs2627883/numericalencoding.js) extension, the page has crashed.

![image](https://user-images.githubusercontent.com/33787854/218277216-021a3f30-52a8-4ea9-a7e4-d4ebf10e1e21.png)

I think its a good idea to add a security to block the extension when it is crashing.

**Comment by GarboMuffin** [comment]
Bad projects can always find ways to make the page freeze regardless of the extension. There is nothing we can do to "block" the extension when it is running slow.
