### ISSUE TITLE
Pen + Issues with transparency

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#197]
Transparent pngs have a white background, and the transparency value doesn't really work.

**Comment by GarboMuffin** [comment]
What extension was this in?

**Comment by TheShovel** [comment]
Pen+

**Comment by GarboMuffin** [comment]
@David-Orangemoon

**Comment by David-Orangemoon** [comment]
It's because there is no background its wierd  because I though webgl would mix it in with the black bg but I am adding a fix for that next update.

**Comment by TheShovel** [comment]
#535 Resolved this.
