### ISSUE TITLE
ShovelUtilis : Update the "Get List" block

### ISSUE THREAD

**Issue by Mickmick2012** [TurboWarp/extensions#198]
I want that this block has a menu that contains "type string" and "type integer" (maybe change integer, i said this because i didn't think oher than this) , for example, if you want to get the content of the list "save" that contains "thing" it returns [thing], but it should be ["thing"]

**Comment by Mickmick2012** [comment]
the solution should be this : return "["" + vm.runtime.getTargetForStage().lookupVariableByNameAndType(TEXT, 'list').value.toString() + ""]"

**Comment by TheShovel** [comment]
Thanks for the suggestion! Gonna make a pull request with this change, but just gonna make it always return a strings.

**Comment by TheShovel** [comment]
Actually, I just realized this is not possible, unless I go through every item of the list and add brackets. Just doing ToString() won't cut it.

**Comment by softedco** [comment]
> Actually, I just realized this is not possible, unless I go through every item of the list and add brackets. Just doing ToString() won't cut it.

`JSON.stringify()` should do, but you would may need to format it

**Comment by TheShovel** [comment]
#203 should get accepted soon

**Comment by Mickmick2012** [comment]
#203 was merged
