### ISSUE TITLE
Fetch Caching

### ISSUE THREAD

**Issue by pokycraftgamer9** [TurboWarp/extensions#199]
Is there anyway to add to fetch a way for it to always re get the information from a site instead of caching the information? I'm trying to implement a Update Notification to the project i'm working on and it keeps fetching the old build number every time even when updated

**Comment by GarboMuffin** [comment]
Your server should set an appropriate Cache-Control header

**Comment by pokycraftgamer9** [comment]
> Your server should set an appropriate Cache-Control header

I dont know how to set that for a TXT file

**Comment by GarboMuffin** [comment]
It's an HTTP header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

If for some reason you don't have that level of control over the server, a common alternative is using "cache busters".

if your URL is https://extensions.turbowarp.org/fetch.js, and you want to ensure it doesn't get cached, you can fetch https://extensions.turbowarp.org/fetch.js?2349238429384234 with some random number there. Usually that bypasses caches.

**Comment by GarboMuffin** [comment]
and note that if you're using a service like GitHub Pages, they have their own server-side cache that fetch() itself can't bypass but the cache busters probably will.
