### ISSUE TITLE
Bool Monitor❓

### ISSUE THREAD

**Issue by True-Fantom** [TurboWarp/extensions#201]
Is this possible for extension blocks?

![24-02-2023 173838](https://user-images.githubusercontent.com/116278271/221205890-95ac025d-829b-41b7-ba18-d1afec0fda95.png)

If you use `disableMonitor: false`, nothing works..

![24-02-2023 174204](https://user-images.githubusercontent.com/116278271/221206743-1ea1cfe6-a169-4318-978f-d86b9436e222.png)

**Comment by GarboMuffin** [comment]
will be soon
