### ISSUE TITLE
General style of extension images🎨

### ISSUE THREAD

**Issue by True-Fantom** [TurboWarp/extensions#204]
![clippingblending](https://user-images.githubusercontent.com/116278271/225658946-532e42b8-d042-4011-a590-cd6d4bb2a741.svg)
![box2d](https://user-images.githubusercontent.com/116278271/225648147-c75fcd36-da21-418c-96a2-de9dfe7280c0.svg)
![cameracontrols](https://user-images.githubusercontent.com/116278271/225648154-ff11a1a6-37a8-41bd-8042-cb8b7913e262.svg)
![couplers](https://user-images.githubusercontent.com/116278271/225648159-fec2387d-2350-4e6f-9766-7817d6578ebf.svg)
![cursor](https://user-images.githubusercontent.com/116278271/225648164-d4c6d5f6-41a8-41d3-b8bc-c25cf78ba925.svg)
![custom](https://user-images.githubusercontent.com/116278271/225648166-ddcdf2c5-5eac-48d4-af1c-086dda036851.svg)
![files](https://user-images.githubusercontent.com/116278271/225648170-f5687ff3-b18d-4bfa-94a0-059c082e878e.svg)
![gallery](https://user-images.githubusercontent.com/116278271/225648175-9ca7abe8-2c54-4219-aead-ba5ae50cfa18.svg)
![gamepad](https://user-images.githubusercontent.com/116278271/225648177-7db5d27a-5d37-4f8b-b287-90a4d33e3a0f.svg)
![math](https://user-images.githubusercontent.com/116278271/225648180-9acadd8a-628d-4464-b0be-014e9e2e7428.svg)
![pointerlock](https://user-images.githubusercontent.com/116278271/225648183-a9c4916e-781d-4973-ae2f-f113450c1be9.svg)
![stretch](https://user-images.githubusercontent.com/116278271/225648186-25041c05-9766-4879-82e8-b12489145f67.svg)
![tw](https://user-images.githubusercontent.com/116278271/225648187-55c7c1a9-e483-4f9e-9c39-a400670b3f86.svg)

**Comment by GarboMuffin** [comment]
these are very intruging

**Comment by GarboMuffin** [comment]
I really like these -- we're going to start using them

Are there any parts of these that you did not make that we should be crediting?

**Comment by True-Fantom** [comment]
@GarboMuffin Should I specify images with license only? Or all the ones I used?

(license image: https://creazilla.com/ru/nodes/46807-vosklitsatelnyy-i-voprositelnyy-znaki-clipart)

**Comment by GarboMuffin** [comment]
Ideally we credit *every* part of the image that wasn't made by you, even public domain things, but we *need* to credit every part that uses a license like CC Attribution 4.0

**Comment by True-Fantom** [comment]
_I think it's worth keeping this open until images are made for all extensions_

@GarboMuffin I edited `all` the images a bit. Here is a list of changes by licenses:

- Gamepad: add Button2-a(Scrath 3)
- Files: replace folder to [new](https://fontawesomeicons.com/svg/icons/folder-open)
- Math: delete formula, add svg version of text(NotoSans-Bold(Scrath 3 Sans Serif))
- Couplers: delete microschemes and numbers, add operators_icon(Scrath Addons)
- Clipping_&_Blending: delete &, add svg version of text(NotoSans-Bold(Scrath 3 Sans Serif))
- Pointerlock: delete all, add [chain](https://svgsilh.com/ru/image/1300304.html) and [cursors](https://commons.wikimedia.org/wiki/File:Mouse-cursor-hand-pointer.svg)
- Box2d: delete all, add [background](https://app.heazy.studio/), based on [box2d](https://griffpatch.github.io/scratch-gui/static/assets/f87904843f21a05464c4acc3ec4d368d.png)

**Comment by True-Fantom** [comment]
For icons of `cursor` and `pointerlock`: They will be need pixelated rendering

**Comment by True-Fantom** [comment]
@GarboMuffin Oh, and you can not expand, but simply crop the images, when add them to TW
(I specially made them with this in mind)

**Comment by GarboMuffin** [comment]
#90 is where future image discussion happens
