### ISSUE TITLE
Make the website look better

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#21]
If you look at the website right now, you will notice that it is rather ugly. If anyone wants to make an attempt at making it look better, you're more than welcome to try

**Comment by softedco** [comment]
I can help, I have [this](https://softedco.github.io/NewDesign/) as an example, btw it's made 100% in turbowarp and it wouldn't be that pretty if not the **screen resizing that breaks high quality pen** fix I suggested earlier, huge thanks for fixing it actually

**Comment by joshpinto6** [comment]
Should extensions shown on the "Choose an extension" page of https://experiments.turbowarp.org/unsandboxed-extensions/editor have their own cover images? More specifically, when you click the add-extension button in the bottom left-hand side of the editor, the unsandboxed extensions appear slightly awkward on the "Choose an Extension" page as they do not have custom images like the other extensions do. This only presents a problem in the sense that creating a fancy cover image for every unsandboxed extension into the future may be unsustainable...

Another idea is that each extension could have a simple icon and the cover image would consist of this icon centered on a colored background. For example, the gamepad extension could have a white SVG gamepad icon centered on the Turbowarp red background... This allows us to easily upload an icon for each unsandboxed extension which will help improve the quality of the "Choose an extension" page.

A second issue may be potential documentation for these and future extensions. Maybe in the future a new section of the Turbowarp docs could provide documentation for some of the extensions e.g. Box2D.

**Comment by GarboMuffin** [comment]
The idea right now is that there will be 3 "tiers" of unsandboxed extensions:

 - Extensions that are available on extensions.turbowarp.org but not listed on the website. Would include experimental addons and some internal testing ones.
 - Extensions that are listed on extensions.turbowarp.org. Would include most community-contributed extensions.
 - Extensions that are listed in the extension chooser. Think of these as "featured" extensions. These will each have images and icons in the library at some point. Just haven't gotten around to that yet.

extensions.turbowarp.org is also where documentation for the extensions will live. The site design needs to somehow accommodate that.

**Comment by joshpinto6** [comment]
So I'm assuming something like a documentation modal in the editor which can be triggered from the "Choose an extension" page?

**Comment by CST1229** [comment]
> So I'm assuming something like a documentation modal in the editor which can be triggered from the "Choose an extension" page?

I assume it would be an "Open Documentation" link in the block palette, like what TurboWarp Blocks does.

**Comment by GarboMuffin** [comment]
About the documentation: Every extension listed on the site will set a docsURI pointing to a page on extensions.turbowarp.org for people to learn about the extension, how to use it, things like that. We could put all of this on the homepage and use anchors to bring people to the right spot automatically or give each extension its own page. If we start giving each extension its own page, it might be a good idea to look into a build step for the website to help keep things maintainable.

**Comment by joshpinto6** [comment]
@GarboMuffin I agree about the build step, and I was also planning on asking about a repo restructure that would give each extension a subfolder, that way files related to each extension such as cover images, documentation, etc. would be more organized. I think that anchors for documentation could work, but would probably make the homepage cluttered over time, so I think the idea of giving extensions separate pages is probably the right way to go...

I also started work on improving the extensions homepage and I'm not done yet, but I'm still testing/experimenting with things. I'm making a good start, though and I added an image of what I have (so far) below.

![image](https://user-images.githubusercontent.com/91392083/201189908-ee7a3c93-4fdd-46e6-a4af-59a952e7fb72.png)

**Comment by CST1229** [comment]
Maybe the site should be styled after Scratch's extension library?

**Comment by joshpinto6** [comment]
@CST1229 Could this become confusing to users who may not realize which page they are on... That was one of the concerns I thought about while designing it. Additionally, would the blocky style of the extension library cards be sustainable in the future if many more extensions are added, or would the homepage become overly cluttered? Also, here's a new image:
![image](https://user-images.githubusercontent.com/91392083/201203453-b1c9e797-47d8-46bf-822f-98fb23213582.png)

**Comment by CST1229** [comment]
> ould this become confusing to users who may not realize which page they are on... That was one of the concerns I thought about while designing it. Additionally, would the blocky style of the extension library cards be sustainable in the future if many more extensions are added, or would the homepage become overly cluttered?

I haven't thought of those.

**Comment by joshpinto6** [comment]
And when (if?) [ScratchLabs ](https://lab.scratch.mit.edu) ever becomes open source, those extensions can probably be added to Turbowarp 👍

**Comment by GarboMuffin** [comment]
we'll do something like this

![image](https://user-images.githubusercontent.com/33787854/209426620-c88fab91-69bc-48d0-9f20-de75b2d5220f.png)
