### ISSUE TITLE
How do I try out Shovel Utils?

### ISSUE THREAD

**Issue by NDM1574** [TurboWarp/extensions#215]

**Comment by TheShovel** [comment]
@GarboMuffin add the extension to the website

**Comment by NDM1574** [comment]
There seems to be a lot of missing extensions on the website, any chance its possible to load them anyways?

**Comment by TheShovel** [comment]
Go to extensions (from where you pick stuff like the pen extension) and click the "load custom extension button. Then paste this link in there:
https://extensions.turbowarp.org/TheShovel/ShovelUtils.js

**Comment by GarboMuffin** [comment]
It's on the website now
