### ISSUE TITLE
Suggestions for Utilities Plugin

### ISSUE THREAD

**Issue by NDM1574** [TurboWarp/extensions#217]
replaceFile type[costume,sound,backdrop] with [fileResult] BLOCK (fileResult accepts fileResult reporter)
fileResult REPORTER
fileExtension REPORTER
fileName REPORTER
openFileDialog title:[value] custom CSS (optional):[value] accept files:[fileExtension] BLOCK
downloadFile name:[fileName] extension:[fileExtension] costume/sound:[value] BLOCK (Value accepts any costume or sound in entire project)
greenFlag BLOCK

If you need an explanation for any block please tell me

**Comment by TheShovel** [comment]
GreenFlag already is in ShovelUtils as Restart project. And you can do most of what you mentioned with the Files extension.

**Comment by NDM1574** [comment]
> GreenFlag already is in ShovelUtils as Restart project. And you can do most of what you mentioned with the Files extension.

Could you quickly explain how to interact with ZIP files, along with replacing sprites and sounds?

**Comment by TheShovel** [comment]
You can't interact with zip files, but you can add sprites and sounds with links to their respective location on a website (look at the example links)

**Comment by NDM1574** [comment]
That wouldn't work, this would have to be a 1 file/1 link for all thing, its for full mod support on my game

**Comment by echoless3484** [comment]
@TheShovel You think its possible to add Zip support to either the files extension or ShovelUtils?

**Comment by CST1229** [comment]
It's now possible to interact with zips with the Zip extension.

**Comment by echoless3484** [comment]
It sure is! I love it

**Comment by SharkPool-SP** [comment]
these all exist now in various extensions as mentioned above
