### ISSUE TITLE
JSON Extension Suggestion

### ISSUE THREAD

**Issue by NDM1574** [TurboWarp/extensions#218]
An extension that allows you to convert lists and multiple variabls/reporters into a single json file, then read it and separate values and load it into a project.

**Comment by TheShovel** [comment]
You can get a json file for lists using ShovelUtils.

**Comment by TheShovel** [comment]
Also there is #205

**Comment by Skyhigh173** [comment]
I will prob do it in my JSON extension if I have free time.
