### ISSUE TITLE
Unpredictable & Broken behavior with unsandboxed extensions loaded from localhost

### ISSUE THREAD

**Issue by ImSomeOtherGuy** [TurboWarp/extensions#222]
Unsandboxed extensions are looking to be an awesome thing, but trying to load _custom_ ones has proven way more complicated than I thought. Considering I haven't seen anyone else mention this, the issues described below may be a problem with my setup (or skill) so I may try this on linux or another windows partition and do a follow-up comment later. If all the crap that keeps happening to me is my fault, then this issue can just be closed.

None of the extensions I tested were imported directly from the extension gallery. Anything from the extension gallery works flawlessly. Instead, I downloaded all the extensions from the repo itself (because there are some that are not in the gallery on the desktop app). I know for a fact that no firewall, proxy, port, or other settings are interfering with Turbowarp or Chrome in any way. I also have the newest version of Python installed.

----------

Here are the issues in detail:

>1. Anything that uses online features on the online editor is extremely hit-or-miss. The default values for every block that uses online work as expected. However, as soon as I input anything from another domain, the blocks won't work. 
-For example, when I put in the localhost path of a text file into fetch, the block will report nothing. Sometimes it just stops immediately, but other times it goes on forever. 
-Strangely enough, the CMD window I have open which is logging traffic says there is a request made and gives me the 200 code along with the filename, meaning the connection was successful. (Even if the connection never actually finished!) Loading the same file path into a new chrome tab works exactly as expected.

>2. Anything online, period, on the desktop app, will not work. This includes things as simple as the "hello world" on fetch. Strangely enough, many extensions which normally could access local files now can't.

----------

Below are some console errors I found when trying to run specific blocks.

>This is what the console says whenever I try to use the fetch block in Turbowarp Desktop:
![weird error](https://user-images.githubusercontent.com/113465904/222615777-b289cf72-65f0-412a-89d3-b30bf9223989.png)

>Similarly, something happens whenever I try to load an image from penplus.js (still Turbowarp Desktop):
![error with penplus](https://user-images.githubusercontent.com/113465904/222616175-3837bd97-1b32-40f5-b2ab-e6746c9aea6b.png)

>Once again, this only applies to online stuff. Offline blocks, such as profanity.js, work just fine.

>Here is an error with loading some text on fetch.js:
![fetch error on online](https://user-images.githubusercontent.com/113465904/222617632-a59d9fc1-48e7-4200-b4ca-ebdbebe4c0a4.png)
This one could be my fault, but considering the script has no documentation regarding this, I'm not fully sure.

----------

Once again, I _will_ follow up with another comment saying if I was successful with other operating systems and how things worked with other extensions.

**Comment by GarboMuffin** [comment]
> Scratch.fetch is not a function

Desktop app is old, will be fixed in next update. Just use fetch() instead for now.

> Access to fetch at ... Access-Control-Allow-Origin ...

Your server needs to set `Access-Control-Allow-Origin` to `*` so that other websites are allowed to access it (this being opt-in is why online banking is not completely insecure). Google "cors" to learn more. The development server we provide in this repository does so automatically as does extensions.turbowarp.org.

**Comment by GarboMuffin** [comment]
Things in the gallery work flawlessly because they use an old snapshot which doesn't use things that aren't yet supported in the desktop app: https://github.com/TurboWarp/extensions/tree/08b82d4605b4de4a11d994dde65b9b01a89d7587

**Comment by ImSomeOtherGuy** [comment]
Good to know, thanks for the quick response!!
