### ISSUE TITLE
Pen+ stamping will overlap the entire stage in black until the stage is updated again.

### ISSUE THREAD

**Issue by Austinoooo** [TurboWarp/extensions#226]
The extension is made pretty useless because you can either ONLY see the pen+ stamped image or the rest of the stage which really isn't ideal. 

But updating isn't just moving a sprite on the stage, it can also be caused by resizing the stage using the "small stage" and "large stage" buttons which makes it pretty useless too because it would be ideal to have the current stage view stay the same at all times.

https://user-images.githubusercontent.com/66364927/222920875-1854ed85-1c1b-4549-9f9f-f5d52b87b190.mp4

**Comment by Mickmick2012** [comment]
if your thing is only to get images from url, you can try ShovelUtils otherwise, ignore this comment

**Comment by GarboMuffin** [comment]
Believe this will be fixed by V6

**Comment by David-Orangemoon** [comment]
> Believe this will be fixed by V6

yes
