### ISSUE TITLE
Update block colors

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/extensions#227]
When Scratch's block colors update, all of the extensions with custom block colors will need to update too. Each one should have a set of colors for each theme: default colors, high contrast, and dark mode by the time TurboWarp receives the block colors update. I'd also assume these can't be changed with the customizable block colors addon.

We don't have to do this now, but I think it should be done before the block colors update arrives.

**Comment by GarboMuffin** [comment]
scratch-gui will figure it out on its own - https://github.com/TurboWarp/scratch-gui/commit/84994767ae04ed22d8e0c20c5c91581396a34b11

**Comment by DNin01** [comment]
> scratch-gui will figure it out on its own - https://github.com/TurboWarp/scratch-gui/commit/84994767ae04ed22d8e0c20c5c91581396a34b11

🤩
