### ISSUE TITLE
JSON -> `replace item ( ) of ( ) to ( )` is inconsistent with other blocks

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/extensions#229]
All of the JSON blocks treat the first array value as number 1, except for `replace item ( ) of ( ) to ( )`, which treats the first array value as number 0.

Expected behavior:
`replace item (2) of (["love","heart","follow"]) to (fav)` = `["love","fav","follow"]`

Actual behavior:
`replace item (2) of (["love","heart","follow"]) to (fav)` = `["love","heart","fav"]`

**Comment by GarboMuffin** [comment]
@Skyhigh173 

considering how new the extension is and that this is a bug, we can ignore the typical backwards compatibility concerns

**Comment by Skyhigh173** [comment]
Ok I will fix it!
