### ISSUE TITLE
FPS Extensions

### ISSUE THREAD

**Issue by ZekusV** [TurboWarp/extensions#233]
A new block that is set to the users FPS and not the project running FPS.

**Comment by Mickmick2012** [comment]
I agree that it's complex to calculate FPS on vanilla Scratch

**Comment by TheShovel** [comment]
This is gonna be added in a new debugging extension I am making, along with on screen errors (instead of having to go check the dev tools in chrome, you will straight up see the error on screen).

**Comment by TheShovel** [comment]
Changed my mind and decided that it wouldn't fit well in the debug extension, so I just added it in ShovelUtils.
Wait for #272 to get pulled.

**Comment by Mickmick2012** [comment]
#273 was merged
