### ISSUE TITLE
box2d extension - some suggestions

### ISSUE THREAD

**Issue by macimas** [TurboWarp/extensions#236]
1. `setup stage [boxed stage]` should be based on actual stage size
currently it sets up walls around 480×360. i think it would be nice if it makes the walls based on actual stage size

https://user-images.githubusercontent.com/42163944/223418023-ffa01552-cf75-4c14-9163-b7393ce15038.mp4

<br>

~~2. replace `set density […v] roughness […v] bounce […v]` with something that's similar to this:~~<br>
something similar was added in pull request #488
![image](https://user-images.githubusercontent.com/42163944/227524157-2c29e056-f9c5-465e-a01c-047b2cc470d3.png)

**Comment by macimas** [comment]
i decided to add another suggestion here. lmk if i should move it to its own issue

**Comment by GarboMuffin** [comment]
believe everything here has been added
