### ISSUE TITLE
ShovelUtilis cannot import sounds nor images to the background

### ISSUE THREAD

**Issue by Mickmick2012** [TurboWarp/extensions#240]
You can't set editing target to the background too

**Comment by GarboMuffin** [comment]
@TheShovel

**Comment by Mickmick2012** [comment]
maybe because background isn't a sprite ?

**Comment by TheShovel** [comment]
You should set the editing target to "Stage"

**Comment by TheShovel** [comment]
Nvm, it's because I use `vm.runtime.getSpriteTargetByName(NAME).id`
Gonna add a new block that sets the stage as the editing target, so there aren't compatibility issues with people using the existing block.

**Comment by Xeltalliv** [comment]
>  Gonna add a new block that sets the stage as the editing target, so there aren't compatibility issues with people using the existing block.

I don't think it's going to affect compatibility with existing projects since currently attempting to switch to Stage causes that block to throw, which currently existing projects should already avoid doing.

**Comment by TheShovel** [comment]
Fixed it with #254 . Now you can do "Stage" and it will set the editing target to stage. Wait for GarboMuffin to push it.

**Comment by Mickmick2012** [comment]
Pushed + merged
