### ISSUE TITLE
Issues with character entity references in extension names

### ISSUE THREAD

**Issue by Xeltalliv** [TurboWarp/extensions#241]
> and replacing the name from `Clipping, blending` to `Clipping & Blending` (https://github.com/TurboWarp/extensions/issues/90#issuecomment-1458499053)

Names like this are currently not possible.
![image](https://user-images.githubusercontent.com/90340988/223777087-132b933f-644f-4c08-91c7-d971b59d3933.png)

**Comment by Xeltalliv** [comment]
After digging around, I found what part of scratch can be modified to make it work, but it was discovered using "let's try random stuff until something works" approach so I doubt it's a proper solution.
https://github.com/Xeltalliv/extensions/blob/examples/examples/amp.js
![image](https://user-images.githubusercontent.com/90340988/223851155-f3e08ec8-1fd2-47b6-9a8a-2e0585544b1b.png)

**Comment by GarboMuffin** [comment]
There seems to be some rather pervasive issues regarding not xml escaping things properly in the VM, will be fixing that today

Note that this is unlikely to cause XSS as this XML is not being interpreted as HTML

**Comment by GarboMuffin** [comment]
In the next update (probably later today), you will be able to just do

```js
  name: 'Clipping & Blending'
```
