### ISSUE TITLE
Database Extension

### ISSUE THREAD

**Issue by lolpng944** [TurboWarp/extensions#250]
It would be cool to have a database extension like create accounts, save values etc.

**Comment by showierdata9978** [comment]
The JSON extension:p

**Comment by CST1229** [comment]
> The JSON extension :p

I don't think that lets you save data.

**Comment by showierdata9978** [comment]
> > The JSON extension :p
> 
> I don't think that lets you save data.

and the file ext, so

**Comment by NachoCN** [comment]
> The JSON extension :p

What JSON extension

**Comment by CST1229** [comment]
> and the file ext, so

That requires going through a file selector prompt, which isn't nearly as simple as doing no manual steps at all.

> What JSON extension

Probably https://extensions.turbowarp.org/Skyhigh173/json.js
