### ISSUE TITLE
[For Extension developers] Can you guys add extensions to the unsandboxed list?

### ISSUE THREAD

**Issue by showierdata9978** [TurboWarp/extensions#251]
https://scratch.mit.edu/discuss/topic/653955/

**Comment by True-Fantom** [comment]
@showierdata9978 Why i true-fandom?!(

**Comment by showierdata9978** [comment]
> @showierdata9978 Why i true-fandom?!(

was going off directory names

**Comment by True-Fantom** [comment]
![Скриншот 09-03-2023 202229](https://user-images.githubusercontent.com/116278271/224106543-413217bf-8366-4c54-b651-a74256fc1595.png)

**Comment by True-Fantom** [comment]
@showierdata9978 Thanks)

There is another mistake: `network-m` is `network-mini`

**Comment by showierdata9978** [comment]
I had assumed modified due to TW rules

**Comment by True-Fantom** [comment]
@showierdata9978 Thank you for fixing it :)

**Comment by Xeltalliv** [comment]
There are few other mistakes:
- AR link is broken
- Box2D link leads to extension homepage

**Comment by showierdata9978** [comment]
:p that subform is so dead

**Comment by showierdata9978** [comment]
> There are few other mistakes:
> 
> * AR link is broken
> * Box2D link leads to turbowarp extensions homepage

fixed
