### ISSUE TITLE
Error: The monitor will not be displayed after the program automatically loads third-party extensions

### ISSUE THREAD

**Issue by SIPC** [TurboWarp/extensions#257]
![image](https://user-images.githubusercontent.com/92251518/223434913-814a1b63-1939-4294-8ae8-5acc17b41b34.png)
Apparently I've turned on the list monitor, but he's not showing up on stage
info: v1.7.1 production, win32 x64, Electron 22.0.3

**Comment by GarboMuffin** [comment]
still happen?

**Comment by SIPC** [comment]
> still happen? 还发生吗？

NO
