### ISSUE TITLE
New extension icons aren’t displayed in the editor’s extension library.

### ISSUE THREAD

**Issue by ProjectSB4** [TurboWarp/extensions#259]
The new extension icons for Stretch, Gamepad, and Mouse Cursor aren’t displayed on the extension gallery in the editor, as shown below.
![IMG_2209](https://user-images.githubusercontent.com/116463349/224452260-8752af2b-4b48-4955-9e68-f3d1e7e4d322.jpeg)

**Comment by GarboMuffin** [comment]
yeah, they're in scratch-gui instead

I'm going to update that and add several more at the same time, soon
