### ISSUE TITLE
Add a discord rich presence to packaged project

### ISSUE THREAD

**Issue by Forysium** [TurboWarp/extensions#275]
Hello guys,
i found a game made and packaged with turbowarp, that somehow managed to add a discord rich presence.
How is this possible? It was packaged with electron. Is there any extension out there that can do this?

**Comment by GarboMuffin** [comment]
ask the person who made that project how they did it and consider sharing it here for everyone else to read

closing as a duplicate of https://github.com/TurboWarp/extensions/issues/220

**Comment by Azulcat** [comment]
@Forysium what is the game?
