### ISSUE TITLE
Global/Project Effects Extension

### ISSUE THREAD

**Issue by SebasMCYT** [TurboWarp/extensions#276]
I don't know if it's possible, but it would be cool to have an extension that can set effects like brightness, color, fisheye, etc. to the entire project or to all sprites at once instead of just one.

**Comment by TheShovel** [comment]
#299 is adding this.

**Comment by SebasMCYT** [comment]
Thank you! Would there be the possibility of adding more effects in the future?

**Comment by TheShovel** [comment]
These are all the effects possible with css. A more complex system would be needed if you want more, and I am not willing to do it, as it takes a lot of time.

**Comment by SebasMCYT** [comment]
Oh ok, thanks!

**Comment by GarboMuffin** [comment]
leave issues open until they are *actually* resolved

**Comment by SebasMCYT** [comment]
Oh ok

**Comment by GarboMuffin** [comment]
#299 is pretty close
