### ISSUE TITLE
Can TurboWarp extensions be made in Chinese?

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/extensions#278]
Can TurboWarp extensions be made in Chinese?

**Comment by LukeManiaStudioss** [comment]
What do you mean by this? Do you mean they can be translated into Chinese to allow for better accessibility?

**Comment by softedco** [comment]
Custom extensions are currently not available for translation

**Comment by GarboMuffin** [comment]
Closing as a duplicate of https://github.com/TurboWarp/extensions/issues/278

**Comment by CST1229** [comment]
...this is #278

**Comment by GarboMuffin** [comment]
... as a duplicate of https://github.com/TurboWarp/extensions/issues/195

**Comment by qxsck** [comment]
> What do you mean by this? Do you mean they can be translated into Chinese to allow for better accessibility?

Emm, I mean the expanded block text is in Chinese.

**Comment by Mickmick2012** [comment]
i think he meant that the text is in Chinese only (no english), in that case, no, english is the language that most user knows

**Comment by True-Fantom** [comment]
@qxsck @Mickmick2012 You can make an extension ONLY in Chinese, but as a personal extension (it will not be posted on the site)
