### ISSUE TITLE
Pen+ blocks stuck in an infinite loop when rendering something

### ISSUE THREAD

**Issue by Meehdrescher** [TurboWarp/extensions#288]
![grafik](https://user-images.githubusercontent.com/83909483/226169441-d3416367-fd80-4072-a8c4-3417254057ba.png)
Some blocks, for example the image stamping block or the triangle drawing block, are stuck in an infinite loop when activated.
I've installed the newest version of TW, restarted the project, restarted the PC, didn't change anything though

**Comment by TheShovel** [comment]
Can you open the console and send a screenshot after you click the block?

**Comment by Meehdrescher** [comment]
> Can you open the console and send a screenshot after you click the block?

How do I open the console in the desktop version?

**Comment by TheShovel** [comment]
> > Can you open the console and send a screenshot after you click the block?
> 
> How do I open the console in the desktop version?

Ctrl+Shift+I to open the console.

**Comment by Meehdrescher** [comment]
![grafik](https://user-images.githubusercontent.com/83909483/226173270-ad34fd87-52c2-4775-a2ca-db6d1edd545b.png)
here it is

**Comment by TheShovel** [comment]
This is because the desktop app wasn't updated to support the new fetch functions. There is nothing you can do right now besides use the web version of TurboWarp.
@GarboMuffin has to update the app.

**Comment by GarboMuffin** [comment]
How exactly did you go about loading Pen+? What version of the desktop app are you using? 1.7.1 includes a version of pen+ that doesn't use those APIs.

**Comment by Meehdrescher** [comment]
The addons now work because I reinstalled Turbowarp.
