### ISSUE TITLE
Render scale

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#292]
Extension that lets you render at a lower scale, while keeping the actual resolution.

Blocks:
set render scale [number]%
change render scale [number]%
interpolation mode [dropdown] (Bicubic, Bilinear)

Reporter blocks:
render scale 
interpolation mode

Why?

Because people can make "dynamic pixel art", by using the pen extension and a bit of math to make a rope that moves with wind, for example, and then downscale it to make it pixelated.
Like here (example is from Celeste)

https://user-images.githubusercontent.com/68913917/226668967-1590e028-9064-4ecb-bce6-01478a248c4c.mp4

**Comment by TheShovel** [comment]
This is NOT the same as the "pixelated effect" block, as it affect the whole frame, not just the sprite's current costume.

**Comment by OeildeLynx31** [comment]
Very useful extensions !
The blocks will be in a new extension or in an extension which already exist?
It is also very useful to set the resolution to low for a photo project with camera !

**Comment by TheShovel** [comment]
#299 will make this possible. Gonna close when it gets pushed.
