### ISSUE TITLE
[Question] About the new unsandboxed API

### ISSUE THREAD

**Issue by showierdata9978** [TurboWarp/extensions#30]
With The [Unsandboxed Extention Guide](https://scratch.mit.edu/discuss/topic/632106/?page=1). I am worried about the api NOT working with other scratch mods. expressly with schools blocking Turbowarp.  while you can use stuff like Adacraft, and at this moment. It has no such API.

another thing is, why do you want the class to be inside the function instend of somthing like this?

```js
class YourExt {
 getinfo() { return {...} }
}

(function(Scratch) {
  'use strict';
  var ExtClass = YourExt;
  Scratch.extensions.register(new ExtClass());
})(Scratch);
```

**Comment by GarboMuffin** [comment]
Networks blocking turbowarp.org is a valid concern. There is a plan to address that involving buying another domain.

These extensions will indeed not be compatible with other mods at this time, but nothing technically would stop them from making them compatible, using our code or their own code.

The class is inside an IIFE because:

 - If two different extensions try to define a class with the same name, you will get an error
 - Each extension gets their own copy of window.Scratch. Putting the class in the IIFE ensures that each extension uses their own copy and not some other extension's copy

Those might not seem important to you, but having multiple scratch-vm instances on a single page is something we want to support.

I'm probably going to convert extensions from script elements to modules with import() though so there will be a simpler way to address these issues

**Comment by showierdata9978** [comment]
I did come up with a solution for this though.

it checks for TW`s unsandboxed system, if it`s not found it will fallback to using internal systems (although i do prefer the internal way more...)

```js
if (!window.Scratch.hasOwnProperty("vm")) {
  (function() {
    var extensionClass = YourExt;
    if (typeof window === "undefined" || !window.vm) {
        Scratch.extensions.register(new extensionClass());
        console.log("YourExt loaded. Detecting sandboxed mode, performance will suffer. Please load YourExt in Unsandboxed mode.");
    } else {
        var extensionInstance = new extensionClass(window.vm.extensionManager.runtime);
        var serviceName = window.vm.extensionManager._registerInternalExtension(extensionInstance);
        window.vm.extensionManager._loadedExtensions.set(extensionInstance.getInfo().id, serviceName);
        console.log("YourExt loaded. Detecting unsandboxed mode.");
    };
  })()
} else {
  (function(Scratch) {
    'use strict';
    var ExtClass = YourExt;
    Scratch.extensions.register(new ExtClass());
  })(Scratch);
}
```

**Comment by showierdata9978** [comment]
>  Networks blocking turbowarp.org is a valid concern. There is a plan to address that involving buying another domain.

They Count it as games, the best you can prob do is make sure to say that this is not a game site. it is an optimized version of scratch, although the network my school district uses did not unblock it. You could prob move the games part to a subdomain, and show cool technological things on the front page.

**Comment by showierdata9978** [comment]
> Those might not seem important to you, but having multiple scratch-vm instances on a single page is something we want to support.

oh, thats really intresting, one concern with that though. JS is famously single threaded.

**Comment by CST1229** [comment]
> I did come up with a solution for this though.
> 
> it checks for TW`s unsandboxed system, if it`s not found it will fallback to using internal systems (although i do prefer the internal way more...)

I actually have some (partially commented out) code in my (currently unreleased) Unsandboxed Images update that also does exactly that.
```js
	const extensionClass = ImagesExt;
	if (Scratch) {
		if (Scratch.extensions.unsandboxed) {
			Scratch.extensions.register(new extensionClass(Scratch.vm));
		} else {
			throw new Error("Images cannot run in sandboxed mode.");
		} /*
	} else if (globalThis.vm) {
		// Support loading the extension "the old way"
		// (running the code in something like the browser console
		// or E羊icques' load_plugin URL parameter)
		const extensionInstance = new extensionClass(globalThis.vm);
		const serviceName = globalThis.vm.extensionManager._registerInternalExtension(
			extensionInstance
		);
		globalThis.vm.extensionManager._loadedExtensions.set(
			extensionInstance.getInfo().id, serviceName
		); */
	} else {
		throw new Error("Images cannot run in sandboxed mode.");
	};
```

**Comment by showierdata9978** [comment]
> > I did come up with a solution for this though.
> > it checks for TW`s unsandboxed system, if it`s not found it will fallback to using internal systems (although i do prefer the internal way more...)
> 
> I actually have some (partially commented out) code in my (currently unreleased) Unsandboxed Images update that also does exactly that.
> 
> ```js
> 	const extensionClass = ImagesExt;
> 	if (Scratch) {
> 		if (Scratch.extensions.unsandboxed) {
> 			Scratch.extensions.register(new extensionClass(Scratch.vm));
> 		} else {
> 			throw new Error("Images cannot run in sandboxed mode.");
> 		} /*
> 	} else if (globalThis.vm) {
> 		// Support loading the extension "the old way"
> 		// (running the code in something like the browser console
> 		// or E羊icques' load_plugin URL parameter)
> 		const extensionInstance = new extensionClass(globalThis.vm);
> 		const serviceName = globalThis.vm.extensionManager._registerInternalExtension(
> 			extensionInstance
> 		);
> 		globalThis.vm.extensionManager._loadedExtensions.set(
> 			extensionInstance.getInfo().id, serviceName
> 		); */
> 	} else {
> 		throw new Error("Images cannot run in sandboxed mode.");
> 	};
> ```

That looks alot better then my solution, is it ok if i edit it some and put it on the guide?

**Comment by CST1229** [comment]
> is it ok if i edit it some and put it on the guide?

Yes.

**Comment by showierdata9978** [comment]
wait github has auto reload for discussions??

**Comment by CST1229** [comment]
> wait github has auto reload for discussions??

Yes, GitHub live-updates several things (I learned that a long time ago.)

**Comment by GarboMuffin** [comment]
> I'm probably going to convert extensions from script elements to modules with import() though so there will be a simpler way to address these issues

Turns out import() requires CORS so this will not be happening

**Comment by GarboMuffin** [comment]
Actually we can use import() since we control extensions.turbowarp.org and that's all that matters for unsandboxed extensions.

As for network filter issues, we can put a mirror of the extensions on `unsandboxed.org` if it becomes an issue. Hopefully as long as that domain only contains APIs and not anything user-facing, filters won't be inclined to block it.

**Comment by tutacat** [comment]
You should be able to host your extension on GitHub or your own site or Google (many cloud compute or cloud storages have free disk space you can use per month, of which some javascript will not take up an appreciable amount), then just add that to the whitelist for your extension loader.

Weird how schools would be blocking github, or especially turbowarp, but I guess they don't want people accidentally stumbling upon... unlicensed copyrighted content. They better block Scratch too just to be safe..... and image search.
