### ISSUE TITLE
camera controls extension - camera y is reversed

### ISSUE THREAD

**Issue by macimas** [TurboWarp/extensions#303]
camera x does not have this problem, only camera y.

![image](https://user-images.githubusercontent.com/42163944/227613235-e620371f-ec15-45dd-b836-14fcbef36b96.png)

<br>

here's a basic mockup to show it a bit zoomed out, with the magenta outline representing the camera:
![image](https://user-images.githubusercontent.com/42163944/227612390-78b16ff8-4d32-4c9a-a199-ec4986714d93.png)

**Comment by DT-is-not-available** [comment]
Seems I might've accidentally made that happen in the last update, fixed in [this PR](https://github.com/TurboWarp/extensions/pull/304#issue-1640392621).

**Comment by macimas** [comment]
very nice
