### ISSUE TITLE
HTML Iframe Extension Suggestion

### ISSUE THREAD

**Issue by NOVASPIDERULTRA** [TurboWarp/extensions#308]
I think this is possible (I've seen it in Penguin Mod so I'm sure).

**Comment by NDM1574** [comment]
Penguin Mod? Send a link pls

**Comment by OeildeLynx31** [comment]
It is in [adacraft](https://www.adacraft.org/studio/), with the extension "browser"

**Comment by GalacticCoder922** [comment]
PenguinMod is [here](penguinmod.site)

**Comment by TheShovel** [comment]
Going to make a pull request with the extension tomorrow.

**Comment by TheShovel** [comment]
#448 Will add this. You can close this issue after the pull request is merged.

**Comment by GarboMuffin** [comment]
we have this now
