### ISSUE TITLE
some camera extension bugs

### ISSUE THREAD

**Issue by PSYclownYT** [TurboWarp/extensions#312]
y is inverted, and a forever: point to mouse pointer thinks the mouse is still in the normal 0,0 canvas.

**Comment by PSYclownYT** [comment]
I was working on a top-down game simalar to battle arena 2 by kikoko_ on scratch

**Comment by PSYclownYT** [comment]
when you are away from the origional canvas, the mouse pointer glitches out

**Comment by GarboMuffin** [comment]
Merging this into #930
