### ISSUE TITLE
Animation Extension?

### ISSUE THREAD

**Issue by Cbr2011** [TurboWarp/extensions#318]
like without doing animations without sprites and 0.1 seconds blocks.
![image](https://user-images.githubusercontent.com/82298138/228944697-14230f41-0678-47c1-b36e-e85839a85ac8.png)
One on GameJolt already requested this.

**Comment by SebasMCYT** [comment]
How would it work? Can you elaborate?

**Comment by NOVASPIDERULTRA** [comment]
I don't know how this would work (also wait you use 0.1 second blocks? I'm sorry but that doesn't look good)

**Comment by Cbr2011** [comment]
Like a video loader?

**Comment by TheBombyMaster** [comment]
That's actually a really cool idea! Someone should implement something like that for video files in general! (If it's possible of course, sounds like it would be a lot of work tbh)

**Comment by Cbr2011** [comment]
[this is a outdated topic but I want to revive it because yes]
I'm just gonna mention pull request #840 because it's a video loader, It doesn't use youtube videos though [plus, there's now a iframe extension so who really cares?]

**Comment by Cbr2011** [comment]
i'll close this issue by the time it gets merged.
