### ISSUE TITLE
File Editor

### ISSUE THREAD

**Issue by TeknikSpace** [TurboWarp/extensions#320]
I'm Not Sure Is This Is Possible, But It would Be Cool To have An Extension That Can Write And Read To Files Directly On The User's Computer? This Would Allow Games To Save And Load From The PC And Allow For An Alternative Save System To Save Codes Or Cloud Savers

Please Consider This As I Believe Is Would Help Me And Many Others Who use Turbowarp.

**Comment by CST1229** [comment]
Websites cannot directly write to the user's filesystem; only write to files that the user chose to open before (see #156; though that only works in Chrome) and to a site-specific local storage area (see #55).

**Comment by Xeltalliv** [comment]
> only write to files that the user chose to open before (see #156; though that only works in Chrome)

using that API, user can actually provide access to an entire directory and after that website can read/create/change/delete any files/directories inside it. https://vscode.dev/ is a good demonstration of it

**Comment by TeknikSpace** [comment]
What If It Needed Access In The Browser But When Packaged Could Work Fine? Is That Possible?

**Comment by TeknikSpace** [comment]
Oops, New To This, Accidentally Closed Suggestion

**Comment by softedco** [comment]
> I'm Not Sure Is This Is Possible, But It would Be Cool To have An Extension That Can Write And Read To Files Directly On The User's Computer? This Would Allow Games To Save And Load From The PC And Allow For An Alternative Save System To Save Codes Or Cloud Savers
> 
> Please Consider This As I Believe Is Would Help Me And Many Others Who use Turbowarp.

You can already implement local saves if that's what you want

**Comment by TeknikSpace** [comment]
Yes, and I accidentally forgot about the cloud variable saving in the compiler, I was thinking of with the files extension, bring able to write to files on a save directory, but that will work, I just forgot about it, thanks for your input!
