### ISSUE TITLE
Can't get client IP

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#322]
I am making a multiplayer game, and I want to be able to ban users based on their IP. For some reason, any attempt at fetching the IP (even from the server itself) just returns a error saying `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`.
I am assuming this is another thing to protect TurboWarp users, but in the end it just ends up being annoying, just like the "Allow to fetch" button.

**Comment by GarboMuffin** [comment]
ERR_BLOCKED_BY_CLIENT means a browser extension, adblocker, or other browser privacy feature is blocking the request. We can not do anything about this, it's a problem with your browser's settings

**Comment by GarboMuffin** [comment]
in the desktop app, that error might also mean that the website is missing Access-Control-Allow-Origin:*

**Comment by CST1229** [comment]
Also, if the IP bans work on the client side, they'd probably be very easy to bypass.

**Comment by TheShovel** [comment]
> in the desktop app, that error might also mean that the website is missing Access-Control-Allow-Origin:*

Ah, that was the issue. The API didn't have that enabled.
Weird that it happened only in the desktop app.

**Comment by SIPC** [comment]
```
        IP() {
            let endpoint = 'https://api.ipify.org?format=json'
            async function getData() {
                const response = await fetch(`${endpoint}`);
                const data = await response.json();
                console.log(data['ip'])
                if (data['ip'] != undefined) {
                    return data['ip'];
                } else {
                    return 'undefined';
                }
            }
            return getData()
        }
```
