### ISSUE TITLE
(Controller mod) Sprite veers off to the right when the joystick position is neutral

### ISSUE THREAD

**Issue by Breakfastcrafty** [TurboWarp/extensions#324]
### Expected Behavior

No joystick movement when neutral

### Actual Behavior

It veers off to the right

### Steps to Reproduce

When flag clicked
Forever[
Point in direction(direction of axes (X stick) on pad (X))
Move X steps
]
### Operating System and Browser

Windows 11 Firefox 111.0

**Comment by Martinelplayz** [comment]
2 words that might explain. Joystick Drift

**Comment by GarboMuffin** [comment]
Stick drift would cause other problems, but this issue will appear on any controller

I should've stated earlier, but the solution for the sprite moving is to do this:

![image](https://github.com/TurboWarp/extensions/assets/33787854/266fde5a-603d-46e0-98af-74284b33e184)

Which also allows analogue speed controller, but does not yet fix the direction resetting to 90.
