### ISSUE TITLE
JSON extension doesn't work in packager

### ISSUE THREAD

**Issue by Skyhigh173** [TurboWarp/extensions#327]
as https://github.com/TurboWarp/extensions/discussions/309 says, JSON extension doesn't work in packager. I am using website version of TurboWarp.

**Comment by MA-master-sec** [comment]
Can you tell me which block is error?

Maybe there's something wrong with  Javascript?

**Comment by MA-master-sec** [comment]
Can you tell me which block is error?

Maybe there's something wrong with  Javascript?

**Comment by Skyhigh173** [comment]
@MA-master-sec the 'set list' doesn't work

**Comment by TheShovel** [comment]
@MA-master-sec You can take the code from ShovelUtils, for the 'set list' block.

**Comment by Skyhigh173** [comment]
@TheShovel ik but it seems like that that block doesn't support clone

**Comment by MA-master-sec** [comment]
try this?
![image](https://user-images.githubusercontent.com/126303227/232174963-23b5a2ab-bdb9-499b-a793-a0baba543261.png)

**Comment by Skyhigh173** [comment]
@MA-master-sec i guess it is slow

**Comment by MA-master-sec** [comment]
"without screen refresh"

anyway,'set list' is slow,too

**Comment by Skyhigh173** [comment]
> "without screen refresh"
> 
> 
> 
> anyway,'set list' is slow,too

(Sorry for no reply)
Why set list is slow?

**Comment by MA-master-sec** [comment]
A test code like this
![image](https://user-images.githubusercontent.com/126303227/235884557-b9200bcc-1240-4f89-b58b-d65c43b8457f.png)
10,000 times takes me 1.11seconds
another test
![image](https://user-images.githubusercontent.com/126303227/235885756-f49d09ad-2dd2-417a-9abc-567370aa8bde.png)
100,000,000 times only takes me 1.032seconds

**Comment by MA-master-sec** [comment]
> @MA-master-sec i guess it is slow I will try it later

Do not use it when the array is too long

**Comment by GarboMuffin** [comment]
this was fixed, open new issue if not
