### ISSUE TITLE
Why LMS returns Internet Explorer when I'm running Firefox?

### ISSUE THREAD

**Issue by Cbr2011** [TurboWarp/extensions#334]
![image](https://user-images.githubusercontent.com/82298138/231302833-fb3b45f1-2804-47be-90b6-17dc587db086.png)

LMS says I'm running Internet Explorer and

Navigator says Firefox which I'm running as my browser. Is there a reason for this?
![image](https://user-images.githubusercontent.com/82298138/231302865-625fc83c-70a5-4088-9b4b-ff507ff50afa.png)
I know these are plugins developed by two different people, I just wanna know why this occurs.

**Comment by David-Orangemoon** [comment]
Internet explorer is probably just a default for LMS while navigator probably checks for firefox. Just a guess though.

**Comment by Cbr2011** [comment]
![image](https://user-images.githubusercontent.com/82298138/231307062-d406a5ed-a5c3-4391-83bc-6d4fd77f8113.png)
That might be right I guess, I found that this is a bug that wasn't coded probably compared to navigator. Looking in LMS Plugin's code it got an error and instead returned internet explorer,

**Comment by GarboMuffin** [comment]
pretty sure this should be fixed now? works for me
