### ISSUE TITLE
Fatal Error w/ ShovelUtils

### ISSUE THREAD

**Issue by echoless3484** [TurboWarp/extensions#336]
@TheShovel 
`import image from <> name <>` crashes Costume Editor in some scenarios

**Comment by TheShovel** [comment]
Mind sending the images that cause that?

**Comment by echoless3484** [comment]
Sure, I'm unable to send them now, I'll try to send then around 11:35 tommorow (Mountain Standard Time)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NDM1574** [comment]
i'm echoless3484
