### ISSUE TITLE
Sound won't import (ShovelUtils)

### ISSUE THREAD

**Issue by gh-nachoso** [TurboWarp/extensions#342]
So when i try to import any sound (even the default one) using ShovelUtils it just won't import

**Comment by TheShovel** [comment]
The default link is broken. Please try another link with a MP3.

**Comment by gh-nachoso** [comment]
> The default link is broken. Please try another link with a MP3.

doesn't work either

**Comment by TheShovel** [comment]
That's odd. Send me the link you are trying to use.

**Comment by gh-nachoso** [comment]
> That's odd. Send me the link you are trying to use.

https://nintendero-es-pro.xyz/neocreativegames/asc.mp3

**Comment by TheShovel** [comment]
I think the website doesn't accept Cross-origin access. Basically you can't fetch the file from another website.

**Comment by TheShovel** [comment]
Had time to test this today. What I expected was the case.

![image](https://user-images.githubusercontent.com/68913917/233785365-420c170c-e983-4871-a872-39e89ba5ac89.png)

As I said, this is not an issue with the extension, it's an issue with the server the sound is uploaded on.
You can close this issue.

**Comment by GarboMuffin** [comment]
@gh-nachoso you need to use a "CORS proxy" to fetch that file (your favorite search engine can help you find one)
