### ISSUE TITLE
Files extension suggestion: Allow the import of multiple files at once

### ISSUE THREAD

**Issue by Meehdrescher** [TurboWarp/extensions#347]
At the moment, only one file at a time can be opened with the files extension. This is fine for operations that only require a single file, but for things like 3D models made of stacked png images, it gets really tedious to import like 30 png images per model because I have to select every single one individually.

And regarding the ShovelUtils, it is really nice to be able to automatically import images and sounds, but it would be even cooler if we could delete them at runtime too.

**Comment by TheShovel** [comment]
I said before that I wanna add that, but I didn't have time to look into the Scratch documentation to figure that out yet. School eating most of my time right now.

**Comment by GarboMuffin** [comment]
The ShovelUtils part of this was done

**Comment by Meehdrescher** [comment]
Closing this as completed since it is possible to import multiple files as once by using zip files and extracting it inside the project.
Already tried this with a zip that contained 20+ images that create a 3d model of a car when stacked, and made a fully functional modding SDK for a simple vehicle simulation that exports mods zip files which can be imported and extracted by the sim.
Works flawlessly, can only recommend the zip extension.
