### ISSUE TITLE
Camera Extension is breaking pen

### ISSUE THREAD

**Issue by Scratchfangs** [TurboWarp/extensions#348]
Moving the stage or resizing it causes the pen to not work beyond its original 480x360 position

![image](https://user-images.githubusercontent.com/71499307/233743357-af16d9aa-0039-4e5f-a86c-ac01406f59fa.png)

**Comment by Scratchfangs** [comment]
Bump?

**Comment by GarboMuffin** [comment]
Merging into https://github.com/TurboWarp/extensions/issues/930
