### ISSUE TITLE
Camera controls extension bug

### ISSUE THREAD

**Issue by jackb0back** [TurboWarp/extensions#349]
The extension https://extensions.turbowarp.org/DT/cameracontrols.js has an error where if you change the camera X or Y the mouse cursor position gets messed up and does not move relative to the canvas and it instead moves relative to the world.

**Comment by Pizzalover4783** [comment]
There's also a bug where any block that interacts with the edge of the canvas (Touching Edge, If On Edge, Bounce) completely breaks once the camera changes position, and doesn't properly update the position of the edge

**Comment by DT-is-not-available** [comment]
The mouse cursor is supposed to move relative to the world; if the camera is offset by 50 on the x-axis, so is the mouse x. to get the screen/canvas position, just subtract the camera x and y from the respective mouse reporters.

**Comment by DT-is-not-available** [comment]
I will look into fixing this bug soon, it seems like I forgot to apply the proper transformations to the cursor position when zooming or rotating, as I added those later in development.

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
