### ISSUE TITLE
Text Rendering Extension

### ISSUE THREAD

**Issue by Pizzalover4783** [TurboWarp/extensions#357]
I'm not sure if this is even possible, but an extension that displays text anywhere on the screen using any font would be pretty useful.

**Comment by True-Fantom** [comment]
Yes, this is fully possible, and has already been implemented in some Scratch modifications. When I have free time I will try to do it if no one does it before.

**Comment by LukeManiaStudioss** [comment]
I've wanted to make one for a while, I think I might get around to it at some point.

**Comment by TheShovel** [comment]
I already made a prototype for something like that a while ago. Wouldn't recommend using it, but if you need it as a base.
[TextBox.zip](https://github.com/TurboWarp/extensions/files/11332735/TextBox.zip)

**Comment by Mystium-YT** [comment]
You can just do this in base scratch, no need for an extension, Here: 
[Text Rendering Module.txt](https://github.com/TurboWarp/extensions/files/11341821/Text.Rendering.Module.txt)
this is a .sprite3 file that has custom text rendering block

**Comment by Mystium-YT** [comment]
you will need to rename it if you want to use it

**Comment by True-Fantom** [comment]
@Mystium-YT This is not a good option. Firstly, this method does not support additional fonts if you do not add them manually. Secondly, it greatly slows down the loading of the project (if you save it as html, it really is very noticeable). And finally: in this method, the text is only an image, it cannot be selected, copied, create a working link in it, etc.

**Comment by True-Fantom** [comment]
@Mystium-YT And one more thing: the character set itself is limited. I understand that it can be expanded, but this will load the project more and more. And it is almost impossible to fit all unicode characters at all.

**Comment by NOname-awa** [comment]
It's not really as simple as it seems,However, you can generate the bitmap in advance using the font,then use Clipping & Blending to cut out a single character.

**Comment by Mystium-YT** [comment]
Scratch has a text rendering thing but Im not sure how to rip the js

https://lab.scratch.mit.edu/text/

**Comment by Mystium-YT** [comment]
heads up, it isn't selectable of anything either, i just thought id mention it
