### ISSUE TITLE
More docs about custom extensions and unsandboxed extensions

### ISSUE THREAD

**Issue by showierdata9978** [TurboWarp/extensions#36]
You could probably  document the Scratch VM and other things like that for people making unsandboxed extensions, or for contributing to TW source code (as you have an api directly for unsandboxed extensions)

and the other things i have found are extremely outdated or dont contain any actual docs

**Comment by GarboMuffin** [comment]
Documentation is a very known shortcoming right now.

As for documenting Scratch VM internals, https://github.com/TurboWarp/types is the approach we will be using for now. Once you want to do anything non-trivial, no amount of documentation will save you from digging around on your own. At least with types we can make that digging a bit easier. If you set this repository up right, those types are automatically used.
