### ISSUE TITLE
error when loading extensions from url

### ISSUE THREAD

**Issue by Boem22** [TurboWarp/extensions#384]
I get the error "Error:Error in unsandboxed script "link extension". Check the console for more information, how do I resolve this?

**Comment by Boem22** [comment]
does this mean turbowarp needs to get updated in order for the newer extensions to work, or is there way that I can put the java file of the extension somewhere so itll work?

**Comment by Mickmick2012** [comment]
> does this mean turbowarp needs to get updated in order for the newer extensions to work, or is there way that I can put the java file of the extension somewhere so itll work?

You need to wait
