### ISSUE TITLE
Loading images

### ISSUE THREAD

**Issue by HangingWithCMM** [TurboWarp/extensions#386]
When using the extension: https://extensions.turbowarp.org/penplus.js you have to run the "Stamp the images from url:" block twice for the image to be shown, if you run it once it just shows a blue block.

**Comment by David-Orangemoon** [comment]
It's because it replace the default rendering pipeline for scratch

**Comment by David-Orangemoon** [comment]
This will be fixed once I get to working on p+ again

**Comment by GarboMuffin** [comment]
Closing as a duplicate of #226, which will be fixed in V6
