### ISSUE TITLE
Some extension may need explanations if possible

### ISSUE THREAD

**Issue by MilkWithCereal** [TurboWarp/extensions#390]

**Comment by NekoDev-cyber** [comment]
In a way to explain how some extensions work.

**Comment by True-Fantom** [comment]
Could you specify for which ones?

**Comment by NekoDev-cyber** [comment]
> Could you specify for which ones?

Tween

That one 2D shapes one 
that is compatible with the pen.

That's all I remember so far.

**Comment by idoinfactexist** [comment]
the api and networking ones probably, not everyone knows how those work

**Comment by Shaan-Coding** [comment]
> the api and networking ones probably, not everyone knows how those work

There is a documentation on CloudLink incase your wondering.
https://hackmd.io/@MikeDEV/HJiNYwOfo#Scratch-Client
https://hackmd.io/@MikeDEV/SywNTBqRD
