### ISSUE TITLE
(Idea) NFC Tag Reader extension

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/extensions#392]
It would be great to create an extension capable of reading an NFC tag and making it interact with the game (a bit like Nintendo's amiibo, so to speak). It would be great to use especially on smartphones, considering that many phones now have an NFC tag reader/writer and it wouldn't be a bad idea. I know this is a bit of an unusual request and one that probably won't matter to many, but I really would like to be able to do this to create my own figurines out of clay from my games and interface with them.

**Comment by lopste** [comment]
The [Web NFC API](https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API) is only supported on Android mobile browsers and doesn't seem fit to implement right now. It may be neat to take a crack at it, but I don't have any androids.

**Comment by GarboMuffin** [comment]
exists now
