### ISSUE TITLE
Extension bug

### ISSUE THREAD

**Issue by TONYflare123** [TurboWarp/extensions#394]
_Originally posted by @DT-is-not-available in https://github.com/TurboWarp/extensions/issues/207#issuecomment-1459068146_

Pen extension does not work beyond the actual stage, please fix that

**Comment by DT-is-not-available** [comment]
Not sure how I would, the pen layer and texture is the size of the stage. I'll look into this nonetheless.

**Comment by Scratchfangs** [comment]
Duplicate of https://github.com/TurboWarp/extensions/issues/348?

**Comment by GarboMuffin** [comment]
Merging into https://github.com/TurboWarp/extensions/issues/930
