### ISSUE TITLE
Button Utilities

### ISSUE THREAD

**Issue by Pizzalover4783** [TurboWarp/extensions#400]
One thing that could be pretty useful is an extension that interacts with the buttons of a project (green flag, stop, pause, fullscreen).
I've made mockups of some of the blocks I'd like to see from this extension.
![scratchblocks (1)](https://github.com/TurboWarp/extensions/assets/130517217/bfffaa3b-c568-45f7-9597-3fffb21c5fd2)
![scratchblocks (2)](https://github.com/TurboWarp/extensions/assets/130517217/53395fc2-3d93-4ff7-af19-3a935bac94d0)
![scratchblocks (3)](https://github.com/TurboWarp/extensions/assets/130517217/c4deeddc-148c-4eb0-b4cf-e20953a1b61f)
![scratchblocks (4)](https://github.com/TurboWarp/extensions/assets/130517217/817ea4c2-6494-4030-90a0-fdd611df84fc)
![scratchblocks (6)](https://github.com/TurboWarp/extensions/assets/130517217/70e96ba6-d551-415c-adfe-bca4ecc3aa09)
![scratchblocks (12)](https://github.com/TurboWarp/extensions/assets/130517217/bcb975bf-55bc-406f-b8f9-261ad6200027)
![scratchblocks (7)](https://github.com/TurboWarp/extensions/assets/130517217/a9d08020-9ff1-49dc-8f76-f7102fae550a)
![scratchblocks (8)](https://github.com/TurboWarp/extensions/assets/130517217/0b0f2714-7895-4fd8-82c1-a7b9bda4850c)
![scratchblocks (5)](https://github.com/TurboWarp/extensions/assets/130517217/3b2aaead-b19c-476f-9908-279606940271)
![scratchblocks (9)](https://github.com/TurboWarp/extensions/assets/130517217/5d930f73-ac1d-4876-a822-e60c7f35151c)
![scratchblocks (10)](https://github.com/TurboWarp/extensions/assets/130517217/bbf646ab-66eb-43bf-92fd-6a266f7f24e9)
![scratchblocks (11)](https://github.com/TurboWarp/extensions/assets/130517217/d59552af-f8ce-4dd7-ac5a-4d1f8b0fd76f)

**Comment by TheShovel** [comment]
I'm going to try and add most of these in ShovelUtils since it already has the Green Flag block.

**Comment by Pizzalover4783** [comment]
Yeah, there is already a block like that in a couple of extensions. It just fit the theme well enough not to include.

**Comment by True-Fantom** [comment]
Perhaps this can also be included in the "interface"
https://github.com/TurboWarp/extensions/issues/367#issuecomment-1528724856

**Comment by idoinfactexist** [comment]
a block that locks you into fullscreen when the project is packaged would be good

**Comment by Cbr2011** [comment]
this can be useful.

**Comment by JeremyGamer13** [comment]
pause blocks wouldnt be possible (if it means the pause button that the addon adds to the bar) because it doesnt allow any code to run while paused
allowing the pause blocks to be excused from that pause would make it so games can ignore the pause button & would probably annoy the user

**Comment by Pizzalover4783** [comment]
Yeah but it'd make pause menus easier to make

**Comment by CST1229** [comment]
> Yeah but it'd make pause menus easier to make

I'd say for pause menus, a "deactivate/activate sprite ()" block would be better.

**Comment by GarboMuffin** [comment]
Control Controls did most of this
