### ISSUE TITLE
About unsandboxed custom extensions

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/extensions#406]
How to obtain and modify variables and lists in unsandboxed custom extensions

**Comment by GarboMuffin** [comment]
```js
Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('variable name').value = 3;
Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('list name', 'list').value = [1, 2, 3];
```

**Comment by qxsck** [comment]
> 

Is there a method to obtain the names of all variables and lists?

**Comment by qxsck** [comment]
> 从根本上说，它只是
> 
> ```js
> Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('variable name').value = 3;
> Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('list name', 'list').value = [1, 2, 3];
> ```
> 
> 您将不得不添加额外的逻辑来处理变量不存在等。

Is there a method to obtain the names of all variables and lists?

**Comment by GarboMuffin** [comment]
you can find the information you desire in `.variables` on either the stage (global variables) or any other target (local variables)

```js
console.log(Scratch.vm.runtime.getTargetForStage().variables)
```

**Comment by qxsck** [comment]
> fundamentally it's just
> 
> ```js
> Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('variable name').value = 3;
> Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('list name', 'list').value = [1, 2, 3];
> ```
> 
> you will have to add extra logic for dealing with when the variable does not exist etc.
After modifying the list using this method,need to hide and then display the list to see if the modified list.

**Comment by qxsck** [comment]
> > fundamentally it's just
> > ```js
> > Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('variable name').value = 3;
> > Scratch.vm.runtime.getTargetForStage().lookupVariableByNameAndType('list name', 'list').value = [1, 2, 3];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you will have to add extra logic for dealing with when the variable does not exist etc.

After modifying the list using this method,need to hide and then display the list to see if the modified list.
