### ISSUE TITLE
We need more reviewers

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#41]
In order for unsandboxed extensions to thrive, we're going to need more people involved in reviewing the extensions. Having everything be bottlenecked on me will not scale.

**Comment by showierdata9978** [comment]
i will watch the repo (everything ), and help with this

**Comment by softedco** [comment]
I can provide help, I can do some review, discuss issues, suggest code, just what I've been doing. The only problem is I'm still getting familiar with scratch's internals and vm, so I can't _really_ review something that is closely related to it.

**Comment by Cbr2011** [comment]
I'll help. however I'm not available most of the time FYI

**Comment by OeildeLynx31** [comment]
I can help too. I am familiar with JS and I already developed some extensions. I am actually working on adacraft, but I can help and correct extension.

**Comment by Martinelplayz** [comment]
can i review?

**Comment by Dy-tech** [comment]
I can help!

**Comment by GarboMuffin** [comment]
There is no need to proclaim yourself as a helper. If you want to help, then do things like test extensions and report any issues, etc. That's how you can actually help.

**Comment by Cbr2011** [comment]
ah

**Comment by OeildeLynx31** [comment]
> There is no need to proclaim yourself as a helper. If you want to help, then do things like test extensions and report any issues, etc. That's how you can actually help.

Ok. I will do it.

**Comment by IonMakesGarbage** [comment]
me

**Comment by n-d-v** [comment]
you could make a system where there's a queue for the custom extensions, and all of the custom extensions that are going to get in the queue get checked by some algorithm before letting it in the queue, and once the extension becomes first in the queue, then it gets checked by you and gets uploaded. this should make it so that there are less extensions being moderated by you, as they should have been catched by the algorithm or AI (whatever you want to use). and if you find one that didn't get moderated by the AI correctly, then you can just improve the algorithm and maybe add the extension hash to a blacklist.
And optionally, you can make another section in the extension area saying "Potentially dangerous extensions that are currently being reviewed" which will show all of the extensions that are in the queue and passed the AI test, and will be reviewed by you and the other moderators if there are

**Comment by Dy-tech** [comment]
> you could make a system where there's a queue for the custom extensions, and all of the custom extensions that are going to get in the queue get checked by some algorithm before letting it in the queue, and once the extension becomes first in the queue, then it gets checked by you and gets uploaded. this should make it so that there are less extensions being moderated by you, as they should have been catched by the algorithm or AI (whatever you want to use). and if you find one that didn't get moderated by the AI correctly, then you can just improve the algorithm and maybe add the extension hash to a blacklist. And optionally, you can make another section in the extension area saying "Potentially dangerous extensions that are currently being reviewed" which will show all of the extensions that are in the queue and passed the AI test, and will be reviewed by you and the other moderators if there are

Can you even do that in github?

**Comment by n-d-v** [comment]
> > you could make a system where there's a queue for the custom extensions, and all of the custom extensions that are going to get in the queue get checked by some algorithm before letting it in the queue, and once the extension becomes first in the queue, then it gets checked by you and gets uploaded. this should make it so that there are less extensions being moderated by you, as they should have been catched by the algorithm or AI (whatever you want to use). and if you find one that didn't get moderated by the AI correctly, then you can just improve the algorithm and maybe add the extension hash to a blacklist. And optionally, you can make another section in the extension area saying "Potentially dangerous extensions that are currently being reviewed" which will show all of the extensions that are in the queue and passed the AI test, and will be reviewed by you and the other moderators if there are
> 
> Can you even do that in github?

If you are able to automatically edit files or just have it done manually, then yes, it should be possible

(also, now that i have more knowledge of how to make extensions, you could make it so that the "Potentially dangerous extensions" thing includes sandboxed extensions)

**Comment by The-Best-Codes** [comment]
I will review extensions for you! I'd love to! I use turbowarp.org a lot, even though I am a web developer (I love the art editor and ease of use for animating). Just let me know and I'd be glad to do it.

**Comment by CST1229** [comment]
> I will review extensions for you! I'd love to! I use turbowarp.org a lot, even though I am a web developer (I love the art editor and ease of use for animating). Just let me know and I'd be glad to do it.

> There is no need to proclaim yourself as a helper. If you want to help, then do things like test extensions and report any issues, etc. That's how you can actually help.

\- https://github.com/TurboWarp/extensions/issues/41#issuecomment-1575246381
