### ISSUE TITLE
<is(Something Wrong)(Title Case v)?> error

### ISSUE THREAD

**Issue by Ottiotta** [TurboWarp/extensions#413]
<img width="290" alt="image" src="https://github.com/TurboWarp/extensions/assets/124516852/67d740e8-a528-42c2-88e2-accabef5a0bd">
If there is more than one word, it will return false, no matter what you give them in the input, even if it is converted by the block in the same extension

**Comment by CST1229** [comment]
The block is just entirely broken.
![image](https://github.com/TurboWarp/extensions/assets/68464103/42fad3da-614d-4d64-b1fc-a76d0821e4f1)
