### ISSUE TITLE
Microphone Recording Extension

### ISSUE THREAD

**Issue by Pizzalover4783** [TurboWarp/extensions#422]
I've made mockups of some blocks I'd like to see for an extension that records input from your microphone
![scratchblocks (13)](https://github.com/TurboWarp/extensions/assets/130517217/d6923461-9cf0-4fb5-9f57-c2b407172c15)
![scratchblocks (17)](https://github.com/TurboWarp/extensions/assets/130517217/f537f405-b553-499b-a405-8ce7051d8e45)
![scratchblocks (14)](https://github.com/TurboWarp/extensions/assets/130517217/ce73f549-4c05-43b7-8315-f66ce62d5616)
![scratchblocks (15)](https://github.com/TurboWarp/extensions/assets/130517217/214d5c50-4016-4fea-a4e9-121b5177602c)
![scratchblocks (16)](https://github.com/TurboWarp/extensions/assets/130517217/3d3bfbf9-4ea2-444c-ab6b-24b6263cbb3c)

**Comment by SIPC** [comment]
I can try!
