### ISSUE TITLE
Please make a movie/video extention

### ISSUE THREAD

**Issue by Zigotonlover08** [TurboWarp/extensions#431]
Please make a movie/video extention, it would been very useful to add and play video files, you can add cutscenesfor your games without using 9999999 costumes just to add a video. This is my request/suggestion

**Comment by idoinfactexist** [comment]
FINALLY!!

**Comment by gomiigg** [comment]
how would this work though

**Comment by TheShovel** [comment]
> > This is possible since it is possible to render videos to canvas. You could just start a hiden video player and take the current frame as a sprite costume skin. The audio would naturally come from the video player.
> 
> Ok great, are you going to make it?

Sadly, I don't have time.

**Comment by Zigotonlover08** [comment]
> > > This is possible since it is possible to render videos to canvas. You could just start a hiden video player and take the current frame as a sprite costume skin. The audio would naturally come from the video player.
> > 
> > 
> > Ok great, are you going to make it?
> 
> Sadly, I don't have time.

Maybe next time?

**Comment by lopste** [comment]
This seems fun to take a crack at. I'll try to actually read documentation on Scratch internals this time. What would be better? Replacing the sprite or putting a separate video in?

**Comment by Zigotonlover08** [comment]
> This seems fun to take a crack at. I'll attempt to read the documentation on Scratch internals this time. What would be better? Replacing the sprite or putting a separate video in? Additionally, would you load the video from a link? That seems the most plausible but poses a few additional questions.

Idk maybe replacing sprite

**Comment by LukeManiaStudioss** [comment]
Replacing the sprite would allow for more flexibility with how it's rendered on the stage, because you could just apply any motion blocks onto the sprite as opposed to having arbitrary blocks to move the video. That's how ScratchLab's "Animated Text" worked.

**Comment by Zigotonlover08** [comment]
> Replacing the sprite would allow for more flexibility with how it's rendered on the stage, because you could just apply any motion blocks onto the sprite as opposed to having arbitrary blocks to move the video. That's how ScratchLab's "Animated Text" worked.

Sounds cool, i can't wait for someone to make it a reality

**Comment by Martinelplayz** [comment]
this needs to happen so bad! i wish there was a way to store mp4 files in projects! even better, to load straight from yt videos. i could upload a game cutscene as unlisted and have it play with the extension. or even better i bet i could use it with an active online multiplayer game whenever there is some sort of special event going on. i could use it with the cloudlink extension to update the video being played for everyone to see at the same time.

**Comment by Zigotonlover08** [comment]
> this needs to happen so bad! i wish there was a way to store mp4 files in projects! even better, to load straight from yt videos. i could upload a game cutscene as unlisted and have it play with the extension. or even better i bet i could use it with an active online multiplayer game whenever there is some sort of special event going on. i could use it with the cloudlink extension to update the video being played for everyone to see at the same time.

Fr

**Comment by ClaytonTDM** [comment]
@TheShovel ?

**Comment by IonMakesGarbage** [comment]
gandi ide has media utils. make a turbowarp port and i think it would work fine. let videos run from a url.
run video (link) at (x) (y) at resolution (x) (y) 
the first one allows inputs from websites like youtube. x and y determines the location that the bottom left corner of the video will be and the last 2 determine the resolution. if left blank they will match the size of the stage: 480x360 by default.
