### ISSUE TITLE
Suggestion: SNES Mode 7 Extension

### ISSUE THREAD

**Issue by Meehdrescher** [TurboWarp/extensions#440]
The SNES has 8 graphics modes from 0 to 7, and the 7. mode is used in games like Super Mario Kart or F-Zero to create the illusion of a 3D world by rotating and skewing a 2D sprite. Larger RPG games use this mode too.
![grafik](https://github.com/TurboWarp/extensions/assets/83909483/af2290dd-33e8-4157-9cf1-7f9847ac2eec)
![grafik](https://github.com/TurboWarp/extensions/assets/83909483/1e6aded5-68e8-4267-a056-a3075f737974)
![grafik](https://github.com/TurboWarp/extensions/assets/83909483/6d5b9c0f-2be4-4227-a0a9-76ec67e8317d)
(Images are from an emulator with HD rendering similar to high quality pen in TW)

**Comment by GalacticCoder922** [comment]
I don't get it.

**Comment by GarboMuffin** [comment]
if you don't get it then don't comment...

**Comment by TheShovel** [comment]
This would be cool, but I think we straight up need a 3D rendering extension.
Replacing a sprites costume with the output of something like Three.js should be enough. I have no experience with Three.js, tho. Someone who knows what they are doing should probably give it a shot.

**Comment by echoless3484** [comment]
This would be freaking awesome

**Comment by David-Orangemoon** [comment]
> This would be cool, but I think we straight up need a 3D rendering extension. Replacing a sprites costume with the output of something like Three.js should be enough. I have no experience with Three.js, tho. Someone who knows what they are doing should probably give it a shot.

I mean old Pen+ could do this effect pretty well it's just that that version was inefficient.

**Comment by Meehdrescher** [comment]
>> I mean old Pen+ could do this effect pretty well it's just that that version was inefficient.
Do you happen to have access to the old version? I'd like to try it out.

**Comment by Meehdrescher** [comment]
> I mean old Pen+ could do this effect pretty well it's just that that version was inefficient.

Do you happen to have access to the old version? I'd like to try it out.

**Comment by David-Orangemoon** [comment]
It's on the gallery

**Comment by Meehdrescher** [comment]
> It's on the gallery
I just went through all the different versions and I can't seem to find the one that allegedly has the mode 7 effect.

**Comment by David-Orangemoon** [comment]
You are going to have to make it somewhat manually by just having a simple
3d projection.

**Comment by Meehdrescher** [comment]
> You are going to have to make it somewhat manually by just having a simple 3d projection.

That would work and I've already managed to do that, but it's resource intensive and the UV mapping is weird.

**Comment by David-Orangemoon** [comment]
> > You are going to have to make it somewhat manually by just having a simple 3d projection.
> 
> That would work and I've already managed to do that, but it's resource intensive and the UV mapping is weird.

Yeah I'm trying to fix the resource issue.

**Comment by Meehdrescher** [comment]
I strongly suggest that you fix the UVs for triangles, since with the
simple 3d projection, it can cause PSX-like major texture warping issues
which cannot be resolved without modifying the extension (which I have no
clue how to do)...
Anyways, here is a site that explains why it occurs:
http://graphics.stanford.edu/courses/cs248-98-fall/Lectures/lecture18/slides/walk014.html

Am Fr., 26. Mai 2023 um 23:18 Uhr schrieb Obvious Alex C <
***@***.***>:

**Comment by David-Orangemoon** [comment]
That is where the depth block comes in handy. It's going to be renamed to
corner pinch.

**Comment by Meehdrescher** [comment]
So I set the depth to the projected Z coordinate of the point?

Am Sa., 27. Mai 2023 um 15:50 Uhr schrieb Obvious Alex C <
***@***.***>:

> That is where the depth block comes in handy. It's going to be renamed to
> corner pinch.
>

**Comment by David-Orangemoon** [comment]
Yeah

**Comment by SharkPool-SP** [comment]
can be replicated now with Pen+ V7 and or Simple3D :)
