### ISSUE TITLE
Sensing + voice recognition not working in Chromium browsers

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#441]
![image](https://github.com/TurboWarp/extensions/assets/68913917/cfc289c0-1e2d-403f-83c6-8e8975d8493e)
 I tried to search on Google for a fix, but I can't seem to find any good answers.

**Comment by David-Orangemoon** [comment]
> ![image](https://user-images.githubusercontent.com/68913917/239685960-cfc289c0-1e2d-403f-83c6-8e8975d8493e.png) I tried to search on Google for a fix, but I can't seem to find any good answers.

Its a google chrome only thing since that is the *ONE* browser to support it. Sorry I couldn't be of much assistance. I just thought it would be a fun feature to add.

**Comment by David-Orangemoon** [comment]
Also it only seems available for HTTPS connections due to web RTC

**Comment by TheShovel** [comment]
Ah alright, so this is a browser dependent thing. Closing the issue since not much can be done.
