### ISSUE TITLE
Read data/images from directories when compiled to desktop

### ISSUE THREAD

**Issue by gomiigg** [TurboWarp/extensions#444]
If there was an extension or addon similar to the Files extension that could allow data like .json to be read from anywhere INSIDE the project folder, it could allow for clearer organization.

Things that could be made easier if stored inside a directory instead of a global list inside the project:
- Level data (good for tile based platformers with lots of levels)
- Keybinds and other settings
- Achievments or unlockables
- Dialogue or other NPC/cutscene data
- Decreased loading time now that less lists are loaded inside the project

Here's an example of what it could look like, used in that one game about the guy with blue hair
![image](https://github.com/TurboWarp/extensions/assets/91437192/4337c2e7-21f9-4fcb-b233-15b8410fba26)

I don't know if this could create any security issues, maybe just restrict reading and writing to inside the project folder

**Comment by TheShovel** [comment]
You can just use the fetch extension. If you want a file directly from the same directory, just put the file name + extension (level.json for example) in the fetch extension block. Same with folders. Just do `foldername/level.json` .

**Comment by TheShovel** [comment]
Here is a explanation for how it works.
https://www.w3schools.com/jsref/api_fetch.asp

**Comment by gomiigg** [comment]
> You can just use the fetch extension. If you want a file directly from the same directory, just put the file name + extension (level.json for example) in the fetch extension block. Same with folders. Just do `foldername/level.json` .

That makes more sense. I originally assumed that the fetch extension was ONLY for online content but I guess it can be used for local files as well. Thanks!

**Comment by TheShovel** [comment]
By the way, the fact that you used Friday Night Funkin as an example makes me feel like you want to make something like it with TurboWarp. I already did something like this if you need a starting point :)
I stopped working on it since I lost interest.
https://github.com/TheShovel/Funkin-on-the-web

**Comment by gomiigg** [comment]
Well, It was the only example I could pull up quickly. What I meant was something more like this:
![image](https://github.com/TurboWarp/extensions/assets/91437192/7a2e9d90-60bb-438d-9dbf-dd735bc1c463)

(My save file for Pizza Tower.)

**Comment by TheShovel** [comment]
Ah, alright.
You can close the issue now, by the way!

**Comment by gomiigg** [comment]
One last thing, TW can read .ini files effectively, right? If I implement saves into a game I want to see if i can make one just like this.

**Comment by TheShovel** [comment]
Of course! It's just text after all. You can fetch anything.

**Comment by CST1229** [comment]
> One last thing, TW can read .ini files effectively, right? If I implement saves into a game I want to see if i can make one just like this.

There is no INI parser extension AFAIK, but you could always just implement one yourself.

**Comment by Gaypatapon** [comment]
> Of course! It's just text after all. You can fetch anything.

can it also fetch audio/image files?

**Comment by fast-food-inception** [comment]
> > Of course! It's just text after all. You can fetch anything.
> 
> can it also fetch audio/image files?

yes, any file

**Comment by Meehdrescher** [comment]
> You can just use the fetch extension. If you want a file directly from the same directory, just put the file name + extension (level.json for example) in the fetch extension block. Same with folders. Just do `foldername/level.json` .

Sorry for the bump, but I didn't want to create another issue on this since there is already so many of them open as of right now.
Does this still work for you? I just tried it with packaged versions of a test project and it didn't do anything whatsoever, no matter the type of package, I tried Electron Win32+64, Win64 and plain HTML with a sample text file in a folder called "mods", then tried it with the text file being moved into the root folder, still nothing...
