### ISSUE TITLE
Steamworks API Extension

### ISSUE THREAD

**Issue by NDM1574** [TurboWarp/extensions#457]
Like Newgrounds, Itch, and GameJolt API extensions, have one for Steamworks, pretty sure this would completely bypass piracy too since you can look for a username on launch of the project.

**Comment by Alestore** [comment]
I would really need and love that. I currently use a method that utilizes Steamworks.js in the Electron packaged project to run the Steam Overlay and stuff.

**Comment by NDM1574** [comment]
> I would really need and love that. I currently use a method that utilizes Steamworks.js in the Electron packaged project to run the Steam Overlay and stuff.

Ah, yeah i'd hope for a way more extensive system so we can add workshop support, achievements, and more

**Comment by Alestore** [comment]
> > I would really need and love that. I currently use a method that utilizes Steamworks.js in the Electron packaged project to run the Steam Overlay and stuff.
> 
> Ah, yeah i'd hope for a way more extensive system so we can add workshop support, achievements, and more

You can already add and use achievements with my method. It works.

**Comment by echoless3484** [comment]
> > > I would really need and love that. I currently use a method that utilizes Steamworks.js in the Electron packaged project to run the Steam Overlay and stuff.
> > 
> > 
> > Ah, yeah i'd hope for a way more extensive system so we can add workshop support, achievements, and more
> 
> You can already add and use achievements with my method. It works.

Would you mind providiing a text guide on how to do your method? it sounds awesome

**Comment by echoless3484** [comment]
> > > I would really need and love that. I currently use a method that utilizes Steamworks.js in the Electron packaged project to run the Steam Overlay and stuff.
> > 
> > 
> > Ah, yeah i'd hope for a way more extensive system so we can add workshop support, achievements, and more
> 
> You can already add and use achievements with my method. It works.

I saw your like, if you do end up making a guide please let me know once you do!

**Comment by Alestore** [comment]
> > > > I would really need and love that. I currently use a method that utilizes Steamworks.js in the Electron packaged project to run the Steam Overlay and stuff.
> > > 
> > > 
> > > Ah, yeah i'd hope for a way more extensive system so we can add workshop support, achievements, and more
> > 
> > You can already add and use achievements with my method. It works.
> 
> I saw your like, if you do end up making a guide please let me know once you do!

Of course, I will do it today

**Comment by Alestore** [comment]
1. Open your project from [TurboWarp](https://turbowarp.org/editor).

2. Create an `☁ eval` variable to be able to activate the JavaScript needed for achievements.

3. Open [Steamworks](https://partner.steamgames.com/dashboard) on a web browser and open the corresponding page of your application, then choose "Edit Steamworks settings" and choose from the menu "Stats and achievements", then choose "Achievements".

4. Create the achievements you want and get the API Name of your achievement (In my case, I've chosen TUTORIAL_COMPLETE as the API Name for this achievement). You can also add a name, icon and description, but remember that you can change these settings at any time.

![image](https://github.com/TurboWarp/extensions/assets/82514000/cd20adae-51d5-40a2-8bc5-f308989d976a)

5. Now go back to your TurboWarp project and set a point where to activate the achievement (for example, after completing a level, activate the corresponding achievement).

6. To do this, you will need to set the `☁ eval` variable to `client.achievement.activate('YOUR_API_NAME_ACHIEVEMENT')`
Inside the parenthesis, replace the word with the API Name of your achievement you created.

7. You're almost done! In order to try achievements, you need to add Steamworks.js and the Steam Overlay within your packaged project. To do this, follow the guide you find here: https://github.com/TurboWarp/packager/issues/503

Huge thanks to @GarboMuffin for helping me with this!

**Comment by Alestore** [comment]
@echoless3484 I've done it, contact me or leave a comment if you need more help!

**Comment by echoless3484** [comment]
> 1. Open your project from [TurboWarp](https://turbowarp.org/editor).
> 
> 2. Create an `☁ eval` variable to be able to activate the JavaScript needed for achievements.
> 
> 3. Open [Steamworks](https://partner.steamgames.com/dashboard) on a web browser and open the corresponding page of your application, then choose "Edit Steamworks settings" and choose from the menu "Stats and achievements", then choose "Achievements".
> 
> 4. Create the achievements you want and get the API Name of your achievement (In my case, I've chosen TUTORIAL_COMPLETE as the API Name for this achievement). You can also add a name, icon and description, but remember that you can change these settings at any time.
> 
> ![image](https://github.com/TurboWarp/extensions/assets/82514000/cd20adae-51d5-40a2-8bc5-f308989d976a)
> 
> 5. Now go back to your TurboWarp project and set a point where to activate the achievement (for example, after completing a level, activate the corresponding achievement).
> 
> 6. To do this, you will need to set the `☁ eval` variable to `client.achievement.activate('YOUR_API_NAME_ACHIEVEMENT')`
> Inside the parenthesis, replace the word with the API Name of your achievement you created.
> 
> 7. You're almost done! In order to try achievements, you need to add Steamworks.js and the Steam Overlay within your packaged project. To do this, follow the guide you find here: https://github.com/TurboWarp/packager/issues/503
> 
> Huge thanks to @GarboMuffin for helping me with this!

Thank you both so much! Using this method but doing something different, could I in theory use this for workshop support?

**Comment by Alestore** [comment]
> > 1. Open your project from [TurboWarp](https://turbowarp.org/editor).
> > 
> > 2. Create an `☁ eval` variable to be able to activate the JavaScript needed for achievements.
> > 
> > 3. Open [Steamworks](https://partner.steamgames.com/dashboard) on a web browser and open the corresponding page of your application, then choose "Edit Steamworks settings" and choose from the menu "Stats and achievements", then choose "Achievements".
> > 
> > 4. Create the achievements you want and get the API Name of your achievement (In my case, I've chosen TUTORIAL_COMPLETE as the API Name for this achievement). You can also add a name, icon and description, but remember that you can change these settings at any time.
> > 
> > ![image](https://github.com/TurboWarp/extensions/assets/82514000/cd20adae-51d5-40a2-8bc5-f308989d976a)
> > 
> > 5. Now go back to your TurboWarp project and set a point where to activate the achievement (for example, after completing a level, activate the corresponding achievement).
> > 
> > 6. To do this, you will need to set the `☁ eval` variable to `client.achievement.activate('YOUR_API_NAME_ACHIEVEMENT')`
> > Inside the parenthesis, replace the word with the API Name of your achievement you created.
> > 
> > 7. You're almost done! In order to try achievements, you need to add Steamworks.js and the Steam Overlay within your packaged project. To do this, follow the guide you find here: https://github.com/TurboWarp/packager/issues/503
> > 
> > Huge thanks to @GarboMuffin for helping me with this!
> 
> Thank you both so much! Using this method but doing something different, could I in theory use this for workshop support?

I don't really know how this would work, but practically yes. Once you have Steamworks.js, you have Steam Support.

**Comment by LukeManiaStudioss** [comment]
I'll see what I can do about getting an actual Steamworks API extension onto TurboWarp, because it seems easier than I would've expected it to be lol.

Keep in mind that 1 of the biggest hurdles about making TurboWarp extensions for APIs like this is coming up with a block palette that makes sense and fills every need, without straying too far away from the Scratch block-style and having too many arguments inside of 1 block. I think if I make it the first version might not have workshop content _just_ yet, since that'll take more time to get right.

**Comment by Alestore** [comment]
> I'll see what I can do about getting an actual Steamworks API extension onto TurboWarp, because it seems easier than I would've expected it to be lol.
> 
> Keep in mind that 1 of the biggest hurdles about making TurboWarp extensions for APIs like this is coming up with a block palette that makes sense and fills every need, without straying too far away from the Scratch block-style and having too many arguments inside of 1 block. I think if I make it the first version might not have workshop content _just_ yet, since that'll take more time to get right.

Super interested in that. I wonder if it will be possible to also add in-app purchases in it. It would be really awesome!

**Comment by echoless3484** [comment]
> I'll see what I can do about getting an actual Steamworks API extension onto TurboWarp, because it seems easier than I would've expected it to be lol.
> 
> Keep in mind that 1 of the biggest hurdles about making TurboWarp extensions for APIs like this is coming up with a block palette that makes sense and fills every need, without straying too far away from the Scratch block-style and having too many arguments inside of 1 block. I think if I make it the first version might not have workshop content _just_ yet, since that'll take more time to get right.

Sick, if you need help coming up with a block pallete I'm here, I'm in a Harvard course learning all the different important languages and hopefully by the time I'm done I could help a bit more, but my peers have said I'm quite nice at making easy to use UI, so I'm all up to help even if code is not my strong suite

**Comment by DD98GAMES** [comment]
It's still hard for me :(

**Comment by softedco** [comment]
![image](https://github.com/TurboWarp/extensions/assets/100989385/7d943de9-c89b-4b5c-9ba8-a6ab0e05ce7a)

**Comment by SharkPool-SP** [comment]
this was added

**Comment by NDM1574** [comment]
I feel like it wasn't fully completed, we still don't have Workshop support.
