### ISSUE TITLE
Custom blocks+ idea

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/extensions#473]
I think a very useful way to improve custom blocks is if we could have custom input blocks, and boolean blocks. There should also be a return block added like in Javascript. It look something like this.
![image](https://github.com/TurboWarp/extensions/assets/131917462/39177a2c-9a3a-4127-98da-ce49fe49c754)

**Comment by David-Orangemoon** [comment]
I might do this.

**Comment by echoless3484** [comment]
custom reporters and global custom blocks too

**Comment by Martinelplayz** [comment]
> I might do this.

#493

**Comment by David-Orangemoon** [comment]
This is where some vm hackery comes in.

**Comment by GarboMuffin** [comment]
https://experiments.turbowarp.org/return/editor
