### ISSUE TITLE
webview extensions

### ISSUE THREAD

**Issue by glebik228** [TurboWarp/extensions#476]
Maybe we need to make an extension in which you can watch web pages Instead of the background there will be a web page (looks like video sensing). Blocks - show page, hide page(close) and url of the page. P.S: I tried to create extension, but idk how to do this

 
![scratchblocks](https://github.com/TurboWarp/extensions/assets/127509426/79c7148e-3388-468f-be7d-07acd504288f)

**Comment by OeildeLynx31** [comment]
How to create an extension: https://docs.turbowarp.org/development/extensions/introduction

**Comment by glebik228** [comment]
yes, I tried to make an extension on this topic, but it's difficult for me😑

**Comment by OeildeLynx31** [comment]
Yes, it's true. But I can do it. I think I will do the extension.

**Comment by GarboMuffin** [comment]
We added an "Iframe" extension
