### ISSUE TITLE
60 fps delta timing

### ISSUE THREAD

**Issue by Azulcat** [TurboWarp/extensions#478]
Please help how can i make deltatiming?

**Comment by penta-quark-neutro** [comment]
![Captura de pantalla (197)](https://github.com/TurboWarp/extensions/assets/134885702/9fdeb754-a5f2-43fa-b2cc-6bcb78af6f48)
ese es un metodo.

**Comment by Azulcat** [comment]
Sí, pero ¿cómo podemos aplicarlo a otros sprites?

**Comment by penta-quark-neutro** [comment]
la variable ΔT es global y puede ser leido por todo sprite.
dependiendo que se busque al aplicarlo en un tiempo se tiene que multiplicar o dividir.
dividir.
![Captura de pantalla (198)](https://github.com/TurboWarp/extensions/assets/134885702/7bcb9339-cff7-4ae4-9cd3-ccdb7c577804)
aquí vivido la velocidad con el tiempo delta para compensar las diferencias

**Comment by Azulcat** [comment]
ok mañana lo pruebo buenas noches!

**Comment by Martinelplayz** [comment]
ummm english solution please?

**Comment by penta-quark-neutro** [comment]
as you can see the ΔT variable is global and can be read by all sprites.
in that case you can use it to multiply the speed of an object by the delta time.

**Comment by Azulcat** [comment]
I have an acceleration variable should it be applicated forever or just set one time acceleration to / delta?

**Comment by penta-quark-neutro** [comment]
If I understood what you are saying.
The delta time must always be updated and not set only once.
The reason is that you have to be compensating for the difference between the reached frames and the target frames.

**Comment by Azulcat** [comment]
oh ok lemme try that

**Comment by Azulcat** [comment]
it did not work

**Comment by Azulcat** [comment]
https://github.com/TurboWarp/extensions/assets/134739700/2f4e408e-ebb9-45ba-93fe-91ccc86e3b32

**Comment by penta-quark-neutro** [comment]
how is it supposed to work?

**Comment by Azulcat** [comment]
i dunno bru

**Comment by Azulcat** [comment]
i did that but unfortunetly it did not work spped was very different

**Comment by SebasMCYT** [comment]
Try  
![image](https://github.com/TurboWarp/extensions/assets/126848249/7741efd1-e35a-438f-ae3f-884e09ca8e69)

**Comment by penta-quark-neutro** [comment]
This reminds me of a big problem I had with delta times in a game with acceleration.
And I just noticed in your video that you multiply instead of divide.
try to divide.
The method I gave you only works by dividing.
at 60fps it would give 1 output and 30 would give 2.
so you need to divide.
![Captura de pantalla (204)](https://github.com/TurboWarp/extensions/assets/134885702/b0548435-6e0b-4836-8e39-3cd1bcfffab4)

**Comment by Azulcat** [comment]
Yessss i have acceleration in my game

**Comment by Azulcat** [comment]
There is a problem when i set fps to 40 not 60 the game goes crazy

**Comment by penta-quark-neutro** [comment]
Does your game use linear or exponential methods or other types of acceleration?

**Comment by penta-quark-neutro** [comment]
It's really important as things can change how the delta time should be applied.
Linear mapping is like the following.
![_20230531_140446.JPG](https://github.com/TurboWarp/extensions/assets/134885702/c73d1b5c-38c2-4c97-bb20-005578ac5ea5)

![_20230531_140427.JPG](https://github.com/TurboWarp/extensions/assets/134885702/a9e30ab9-20ba-4ede-b206-4dbdfc34225f)

And this is depending on the sine of x. 
![_20230602_151406.JPG](https://github.com/TurboWarp/extensions/assets/134885702/dfa9c57b-7e36-46c8-805d-7e4a6197cfb4)

![_20230602_151351.JPG](https://github.com/TurboWarp/extensions/assets/134885702/fb8e4fbd-f2be-41cc-9f5c-c97ffa62e666)

**Comment by penta-quark-neutro** [comment]
This equation almost maintains the accelerative relationship in sine of x but as you can see it is more difficult than just multiplying.
![_20230602_152238.JPG](https://github.com/TurboWarp/extensions/assets/134885702/7172d5e2-8ab9-4b79-b18d-4408b633d54b)

**Comment by penta-quark-neutro** [comment]
How exactly does your game speedup work in equation form?

**Comment by TONYflashB** [comment]
I guess you should round the value after every 4 frames

**Comment by Azulcat** [comment]
Hi Can you explain by showing an image With scartch code plz

**Comment by Azulcat** [comment]
none of these worked do you guys have any solution

**Comment by penta-quark-neutro** [comment]
If applying delta time to your program is so difficult, you could replace time functions like "wait one second" with a wait-for-frame method.
At 60 fps at runtime.
1 second is 60 frames
0.5 is 30 frames.
You can make a block that waits for N frames instead of time.

**Comment by penta-quark-neutro** [comment]
![_20230712_131039.JPG](https://github.com/TurboWarp/extensions/assets/134885702/522693ad-ea21-4ca9-985f-39a3084cc789)

the move block must always have 0.
That small block will take the number of frames that you indicate.
So, like this one, it will take 30 frames to finish.
Regardless of the execution time or any kind of delay in the program process.

**Comment by Azulcat** [comment]
i'll see

**Comment by Azulcat** [comment]
no work breh

**Comment by penta-quark-neutro** [comment]
just guessing what may or may not work will be difficult.

**Comment by penta-quark-neutro** [comment]
I could try to correct your project so that it works with delta time.

**Comment by GarboMuffin** [comment]
A delta time extension was merged
