### ISSUE TITLE
Duplicate block functionality

### ISSUE THREAD

**Issue by Samq64** [TurboWarp/extensions#48]
There are already blocks from multiple extensions that do the same thing. Something should probably be done about it eventually.

![image](https://user-images.githubusercontent.com/81489795/204049731-88afeb0b-8e6b-413b-b92f-b77a1e28d9dc.png)

**Comment by GarboMuffin** [comment]
It's okay for there to be some duplication. The fetch extension is the preferred way to fetch URLs, but we're not going to tell the Cloudlink people that they need to remove their own fetch block or anything like that.
