### ISSUE TITLE
2 Questions.

### ISSUE THREAD

**Issue by SurvExe1Pc** [TurboWarp/extensions#487]
Sorry for bad title, Never been good at writing titles. (Also first scratch extension)
I have been wanting to submit an extension to the turbowarp gallery, but then I came across the
"//pull/480" pull, and since my extension has AES+RSA encryption in it I was wondering if it would
have the same issue, the comment in question is:

#480 @GarboMuffin 
> the reason the other PR is stalled is because storing the API key inside the project is very scary and will almost definitely cause someone's credit card to be charged for API requests they didn't make. IF possible I would prefer these types of extensions to have some custom UI that they use to ask for the API key rather than storing it in the scripts
[the comment](https://github.com/TurboWarp/extensions/pull/480#issuecomment-1567317890)

So I assume it would apply to the passwords part of the AES encryption, and the private key storage of the RSA encryption, I have also seemed to run into an issue with turbowarp breaking the jsencrypt library when embeded in the function.

(edit):
  linked to comment

**Comment by CST1229** [comment]
I'm pretty sure encryption keys are a different thing (as they don't let you charge people's credit cards by themselves).

**Comment by SurvExe1Pc** [comment]
yeah I know but you could say the same concept applys

**Comment by GarboMuffin** [comment]
Storing the private key inside the project may ruin the point of the encryption depending on what you're doing, however those keys cannot charge credit cards so there is no problemthere

**Comment by SurvExe1Pc** [comment]
so after i check it with eslint I could do a pull request?

**Comment by SurvExe1Pc** [comment]
"on how to do it" i mean to submit the extension sorry for bad clarity
