### ISSUE TITLE
Save file list

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#49]
When saving a list using the file extension like this, the whole list will be on 1 string.
It should save the list on different rows, as many people will try to do that, and be confused.
Also probably should add a load to list block to format it correctly.

**Comment by softedco** [comment]
I believe that would require to change the list reporter's functionality, which would make vanilla turbowarp (without any not scratch compatible extensions) not really compatible with scratch and other mods.

**Comment by TheShovel** [comment]
Not really. You can add a block just for exporting lists, so you wold still be able use the other save normally.
Plus, lists have a invisible character that you can use to create new rows in the file.

**Comment by softedco** [comment]
List reporters do not return items separated with a newline operator

![list1](https://user-images.githubusercontent.com/100989385/204144047-7d35dc62-3f45-4226-a616-bf99be77a882.png) ![list2](https://user-images.githubusercontent.com/100989385/204144066-ee9bf6f8-5249-4e9a-91ba-fc7464578bd4.png)

**Comment by GarboMuffin** [comment]
I think making lists work well will require "open a [.txt] file as [list name]" and "save [list name] as [file.txt]" blocks, which isn't impossible right now, but is a bit of a mess and doesn't work well

**Comment by GarboMuffin** [comment]
leave open until merged

**Comment by GarboMuffin** [comment]
it was merged
