### ISSUE TITLE
Custom block color addon problem

### ISSUE THREAD

**Issue by YogaindoCR** [TurboWarp/extensions#494]
Some of the extension block colors don't follow the custom block color addon theme (Colored on black background) Making the text block hard to read

![Some](https://github.com/TurboWarp/extensions/assets/132117105/dd63b6d2-5a46-4e55-9749-fbfe4c39ce9e)

**Comment by LukeManiaStudioss** [comment]
I can't fix it for every extension, but I'll amend this for a few of my existing extensions if I can

**Comment by CST1229** [comment]
This is probably partially also an issue with the addon.

**Comment by SharkPool-SP** [comment]
was fixed post merge-upstream
