### ISSUE TITLE
An extension for exponentiation and arbitrary log and root bases

### ISSUE THREAD

**Issue by DroneBetter** [TurboWarp/extensions#5]
Have all three as separate blocks beneath the regular arithmetic ones, not as a single configurable one like the abs at the bottom of the operations section.

**Comment by mollthecoder** [comment]
This isn't possible to have it underneath the normal math category. If you gave me a link describing what that is, I could program an extension for you, but extensions are still experimental so I can't guarantee it'll work forever and it may not be exactly what you envision.

**Comment by DroneBetter** [comment]
Full list of all additions I could think of:
- Exponentiation (would be either `()**()` or `()^()`), supporting noninteger/negative indices, instead of having to include the long function in each program.
- Roots (would be `()th root of ()`), could be done by exponentiation to indice 1/(root order) but are more concise this way.
- Logarithms (would be `log () of ()`), can already be done by `ln(input)/ln(base)` but would be more concise this way also.
- Another dropdown operator like the existing one that says `abs ()` by default, for more advanced (but still reasonably common) single-input operations like hyperbolic trigonometry functions, perhaps ones like the Lambert W function.
- A native `set [list] to ()` function as an inverse to list reporters, for setting lists to strings (perhaps optionally specifying delimiter (if left blank, would split each character)), you could set one list to another instead of iterating through elements. Perhaps also insert lists' full contents (not delimitered) into other lists.
- A hash operator (not cryptographically secure) that only intakes strings (because the list reporter exports them to strings) and outputs fixed-length hashes, applications mostly for checking transpositions in chess engines or other permutation-tree searches.
-

**Comment by mollthecoder** [comment]
> Full list of all additions I could think of:
> 
> * Exponentiation (would be either `()**()` or `()^()`), supporting noninteger/negative indices, instead of having to include the long function in each program.
> * Roots (would be `()th root of ()`), could be done by exponentiation to indice 1/(root order) but are more concise this way.
> * Logarithms (would be `log () of ()`), can already be done by `ln(input)/ln(base)` but would be more concise this way also.
> * Another dropdown operator like the existing one that says `abs ()` by default, for more advanced (but still reasonably common) single-input operations like hyperbolic trigonometry functions, perhaps ones like the Lambert W function.
> * A native `set [list] to ()` function as an inverse to list reporters, for setting lists to strings (perhaps optionally specifying delimiter (if left blank, would split each character)), you could set one list to another instead of iterating through elements. Perhaps also insert lists' full contents (not delimitered) into other lists.
> * A hash operator (not cryptographically secure) that only intakes strings (because the list reporter exports them to strings) and outputs fixed-length hashes, applications mostly for checking transpositions in chess engines or other permutation-tree searches.

Okay, I might do something like this in a few days, but unfortunatley I am currently caught up in school. I hope you can understand.

**Comment by mollthecoder** [comment]
For a while I forgot about this but came across it again and started coding it. First I did exponents. That was very easy. But, I'm only a middle schooler and I don't really understand all that math. As for the native "set [list] to ()" it's not really possible to do. Not yet. As for the hash operator, I could do that. In the end I could only do two of these, but I will look into the math thing more and possibly learn some of this math stuff.

**Comment by infernostars** [comment]
Are you still looking for this, @DroneBetter ? I could probably do most of those

**Comment by GarboMuffin** [comment]
Follow https://github.com/TurboWarp/scratch-gui/issues/633. This should probably make it into one of the "utilities"-like ones that will eventually be added.

**Comment by DroneBetter** [comment]
More ideas from having used Python now [quite a bit](https://github.com/DroneBetter/ChessPieceVision/blob/main/tablebase%20vision.py):
- Prevent converting large integers to floats, store them precisely like Python does (perhaps difficult but necessary for the next part)
- Add bitwise operators and floordiv operator (beneath modulo in the block pane)
- Inline ternary operator as reporter block (ie. `(() if <> else ())`)
- Zero-indexed mode (this would break compatibility with Scratch, but so would most of these ideas)
- Perhaps walrus operators, break statements and for-elses but these are only useful for minor conciseness
- A range function like Python's with an increment that returns a list or otherwise iterable
- The ability for a function to axtract the values of specific elements of inputted lists (would require enforcing types in input parameters like Scratch 2 did)
- Return blocks that exit functions, and thus functions as reporter blocks (this one is much more important than the suggestion with lists)
- `change element (i) of [list] by ()` block
- `-=`, `*=` and `/=` in-place blocks (perhaps a single in-place operator function with a dropdown for the function enacted, including bitwise operators, if they're to be added)
- Perhaps remove some blocks and make others work on multiple types like Python, ie. `+` for string concatenation, an indexing block for both strings and lists
- A slicing block for at least strings, ie. `(letters () to () of [])` (though if it were to be upper-exclusive, the word "to" would be somewhat misleading so perhaps only a `(():())` block that fits in the indexing parameter)
- Perhaps a `(sorted ())` function for lists (if the ability to use lists in reporters (instead of their string representations) is added) or an in-place sort function
- Functions that can intake other functions as parameters (ie. a key or comparison function for this sort function), and if reporter functions are to be added, a builtin `(map (function) across ((list))` function (that returns a list or iterable) and ones equivalent to Python's `functools.reduce()` and `itertools.accumulate()`
- Perhaps default values for function parameters when left empty (although perhaps not because they can't be forgone like Python)

**Comment by CST1229** [comment]
Post-unsandboxed-extensions reply:

(links are to the extensions' .js files)

> * Exponentiation (would be either `()**()` or `()^()`), supporting noninteger/negative indices, instead of having to include the long function in each program.

Added by [Math](https://extensions.turbowarp.org/true-fantom/math.js), [Utilities](https://extensions.turbowarp.org/utilities.js) and [LMS Utilities](https://extensions.turbowarp.org/LukeManiaStudios/lmsutils.js
)
> * Roots (would be `()th root of ()`), could be done by exponentiation to indice 1/(root order) but are more concise this way.
> * Logarithms (would be `log () of ()`), can already be done by `ln(input)/ln(base)` but would be more concise this way also.

Added by [Math](https://extensions.turbowarp.org/true-fantom/math.js
)
> * A native `set [list] to ()` function as an inverse to list reporters, for setting lists to strings (perhaps optionally specifying delimiter (if left blank, would split each character)), you could set one list to another instead of iterating through elements. Perhaps also insert lists' full contents (not delimitered) into other lists.

Added by [JSON](https://extensions.turbowarp.org/Skyhigh173/json.js) (using JSON; there's also a block to convert delimited text to JSON)

> * Add bitwise operators and floordiv operator (beneath modulo in the block pane)

Bitwise operators added by [Bitwise](https://extensions.turbowarp.org/bitwise.js
)
> * Inline ternary operator as reporter block (ie. `(() if <> else ())`)

Added by [Utilities](https://extensions.turbowarp.org/utilities.js), [LMS Utilities](https://extensions.turbowarp.org/LukeManiaStudios/lmsutils.js) and probably other extensions

> * A hash operator (not cryptographically secure) that only intakes strings (because the list reporter exports them to strings) and outputs fixed-length hashes, applications mostly for checking transpositions in chess engines or other permutation-tree searches.

Added by [Encoding](https://extensions.turbowarp.org/encoding.js) (MD5)

> * The ability for a function to axtract the values of specific elements of inputted lists (would require enforcing types in input parameters like Scratch 2 did)

Not exactly what you're looking for, but [ShovelUtils](https://extensions.turbowarp.org/TheShovel/ShovelUtils.js) allows you to get and set lists by name

> * A slicing block for at least strings, ie. `(letters () to () of [])` (though if it were to be upper-exclusive, the word "to" would be somewhat misleading so perhaps only a `(():())` block that fits in the indexing parameter)

Added by [Utilities](https://extensions.turbowarp.org/utilities.js), [LMS Utilities](https://extensions.turbowarp.org/LukeManiaStudios/lmsutils.js), [Text](https://extensions.turbowarp.org/text.js) and possibly other extensions
