### ISSUE TITLE
Can't use canvas.toDataURL()

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/extensions#507]
I want to make an extension that allows me to take a screenshot of the canvas by using `vm.renderer.canvas.toDataURL()`. Sadly I can't achieve this because I assume `preserveDrawingBuffer` is `false`.

Any other way this can be done?

**Comment by LukeManiaStudioss** [comment]
If you go to the Looks Plus PR there's a block in that extension that takes a screenshot of the canvas. Look at the source and use that as a reference.

**Comment by TheShovel** [comment]
Ah, alright! Thanks!
