### ISSUE TITLE
Save game progress

### ISSUE THREAD

**Issue by Azulcat** [TurboWarp/extensions#508]
Is there any extension that saves game progress and loads it?

**Comment by LukeManiaStudioss** [comment]
Local Storage

**Comment by Azulcat** [comment]
i don't know how to use it can you explain? plz

**Comment by LukeManiaStudioss** [comment]
![image](https://github.com/TurboWarp/extensions/assets/127533508/6f9fdd9f-9a5e-43bf-ae1b-8720361b3b38)

**Comment by Azulcat** [comment]
lemme try

**Comment by Juenjos** [comment]
https://extensions.turbowarp.org/local-storage.js

**Comment by Azulcat** [comment]
It's not closed it did not work

**Comment by Azulcat** [comment]
Bruh

**Comment by GarboMuffin** [comment]
please provide more details so that we can help you. examples of broken projects are helpful, for example.

**Comment by Azulcat** [comment]
oki
