### ISSUE TITLE
☁ Ping custom cloud server. ☁

### ISSUE THREAD

**Issue by ZekusV** [TurboWarp/extensions#52]
A block that can send a ping to a custom cloud server and get a response via a boolean block if the server status is online will return true else if the server is offline or doesn't get any response back during a certain amount of time will return false.
(Tried messing with the fetch extension, but doesn't work like so: http://localhost:9080/Status.txt (Dislays the text "Online"))
Would be amazing to see an extension like this and help make our projects work online properly :)

**Comment by TheShovel** [comment]
I am writing an extension for that right now.

**Comment by MeztaGames** [comment]
> I am writing an extension for that right now.

Aw amazing, do you plan to make this public?

**Comment by TheShovel** [comment]
Gonna make a pull request when done so yeah.

**Comment by softedco** [comment]
Shouldn't fetch work for that?
-If it succeeds, it's output is true
-If it fails (catches an error), return false

**Comment by ZekusV** [comment]
> Shouldn't fetch work for that? -If it succeeds, it's output is true -If it fails (catches an error), return false But a tool for that would be nice

It wouldn't work when I tried getting a txt file from a link that was a ddns with port.
Example:
http://zekusv.ddns.net:9080/Status.txt would always display an empty value when using fetch.

**Comment by TheShovel** [comment]
Created a pull request, you can go get the code from there in if doesn't get accepted.

**Comment by GarboMuffin** [comment]
https://extensions.turbowarp.org/clouddata-ping.js

**Comment by TrueFantom** [comment]
@TheShovel

I'm going to create a small extension related to internet connection.

Can I use some of your code?

**Comment by GarboMuffin** [comment]
Everything in this repository is open source, typically under this license: https://github.com/TurboWarp/extensions/blob/master/licenses/MIT.txt
