### ISSUE TITLE
Animated Text+ Extension Idea

### ISSUE THREAD

**Issue by NDM1574** [TurboWarp/extensions#545]
Allow multiple sets of animated text, with both simple and advanced block sets.
Blocks:

set text id: [id] text: [text] font: [font] alignment: [alignment]
clear text id: [id]

set text id: [id] text: [text]
set text id: [id] font: [font]
set text id: [id] alignment: [alignment]
set text id: [id] left border: [left border]
set text id: [id] right border: [right border]
set text id: [id] top border: [top border]
set text id: [id] bottom border: [bottom border]

**Comment by LukeManiaStudioss** [comment]
I don't understand the utility of this, can't you just use clones?

**Comment by NDM1574** [comment]
You can, but text engines suck and slows the game down a lot, if it's done
externally it improves a lot.

**Comment by NDM1574** [comment]
I'll try this, thanks
