### ISSUE TITLE
Text extension new block suggestion (INVALID)

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/extensions#547]
![image](https://github.com/TurboWarp/extensions/assets/131917462/01e45f10-06c1-4cad-bf8c-8c3a1dcffa46)
This could be used to find the amount of a letter is in text
I think it could be very useful

**Comment by LukeManiaStudioss** [comment]
I don't update LMS Utilities anymore, the recent update is the second-to-final one.

This block would work well in the Text extension, I believe
