### ISSUE TITLE
Help! Newgrounds.IO extension does not work!

### ISSUE THREAD

**Issue by gomiigg** [TurboWarp/extensions#557]
I tried to implement medals into my game, but they do not work. I have the `Connect to game` block properly set up as well as medal ID's so I don't know what the problem could be. Maybe there is a packaging issue?

P.S: I have reset the app credentials and I was shown the login screen again, but medals still do not work.

Here is the game in question:
https://www.newgrounds.com/portal/view/886824

**Comment by David-Orangemoon** [comment]
Give me a second

**Comment by David-Orangemoon** [comment]
Hey quick question could you check if the user is logged in? I think garbo
might have changed some code in the api that might have broke some features.

**Comment by gomiigg** [comment]
I know that logging in works, because I had made a test project that attemps to get your profile name and picture, and gives you a medal for logging in. Everything worked, except the medal part.

**Comment by David-Orangemoon** [comment]
Ok

**Comment by David-Orangemoon** [comment]
Could you open the chrome console and give me any errors?

**Comment by gomiigg** [comment]
![image](https://github.com/TurboWarp/extensions/assets/91437192/7314b403-21a1-45c3-8944-07dbf6697198)

There's one error that looks like it has to do with NGIO but other thank that it's running `NGIO Tick` normally

**Comment by gomiigg** [comment]
This is on the NG page for the game BTW

**Comment by David-Orangemoon** [comment]
https://github.com/TurboWarp/extensions/pull/558
Here is a fix
https://raw.githubusercontent.com/David-Orangemoon/extensions/patch-7/extensions/obviousAlexC/newgroundsIO.js
instead of just opening the project add the extension through copy and pasting it into the section of add custom extension

**Comment by gomiigg** [comment]
Do i leave the old link in there too?
![image](https://github.com/TurboWarp/extensions/assets/91437192/ba4d6634-8055-4bf3-b98e-912a60c8aae8)

**Comment by gomiigg** [comment]
Wait sorry i read the instructions wrong

**Comment by David-Orangemoon** [comment]
> Wait sorry i read the instructions wrong

you will also have to reset the packager options.

**Comment by gomiigg** [comment]
So I load the new version of NG first, and then load the project, then reset packager options?

**Comment by David-Orangemoon** [comment]
> So I load the new version of NG first, and then load the project, then reset packager options?

yeah then you click the package button again on file.

**Comment by gomiigg** [comment]
![image](https://github.com/TurboWarp/extensions/assets/91437192/f2326b6e-8238-45de-993d-31a483aa13e0)
progress bar freezes...

**Comment by David-Orangemoon** [comment]
> ![image](https://user-images.githubusercontent.com/91437192/244897823-f2326b6e-8238-45de-993d-31a483aa13e0.png) progress bar freezes...

Are you on the discord?

**Comment by gomiigg** [comment]
![image](https://github.com/TurboWarp/extensions/assets/91437192/5aa1904e-42e9-4fda-a733-b7f22f9ea413)
It works now! I pasted the URL instead of refreshing the raw text itself!

**Comment by David-Orangemoon** [comment]
ok that is good.
