### ISSUE TITLE
AR extension documentation page wasn't made from the ground up

### ISSUE THREAD

**Issue by Xeltalliv** [TurboWarp/extensions#564]
https://extensions.turbowarp.org/bitwise.html ([Source code](https://github.com/TurboWarp/extensions/blob/master/website/bitwise.html))
https://extensions.turbowarp.org/box2d.html ([Source code](https://github.com/TurboWarp/extensions/blob/master/website/box2d.html))

were based on:
https://extensions.turbowarp.org/ar.html ([Source code](https://github.com/TurboWarp/extensions/blob/master/website/ar.html))

which I based on my:
https://xeltalliv.github.io/ScratchTools/ProgLang/guide.html ([Source code](https://github.com/Xeltalliv/ScratchTools/blob/main/ProgLang/guide.html))

To avoid possible confusion as to why the html/css of all of them is similar, it might be a good idea to mention somewhere something about it. As far as I understand, technically it's not required, so I'm not sure if it's a good idea

**Comment by GarboMuffin** [comment]
If you want to add a mention somewhere like a comment in the source code, feel free to submit a PR, it will be merged

It is not technically required because ar.html became GPLv3-compatible when you submitted it here, so it can be copied to other files essentially unrestricted

**Comment by GarboMuffin** [comment]
Our new documentation pages are largely ground-up now
