### ISSUE TITLE
Custom reporter and boolean blocks

### ISSUE THREAD

**Issue by BlueDome77** [TurboWarp/extensions#568]
### Discussed in https://github.com/TurboWarp/extensions/discussions/541

<div type='discussions-op-text'>

<sup>Originally posted by **BlueDome77** June  7, 2023</sup>
Is it possible to add the ability to let people make their own Operator and Boolean blocks like in [PenguinMod](https://studio.penguinmod.site/editor.html)?

![Screenshot 2023-06-07 at 10 58 42 AM](https://github.com/TurboWarp/extensions/assets/135789443/9a5ca799-2c85-45fc-b7e7-a03c5893d97b)</div>

**Comment by LukeManiaStudioss** [comment]
Not without modifying the VM it's not.

**Comment by BlueDome77** [comment]
> > Not without modifying the VM it's not. Compatibility-breaking features tend to be reserved for extensions, and this would break that rule, but that might change.
> 
> In my opinion, custom reporters done like in PM are not really an extension thing to do, as they heavily modify existing Scratch components and a bit of UI.

Could be an addon maybe…

**Comment by BlueDome77** [comment]
> So it wouldn't be an addon, but just something in Turbowarp that you can't remove?

That’s the idea…

**Comment by Martinelplayz** [comment]
sooo. never happening?

**Comment by LilyMakesThings** [comment]
I think a better solution would be an inline blocks extension :P 
![image](https://github.com/TurboWarp/extensions/assets/127533508/a2fb3da5-8a37-4db0-b688-782c2c87b857)

This would not have to change anything within the VM (by this I mean it wouldn't change anything on the site that would make vanilla TurboWarp not vanilla), and lines up closer with TurboWarp's unspoken rules (●'◡'●)

**Comment by BlueDome77** [comment]
> I think a better solution would be an inline blocks extension :P ![image](https://user-images.githubusercontent.com/127533508/247939664-a2fb3da5-8a37-4db0-b688-782c2c87b857.png)
> 
> This would not have to change anything within the VM (by this I mean it wouldn't change anything on the site that would make vanilla TurboWarp not vanilla), and lines up closer with TurboWarp's unspoken rules (●'◡'●)

That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.

P.S The code above could be made like this:
![block_6_22_2023-9_08_24 AM](https://github.com/TurboWarp/extensions/assets/135789443/152395c7-a9e1-4f71-ad96-f397d7a81881)

**Comment by BlueDome77** [comment]
Btw what are the “unspoken rules”?

**Comment by CST1229** [comment]
> That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.

This is where custom blocks come in:
![](https://github.com/TurboWarp/extensions/assets/68464103/d0865158-3649-4949-a73a-6eb76550664b)

**Comment by LilyMakesThings** [comment]
> > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> 
> This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)

another example:

![image](https://github.com/TurboWarp/extensions/assets/127533508/55276d91-e85e-4726-bdee-ba349acf2ae9)

**Comment by GarboMuffin** [comment]
I have been thinking about a lot of things :)

**Comment by LilyMakesThings** [comment]
> I have been thinking about a lot of things :)

Bro is a Pokémon, you keep saying this 😭

**Comment by Faris90** [comment]
Does 

> > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > 
> > 
> > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> 
> another example:
> 
> ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)

Is this just concept art or functional?

**Comment by LilyMakesThings** [comment]
> Does
> 
> > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > 
> > > 
> > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > 
> > 
> > another example:
> > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> 
> Is this just concept art or functional?

functional

**Comment by BlueDome77** [comment]
> > Does
> > > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > > 
> > > > 
> > > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > > 
> > > 
> > > another example:
> > > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> > 
> > 
> > Is this just concept art or functional?
> 
> functional

so c-shape blocks work now?

**Comment by LilyMakesThings** [comment]
> > > Does
> > > > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > > > 
> > > > > 
> > > > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > > > 
> > > > 
> > > > another example:
> > > > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> > > 
> > > 
> > > Is this just concept art or functional?
> > 
> > 
> > functional
> 
> so c-shape blocks work now?

no, they don't, this doesn't compile correctly still

**Comment by Faris90** [comment]
> > Does
> > > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > > 
> > > > 
> > > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > > 
> > > 
> > > another example:
> > > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> > 
> > 
> > Is this just concept art or functional?
> 
> functional

Do you have a link?

**Comment by LilyMakesThings** [comment]
> > > Does
> > > > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > > > 
> > > > > 
> > > > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > > > 
> > > > 
> > > > another example:
> > > > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> > > 
> > > 
> > > Is this just concept art or functional?
> > 
> > 
> > functional
> 
> Do you have a link?

nope

**Comment by Faris90** [comment]
txt?

> > > > Does
> > > > > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > > > > 
> > > > > > 
> > > > > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > > > > 
> > > > > 
> > > > > another example:
> > > > > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> > > > 
> > > > 
> > > > Is this just concept art or functional?
> > > 
> > > 
> > > functional
> > 
> > 
> > Do you have a link?
> 
> nope

a text file?

**Comment by BlueDome77** [comment]
> > > > Does
> > > > > > > That kinda defeats the whole purpose of what custom **Operator** and **Boolean** blocks would solve: shorting code and making the coding process much easier.
> > > > > > 
> > > > > > 
> > > > > > This is where custom blocks come in: ![](https://user-images.githubusercontent.com/68464103/247966672-d0865158-3649-4949-a73a-6eb76550664b.png)
> > > > > 
> > > > > 
> > > > > another example:
> > > > > ![image](https://user-images.githubusercontent.com/127533508/247969268-55276d91-e85e-4726-bdee-ba349acf2ae9.png)
> > > > 
> > > > 
> > > > Is this just concept art or functional?
> > > 
> > > 
> > > functional
> > 
> > 
> > Do you have a link?
> 
> nope

what about a js file?

**Comment by CST1229** [comment]
> what about a js file?

[inlineBlocksv3.zip](https://github.com/TurboWarp/extensions/files/11919046/inlineBlocksv3.zip)
Contains the .js file for the extension.
Must be run unsandboxed, obviously. Does not support the compiler without TurboWarp/scratch-vm#141 (it will still run, just that scripts with it will use the interpreter), a prebuilt version of that can be found [here](https://cst1229.github.io/scratch-gui/tw-ext-cblocks/editor.html).

**Comment by Martinelplayz** [comment]
at this point we should easilly just be able to add custom blocks+ :(

**Comment by SurvExe1Pc** [comment]
> > what about a js file?
> 
> [inlineBlocksv3.zip](https://github.com/TurboWarp/extensions/files/11919046/inlineBlocksv3.zip) Contains the .js file for the extension. Must be run unsandboxed, obviously. Does not support the compiler without [TurboWarp/scratch-vm#141](https://github.com/TurboWarp/scratch-vm/pull/141) (it will still run, just that scripts with it will use the interpreter), a prebuilt version of that can be found [here](https://cst1229.github.io/scratch-gui/tw-ext-cblocks/editor.html). The interpreter version of the block does not work properly when it is in multiple inputs in a single block; this is a known bug and can be workarounded by using variables.

Who created the inline blocks thing?

**Comment by CST1229** [comment]
> Who created the inline blocks thing?

I did most of the code.

**Comment by LilyMakesThings** [comment]
CST was the one that actually made it work lol

**Comment by SurvExe1Pc** [comment]
Fast, And thx lol

**Comment by BlueDome77** [comment]
> experiments.turbowarp.org/return

Awesome! I noticed that there's a little extra "tail" at the end of the block
