### ISSUE TITLE
LMS Utilities bug

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/extensions#571]
![image](https://github.com/TurboWarp/extensions/assets/131917462/3ed69754-31c8-4ea9-88a4-d0ad2737791f)
I'm not entirely sure if this is a bug or not, but it only replaces the text **once**. If this isn't a bug, there should be a replace all block so that you don't have to repeatedly replace it.

**Comment by LukeManiaStudioss** [comment]
Yeah this is a bug, you can use Utilities of Text to find a block that has a block that does that.

**Comment by GarboMuffin** [comment]
if you don't want to fix it, perhaps rename it to "replace first [ ] with ..."

**Comment by LukeManiaStudioss** [comment]
> if you don't want to fix it, perhaps rename it to "replace first [ ] with ..."

Alright, I'll do that

It's not that I don't _want_ to fix it, I'm just worried about it breaking projects that may rely on it.

**Comment by LukeManiaStudioss** [comment]
I will not be adding any more blocks to LMS Utilities, no

**Comment by CST1229** [comment]
> Can you tell me where I find this?

https://extensions.turbowarp.org/text.js
https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/text.js

![image](https://github.com/TurboWarp/extensions/assets/68464103/0c82026d-dfdf-4929-a695-033a7c0b3d73)
