### ISSUE TITLE
Temporary Lists

### ISSUE THREAD

**Issue by Skyhigh173** [TurboWarp/extensions#578]
this extension is useful:
- when the list is temporary 
- when too many lists (eg list1,list2,list3,list4...list30)

**Comment by DNin01** [comment]
Temporary Variables in combination with the JSON extension can let us store temporary lists too.

**Comment by Skyhigh173** [comment]
> Temporary Variables in combination with the JSON extension can let us store temporary lists too.

I know, but the speed will be slow when there's too many data

**Comment by SharkPool-SP** [comment]
these exist now

**Comment by yuri-kiss** [comment]
> these exist now

where?

**Comment by SharkPool-SP** [comment]
> > these exist now
> 
> where?

faster json exts + temp variables, dictionaries, etc

**Comment by yuri-kiss** [comment]
> > > these exist now
> > 
> > 
> > where?
> 
> faster json exts + temp variables, dictionaries, etc

that doesnt fix the issue mate

**Comment by SharkPool-SP** [comment]
ok

**Comment by DNin01** [comment]
The Dictionaries extension is basically this.

**Comment by yuri-kiss** [comment]
> The Dictionaries extension is basically this.

not really, but tis already closed so.
