### ISSUE TITLE
Unstoppable forever block

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/extensions#588]
![image](https://github.com/TurboWarp/extensions/assets/131917462/32a1614c-8246-40d5-af51-74dbd4556ca2)
An unstoppable forever block. This could be useful if you want to run a forever loop while still using "Stop other scrips in sprite" block that won't interrupt the forever loop.

**Comment by GalacticCoder922** [comment]
This is possible in [PenguinMod](https://penguinmod.site) using the hat block "Always" in Events and putting blocks under there. It is unstoppable.

**Comment by LilyMakesThings** [comment]
> This is possible in [PenguinMod](https://penguinmod.site) using the hat block "Always" in Events and putting blocks under there. It is unstoppable.

One of my extensions on the PRs adds a block that has the "always" functionality, so this'll soon be in TurboWarp too!

Also, keep in mind, this is a TurboWarp repository, so the issues here will pertain to TurboWarp, not other Scratch/TW mods. Don't assume that the user wants to use PenguinMod! :)

**Comment by GalacticCoder922** [comment]
I'm just telling.

**Comment by Faris90** [comment]
Like this?
`(function(Scratch) {
  'use strict';
  class ABlock {
    getInfo() {
      return {
        id: 'idklul',
        name: 'idk',
        blocks: [
          {
            opcode: 'always',
            blockType: Scratch.BlockType.HAT,
            text: 'always',
            isEdgeActivated: false
          }
        ]
      };
    }
  }
  setInterval(() => {
    const startedThreads = Scratch.vm.runtime.startHats('idklul_always');
  }, 10);
  Scratch.extensions.register(new ABlock());
}(Scratch));`

**Comment by GarboMuffin** [comment]
part of More Events
