### ISSUE TITLE
Window positioning blocks

### ISSUE THREAD

**Issue by gomiigg** [TurboWarp/extensions#590]
Blocks that can change the position of the game window if run on desktop (think like [Rhythm Doctor](https://youtu.be/m22nb_LYm2A?t=52))

`center window to desktop`

`set window x/y to ( )`

`change window x/y to ( )`

`set window width/height to ( )`

`set window align center/left/right`

this can be used with runtime options "stage size" functions in order to make some cool effects

**Comment by BlueDome77** [comment]
I'm making an extension like this right now :)

**Comment by BlueDome77** [comment]
#708
