### ISSUE TITLE
Looks+ suggestion: Add a block to replace png contents

### ISSUE THREAD

**Issue by Meehdrescher** [TurboWarp/extensions#594]
We have the "set svg for costume to (svg input)" block, and there is no block to replace the png content.

If it's already possible with SVG, I'd love to see it with PNG too, the safest way should be to use data URIs...
combined with the snapshot stage block, this could be used to create something like render textures in Unity (https://docs.unity3d.com/Manual/class-RenderTexture.html), so we could for example render the game world, then snapshot the stage and stretch it on the y axis or something...

**Comment by LilyMakesThings** [comment]
It's already been planned. The extension was merged with the SVG dropdown with just "SVG" because I've got plans to add PNG support later, however it won't be as easy as SVG.

**Comment by OeildeLynx31** [comment]
You can just embed a PNG in a SVG, I think.

**Comment by LilyMakesThings** [comment]
> You can just embed a PNG in a SVG, I think.

That's not ideal.

**Comment by GarboMuffin** [comment]
should be able to do this with Skins?
