### ISSUE TITLE
where to i go to host the extension?

### ISSUE THREAD

**Issue by DemonLordDiablo** [TurboWarp/extensions#6]
i am trying to make my own extension, but i don't know how to put it somewhere so i can actually use the extension, i tried just loading the file url on turbowarp, but that didn't work, so where can i go to get a place to put the code so i can actually use it on turbowarp.

**Comment by mollthecoder** [comment]
You can make a pull request adding the extension's files here and @GarboMuffin will merge it (If it's appropriate for Scratch) and you will then be able to find it on [Turbowarp's Extension Page](https://extensions.turbowarp.org)

**Comment by mollthecoder** [comment]
If I solved your question, please close this issue.

**Comment by DemonLordDiablo** [comment]
> If I solved your question, please close this issue.

oh, sorry i didn't see your reply, but what i meant was i was wanting to make an extension, but i have no idea how to load it into turbowarp to test it to even see if it works, because i tried just loading it with the url to the file but it didn't accept that.

**Comment by GarboMuffin** [comment]
Custom extensions are still not ready and are at the point where if you can't figure it out/don't already know, it might be for the best that you don't try to use them (and get really disappointed)

**Comment by DemonLordDiablo** [comment]
> You have to have the file on the internet and on a site that accepts other pages requesting its files. GitHub Pages can be used for that, which you can enable on the settings of the repo where you host the files.

okay, thanks for the help.

**Comment by DemonLordDiablo** [comment]
i created a test one here and put it as pages, but it still didn't work, what did i do wrong?https://demonlorddiablo.github.io/testscratchextension/prompt.js

**Comment by GarboMuffin** [comment]
Custom extensions can't access APIs such as prompt()

Yep. It sucks. That's one of many reasons these things aren't ready.

**Comment by DemonLordDiablo** [comment]
> Custom extensions can't access APIs such as prompt()
> 
> Yep. It sucks. That's one of many reasons these things aren't ready.

oh, okay. :(

**Comment by GarboMuffin** [comment]
Follow https://github.com/TurboWarp/scratch-gui/issues/633

**Comment by GarboMuffin** [comment]
Unsandboxed extensions are ready for testing https://extensions.turbowarp.org/

You can submit extensions to this repository https://github.com/TurboWarp/extensions#readme
