### ISSUE TITLE
TurboHook: Block rendering error.

### ISSUE THREAD

**Issue by SurvExe1Pc** [TurboWarp/extensions#600]
I have turned off all addons and refreshed the page,
For some reason the inputs in the extension are off:
![image](https://github.com/TurboWarp/extensions/assets/135030944/914f9f3c-2018-4b21-910c-e8ee92f77108)
But if I load a different extension say for example clones+ it will render correctly but still not TurboHook
![image](https://github.com/TurboWarp/extensions/assets/135030944/d226246b-fd77-491b-a509-55a6cda5e2fe)

**Comment by LilyMakesThings** [comment]
Yeah, null inputs (inputs that aren't defined as "NUMBER" or "STRING") don't have any rendering cases in Scratch Addons because they aren't supposed to exist.

**Comment by SurvExe1Pc** [comment]
i dont use scratch addons, cause i am to lazy to reconfig it but thanks for telling me lol I only use these extensions:
![image](https://github.com/TurboWarp/extensions/assets/135030944/d0309672-cdc2-469a-abf6-80efdd0525a4)

**Comment by LilyMakesThings** [comment]
> i dont use scratch addons, cause i am to lazy to reconfig it but thanks for telling me lol I only use these extensions: ![image](https://user-images.githubusercontent.com/135030944/246664879-d0309672-cdc2-469a-abf6-80efdd0525a4.png)

You don't use scratch addons, but if you click "Addons" in TurboWarp, it's the same thing.

**Comment by SurvExe1Pc** [comment]
> > i dont use scratch addons, cause i am to lazy to reconfig it but thanks for telling me lol I only use these extensions: ![image](https://user-images.githubusercontent.com/135030944/246664879-d0309672-cdc2-469a-abf6-80efdd0525a4.png)
> 
> You don't use scratch addons, but if you click "Addons" in TurboWarp, it's the same thing.

i tried disabling all the addons, but it was the same thing

**Comment by CubesterYT** [comment]
@SurvExe1Pc Try disabling custom block shape and maybe cat blocks in TW Addons, but null inputs cannot be rendered.

**Comment by SurvExe1Pc** [comment]
thx and i forgot to close the issue
