### ISSUE TITLE
Extensions : "Looks+", "Sensing+", "Files" update suggestion

### ISSUE THREAD

**Issue by XeroName** [TurboWarp/extensions#611]
My environment : TurboWarp Desktop v1.8.0 beta-1.

Hello.
The custom extensions recently added in TurboWarp seems very powerful and having high-level potential.

According to "Scratch built-in timer" benchmark result, it seems quite a bit slow rather than basic blocks, but also allows tons of useful functions developing Scratch-based game just like my case.

But using some of the extensions, I got a few requirements/dissatisfaction about lack of functional process.
So here's the few suggestions about the extensions : **"Looks+", "Sensing+", "Files".**

**In Detail :** 

**1. Functional Error at "Looks+" - The "[effect] effect of (sprite)" block doesn't work with clones.**
When I set the (sprite) tab of block with "this sprite" and use it on Clones, it gets the original sprite's effect values and doesn't recognize parent of itself(clone). Opening the (sprite) tab when clone got birth, just increasing of "this sprite" button selection.
![image](https://github.com/TurboWarp/extensions/assets/63216951/cb4e1564-1661-437d-926d-d1ba16db8b0c)
What a mirror.

**2. EXACTLY Mouse pointer detector at "Sensing+"**
Sensing+ is very useful to add support of mobile touchscreen. But in some of the cases like situation have to support both PC and Mobile Screen, detecting which is exactly mouse pointer goes too difficult. Yeah I know how to detect exactly mouse pointer, not a touchscreen touch, but it is too abstruse and get mess the codes. Basic Scratch's mouse pointer detection is very annoying in this situation.
Adding blocks such as <is Exactly Mouse pointer?> will be very useful to recognizing at computer mouse pointer.

**3 . "Files" : Disable showing "Drag and Drop" box screen when open files / Set a title of file saving window**
Although there's already have an block "set open file selector mode to (open selector immediately)", after using that block, it pops up both file opening window and D&D box at the same time! I hope there be an option disable showing D&D box, to only show file opening window.

Also, when I trying to save any file using "download (string) as (file.txt)" block, the title of file saving window displays raw blob names : such as "blob:file:///12blah9123-blah5345-bl75675ah".
![image](https://github.com/TurboWarp/extensions/assets/63216951/17e6296a-e9e5-4f68-b502-3f18bd257474)
Giving an option to edit it, it will be really cool.

these above are all of my suggestions.
Thank you for reading, and always huge thanks and cheers for GarboMuffin and TurboWarp's developers.

XeroName

**Comment by GarboMuffin** [comment]
I am fixing the looks+ menu issue right now.

For files, you can get that behavior by doing this

![image](https://github.com/TurboWarp/extensions/assets/33787854/f2a3ed45-3616-414a-9727-666114c4f87b)

I have significant concerns about the reliability of this, which is why it's not on the website (browsers sometimes refuse to open the window, but they don't tell us when they do that, so the block can just get stuck forever)

For changing the title of the file saving window, it looks like that screenshot is from the desktop app, where we can probably make it look a bit nicer. However in general we don't have control over what gets displayed there

**Comment by GarboMuffin** [comment]
@LilyMakesThings @David-Orangemoon

**Comment by David-Orangemoon** [comment]
What do you mean by is exactly mouse pointer? Could you give an example.

**Comment by XeroName** [comment]
> What do you mean by is exactly mouse pointer? Could you give an example.

For example, basic Scratch's <mouse pointer touched?> blocks detects both PC mouse pointer and screen touch, which stil remains "pointer recognization" after get off a finger from touchscreen.
It remains until the screen gets another location touch, this phenomenon creates confusing when supports both PC and touchscreen, but have to identificate only the computer mouse pointer.

So I need computer mouse pointer detection in one block, not a finger touch.

**Comment by David-Orangemoon** [comment]
> > What do you mean by is exactly mouse pointer? Could you give an example.
> 
> For example, basic Scratch's <mouse pointer touched?> blocks detects both PC mouse pointer and screen touch, which stil remains "pointer recognization" after get off a finger from touchscreen. It remains until the screen gets another location touch, this phenomenon creates confusing when supports both PC and touchscreen, but have to identificate only the computer mouse pointer.
> 
> So I need computer mouse pointer detection in one block, not a finger touch.
> 
> _Also, thanks for GarboMuffin's quick reply and notice to fixing problem!_

I added part of that i will do the rest tommorow

**Comment by XeroName** [comment]
> > > What do you mean by is exactly mouse pointer? Could you give an example.
> > 
> > 
> > For example, basic Scratch's <mouse pointer touched?> blocks detects both PC mouse pointer and screen touch, which stil remains "pointer recognization" after get off a finger from touchscreen. It remains until the screen gets another location touch, this phenomenon creates confusing when supports both PC and touchscreen, but have to identificate only the computer mouse pointer.
> > So I need computer mouse pointer detection in one block, not a finger touch.
> > _Also, thanks for GarboMuffin's quick reply and notice to fixing problem!_
> 
> I added part of that i will do the rest tommorow

Really appreciate for accepting my suggestion! <3

**Comment by David-Orangemoon** [comment]
> > > > What do you mean by is exactly mouse pointer? Could you give an example.
> > > 
> > > 
> > > For example, basic Scratch's <mouse pointer touched?> blocks detects both PC mouse pointer and screen touch, which stil remains "pointer recognization" after get off a finger from touchscreen. It remains until the screen gets another location touch, this phenomenon creates confusing when supports both PC and touchscreen, but have to identificate only the computer mouse pointer.
> > > So I need computer mouse pointer detection in one block, not a finger touch.
> > > _Also, thanks for GarboMuffin's quick reply and notice to fixing problem!_
> > 
> > 
> > I added part of that i will do the rest tommorow
> 
> Really appreciate for accepting my suggestion! <3

https://github.com/TurboWarp/extensions/pull/613 here is the pull request

**Comment by Skyhigh173** [comment]
About the "files":
Please DONT remove the "drag and drop" box

if you disable it, iOS and iPadOS cannot select files.

**Comment by LilyMakesThings** [comment]
> (TL;DR) About the "files": Please DONT remove the "drag and drop" box
> 
> if you disable it, iOS and iPadOS cannot select files.

And once again I find myself replying to a message in this repo with "wow, apple sucks" (•_•)

**Comment by XeroName** [comment]
> 

Oof... didn't know about that.
Thank you for your advice.

**Comment by XeroName** [comment]
@LilyMakesThings 

Hi Lily.
I've checked Looks+ extension updates today.

The sprite selection menu error seems to be fixed at the situation that clones are generated, but "this sprite" target selection still doesn't work when I trying to targeting clone itself under "when I start as a clone" scripts.
My goal is getting brightness effect value of clone itself, still struggling with this problem.

Could you check this problem? Thank you.

**Comment by LilyMakesThings** [comment]
> @LilyMakesThings
> 
> Hi Lily. I've checked Looks+ extension updates with TurboWarp Desktop-1.8.0 today.
> 
> The sprite selection menu error seems to be fixed at the situation that clones are generated, but "this sprite" target selection still doesn't work when I trying to targeting clone itself under "when I start as a clone" scripts. My goal is getting brightness effect value of clone itself, still struggling with this problem.
> 
> Could you check this problem? Thank you.

Hi,

I will fix this issue as soon as I can. Thank you for informing me of this problem (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by XeroName** [comment]
> > @LilyMakesThings
> > Hi Lily. I've checked Looks+ extension updates with TurboWarp Desktop-1.8.0 today.
> > The sprite selection menu error seems to be fixed at the situation that clones are generated, but "this sprite" target selection still doesn't work when I trying to targeting clone itself under "when I start as a clone" scripts. My goal is getting brightness effect value of clone itself, still struggling with this problem.
> > Could you check this problem? Thank you.
> 
> Hi,
> 
> I will fix this issue as soon as I can. Thank you for informing me of this problem (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

The "this sprite" problem in clones have been fixed. Thank you so much!
