### ISSUE TITLE
Allow unchecked unsandboxed extensions with some sort of warning

### ISSUE THREAD

**Issue by infernostars** [TurboWarp/extensions#62]
The current issue I can see is that I want to test my extension with others. However, they are not willing to figure out how to host a server just to test it out. Perhaps some sort of warning to allow untrusted unsandboxed extensions would be good? Should probably be a very heavy "you shouldn't do this", but would be nice to have regardless

**Comment by softedco** [comment]
You can host extensions on github by using github pages

**Comment by infernostars** [comment]
Doesn't allow *unsandboxed* extensions, though

**Comment by GarboMuffin** [comment]
We might add a way to run unsandboxed extensions by uploading a file but URLs seem a bit risky

**Comment by infernostars** [comment]
Fair. I'm fine with no URLs so /shrug

**Comment by showierdata9978** [comment]
maybe expose a global `scratch` object in the window so that extentions can be loaded  your way via scriptlets and dev console

**Comment by softedco** [comment]
> maybe expose a global `scratch` object in the window so that extentions can be loaded  your way via scriptlets and dev console 

Too risky, loading extensions via window.vm is not safe

**Comment by showierdata9978** [comment]
> > maybe expose a global `scratch` object in the window so that extentions can be loaded  your way via scriptlets and dev console
> 
> Too risky, loading extensions via window.vm is not safe

???? not what i said at all

i suggested that so ppl would NOT need to do that

 im saying expose the `Scratch.extensions` API to the dev console

**Comment by softedco** [comment]
> > > maybe expose a global `scratch` object in the window so that extentions can be loaded  your way via scriptlets and dev console
> > 
> > Too risky, loading extensions via window.vm is not safe
> 
> ???? not what i said at all
> 
> i suggested that so ppl would NOT need to do that
> 
>  im saying expose the `Scratch.extensions` API to the dev console
>  

I know what you meant, it wouldn't be any safer that way

**Comment by GarboMuffin** [comment]
We allow them from files and text now
