### ISSUE TITLE
ScratchBlocks not defined when loading extensions

### ISSUE THREAD

**Issue by LilyMakesThings** [TurboWarp/extensions#620]
I imagine if there was a way to fix this, it would've been done by now, but is there a way for ScratchBlocks to be defined before loading extensions, or to pause loading extensions until it's been typed? We'd be able to do so much more with extensions if we were able to access it consistently :/

**Comment by GarboMuffin** [comment]
if it's not defined then it means the JavaScript literally hasn't been downloaded yet

it sounds like you would be better off submitting your changes as scratch-blocks/scratch-vm/etc. improvements so everyone can use them
