### ISSUE TITLE
New Extension: HS Utilities

### ISSUE THREAD

**Issue by horizontal-shading** [TurboWarp/extensions#644]
I think there should be an extension which adds 6 new blocks.

![Screenshot 2023-06-26 at 20-10-01 TurboWarp - Run Scratch projects faster](https://github.com/TurboWarp/extensions/assets/137826335/366aaa32-fec9-4d94-bdda-365052a1d18e)

This is my thumbnail idea.

![hsutilities](https://github.com/TurboWarp/extensions/assets/137826335/3e196102-1fe4-47b9-8f14-9dbde6246df4)

I hope you like this idea.
Note: I'm new to Github.

**Comment by horizontal-shading** [comment]
Source code: https://github.com/horizontal-shading/HS-Extensions

**Comment by GalacticCoder922** [comment]
Many of these blocks are in other extensions, this is probably a no.

**Comment by Flappy25** [comment]
> I think there should be an extension which adds 6 new blocks.
> 
> ![Screenshot 2023-06-26 at 20-10-01 TurboWarp - Run Scratch projects faster](https://github.com/TurboWarp/extensions/assets/137826335/366aaa32-fec9-4d94-bdda-365052a1d18e)
> 
> This is my thumbnail idea.
> 
> ![hsutilities](https://github.com/TurboWarp/extensions/assets/137826335/3e196102-1fe4-47b9-8f14-9dbde6246df4)
> 
> I hope you like this idea.
> Note: I'm new to Github.

Random Chinese letter? Really?

**Comment by horizontal-shading** [comment]
I'm closing this issue

**Comment by horizontal-shading** [comment]
_This comment was marked as off-topic._
