### ISSUE TITLE
Delta time extension

### ISSUE THREAD

**Issue by TONYflashB** [TurboWarp/extensions#654]
Basically this extension will have a Delta Time reporter block which tells the elapsed time between two frames [Delta time on Wikipedia](https://en.m.wikipedia.org/wiki/Delta_timing)

**Comment by LilyMakesThings** [comment]
This is already in the pull requests! :)
https://github.com/TurboWarp/extensions/pull/622

**Comment by Azulcat** [comment]
GREAT IDEA
