### ISSUE TITLE
IFTTT Webhooks Extension!! (WITH DOCS)

### ISSUE THREAD

**Issue by kindpump** [TurboWarp/extensions#655]
This extension allows users to safely interact with third party applications using webhook keys via IFTTT.
Extension URL: https://[kindpump.github.io/extensions/ifttt.js](https://kindpump.github.io/extensions/ifttt.js)
Documentation URL: https://kindpump.github.io/IFTTTDOCS.html
![webhook](https://github.com/TurboWarp/extensions/assets/115276781/f900d93a-0ca2-435f-a32f-bdf2a21d9842)
![1](https://github.com/TurboWarp/extensions/assets/115276781/304220ab-28e3-40c9-9787-c018c278ed3d)

**Comment by GarboMuffin** [comment]
send it in a pull request
