### ISSUE TITLE
How to make empty text for REPORTER block?

### ISSUE THREAD

**Issue by TrueFantom** [TurboWarp/extensions#66]
Apparently there is similar bug again...

Instead of empty value, it's name is displayed on block.
![Screenshot_159](https://user-images.githubusercontent.com/116278271/207080156-903f0168-0a7e-4a24-8979-54714decf817.png)
Here is the code:
![Screenshot_160](https://user-images.githubusercontent.com/116278271/207080924-f000cddd-b0fa-4ec3-abdd-a03783698171.png)
I hope this will be fixed. Thanks in advance.

**Comment by GarboMuffin** [comment]
You can't make blocks with no name. Works as intended.

**Comment by TrueFantom** [comment]
It was experiment. I would like to create stub block that could be used instead of an empty field. Empty name would suit him perfectly. It is unlikely that this block would be helpful in principle, but I wanted to test it. Now I will use 'empty', instead of ''

Thanks for the answer)

**Comment by CST1229** [comment]
> It was experiment. I would like to create stub block that could be used instead of an empty field. Empty name would suit him perfectly. It is unlikely that this block would be helpful in principle, but I wanted to test it. Now I will use 'empty', instead of ''

You might be able to use special characters but that's probably kind of hacky and might not be okay.

**Comment by TrueFantom** [comment]
@CST1229 Oh, not a bad alternative) Thanks.

**Comment by softedco** [comment]
> > It was experiment. I would like to create stub block that could be used instead of an empty field. Empty name would suit him perfectly. It is unlikely that this block would be helpful in principle, but I wanted to test it. Now I will use 'empty', instead of ''
> 
> You might be able to use special characters but that's probably kind of hacky and might not be okay.

Not hacky as long as it doesn't introduce bidirectional unicode issues

**Comment by showierdata9978** [comment]
you can prob just do a single space, or a thin space ` `
