### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SurvExe1Pc** [TurboWarp/extensions#675]
Other mitigating factors that make this not a large problem:

 - Our extension library has grown *massively*. There are fewer gaps to fill than ever.
 - You can just load extensions from files now. They get stored in the project.

> so they need a base of what they actually do to make it easier, so split them into different extensions?

Yes, the proposal is that those should be split into separate extensions. If another extension in the same category exists, consider adding to that one instead of making a new one.

> i understand the issue, as it can be hard to make an image based on an extension that has really no base.

Yes, see the RixxyX image for an image that don't really represent the functionality because it's just too broad

> should I close my PR?

It's only been 30 minutes so this discussion is not closed. However I would encourage you to pick specific parts of 0tils to focus on and make extensions that go deep in each specific area.

_Originally posted by @GarboMuffin in https://github.com/TurboWarp/extensions/issues/674#issuecomment-1616400812_

**Comment by SurvExe1Pc** [comment]
should I move the raw download block to the files extension?

**Comment by SurvExe1Pc** [comment]
and question on my (i36) block, what do i do with that,

**Comment by SurvExe1Pc** [comment]
woops

**Comment by GarboMuffin** [comment]
> should I move the raw download block to the files extension?

I am not familiar with what your raw download block does, but that seems like a logical place

> and question on my (i36) block, what do i do with that,

I do not know what i36 is, but it seems you basically have a numerical encoding alternative? you could add a new extension if you want

**Comment by SurvExe1Pc** [comment]
> I am not familiar with what your raw download block does, but that seems like a logical place

Ill attempt a video

**Comment by SurvExe1Pc** [comment]
because no extension has a proper raw decode for base64 i could not show the difference

**Comment by SurvExe1Pc** [comment]
there is some compatibility issues in the encoding extension should i just put it in a new file

**Comment by SurvExe1Pc** [comment]
relevant: https://github.com/TurboWarp/extensions/pull/676
