### ISSUE TITLE
When framerate is set to 0 (unlimited), the framerate limit block should ideally report the screen refresh rate

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/extensions#679]
Some projects may use the framerate limit block to properly time events, but that's not possible when you've set the framerate to 0.

When the framerate is set to 0, that actually means to match the device's screen refresh rate [(source)](https://docs.turbowarp.org/custom-fps). This is the only time I am aware of where the framerate reported by the block doesn't match the actual refresh rate, which might be problematic for projects that use it to calculate how far to move something forward in time.

**Comment by horizontal-shading** [comment]
Is that even possible? I've never seen any program other than Settings to see your refresh rate. (Windows 10)

**Comment by DNin01** [comment]
> Is that even possible? I've never seen any program other than Settings to see your refresh rate. (Windows 10)

I mean, desktop games must be able to, because they would need to render the game screen at the correct rate.

**Comment by horizontal-shading** [comment]
> > Is that even possible? I've never seen any program other than Settings to see your refresh rate. (Windows 10)
> 
> I mean, desktop games must be able to, because they would need to render the game screen at the correct rate.

I guess you _could_ be right.

**Comment by DNin01** [comment]
I guess this is basically resolved via the Deltatime extension.

**Comment by GarboMuffin** [comment]
Your browser won't tell us what your actual screen refresh rate it, we just have to guess from how often it lets us run, which is what delta time gives you
