### ISSUE TITLE
Stretch bug: stretch doesn't get cloned

### ISSUE THREAD

**Issue by CST1229** [TurboWarp/extensions#68]
Steps to reproduce:
- Add the Stretch extension
- Set the stretch of a sprite to something other than 100x100
- Create a clone of the sprite
- The stretch of the clone is reset to 100x100

**Comment by softedco** [comment]
I believe that's not the extension's issue

**Comment by GarboMuffin** [comment]
it's the extension's issue

**Comment by softedco** [comment]
> it's the extension's issue

Oh ok
