### ISSUE TITLE
Idea for extension

### ISSUE THREAD

**Issue by Qewbitech** [TurboWarp/extensions#684]
What about an extension that allows to upload images from a file. Like a "load image from url" (ShovelUtils), but "load image from file"

**Comment by ClaytonTDM** [comment]
You can already do this with the files extension
![image](https://github.com/TurboWarp/extensions/assets/71360210/fac2123e-8b0e-479c-86d8-55ad1487c102)

**Comment by Qewbitech** [comment]
Thanks, I didn't guess
