### ISSUE TITLE
We need a Motion and Control Plus!

### ISSUE THREAD

**Issue by ghost** [TurboWarp/extensions#686]
Hello! It's Aiden, aka GalacticCoder922,
So far, I have seen people add extensions that are "expansions" of a category. For example:
Looks +
Sound Expanded (requested)
More Events (requested)
Sensing + 
Operators Expansion (requested) (in PenguinMod)
and Variable and List!
What we are missing is Motion and Control.
Could someone make a Motion expansion and a Control expansion? Those are what we are missing for now. I've been waiting for a Motion Expansion to be requested, but not so much for a Control one? But can someone please make both?

**Comment by David-Orangemoon** [comment]
The problem with making both of them. Motion doesn't have any blocks that seem missing, and the problem with Control is the lack of c-blocks and ideas.

**Comment by GalacticCoder922** [comment]
Then how come PenguinMod has more Motion and Control blocks?

**Comment by David-Orangemoon** [comment]
Because penguinmod has the ability to edit scratchblocks

**Comment by NexusKitten** [comment]
> Then how come PenguinMod has more Motion and Control blocks?

Two reasons:
- PenguinMod generally has more customization when it comes to blocks, i.e. modification of C-Blocks and such
- The extra blocks in these categories all have workarounds. While they are still useful, I personally wouldn't consider something that can be worked around "plus," more of extra utility.

**Comment by GalacticCoder922** [comment]
Alright.

**Comment by David-Orangemoon** [comment]
> > Then how come PenguinMod has more Motion and Control blocks?
> 
> Two reasons:
> - PenguinMod generally has more customization when it comes to blocks, i.e. modification of C-Blocks and such
> - The extra blocks in these categories all have workarounds. While they are still useful, I personally wouldn't consider something that can be worked around "plus," more of extra utility.

The only way I'd consider something that can be worked around plus is if it provides a giant performance boost. Like pen+'s triangle blocks

**Comment by GalacticCoder922** [comment]
Alright..?

**Comment by LilyMakesThings** [comment]
Control Plus I have plenty of ideas for but I'm not even going to consider working on it until we're allowed to use C-Blocks (repeat, forever, if, etc) in our extensions, which might not be for a while.

**Comment by GalacticCoder922** [comment]
Ok.
