### ISSUE TITLE
Extension Security do not show again

### ISSUE THREAD

**Issue by xEobardThawne** [TurboWarp/extensions#687]
For custom extensions that are loaded into a project via file (and maybe text), it'll always ask if you trust the extension and whether you want to run it without the sandbox when loading the project. I suggest a setting for the extension security to not show the message again after you've chosen to run with/without sandbox. The setting could be saved similar to how advanced settings are saved in the stage. As someone with their own personal extension, something like this would be helpful.

**Comment by LIZARD-OFFICIAL** [comment]
Yes, its super annoying because im using weather extension and it asks me everytime i load project.

**Comment by GarboMuffin** [comment]
Problem is that after you load the first malicious extension, it can then permanently add all sorts of other extensions to the list of extensions to always allow without you knowing
