### ISSUE TITLE
Avoid using "unsandboxed" in user-facing pages

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#69]
In computing, "unsandboxed extensions" or "unsandboxed plugins" have a bad history (see "flash" and "java"). We should avoid using that word, and use something that is both more descriptive and less scary to users.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/33787854/208269471-14945a78-ca9c-4d1e-b4ed-8a48d6b5c53e.png">

**Comment by softedco** [comment]
Maybe internal or integrated extensions, it describes that they work on a different level while not having that un prefix shared with unsafe.
