### ISSUE TITLE
Custom Cursor

### ISSUE THREAD

**Issue by Azulcat** [TurboWarp/extensions#701]
There is this extension known as a custom cursor and it doesn't have the ability of ''custom'' maybe I missed sumthing?

**Comment by LilyMakesThings** [comment]
Yes, you did
![image](https://github.com/TurboWarp/extensions/assets/127533508/bf0a1af5-89b5-4df2-8923-7b3816e6f0c7)

**Comment by Azulcat** [comment]
Thanks!

**Comment by Azulcat** [comment]
I had a bug where that specific code won't sow up but it's fixed @LilyMakesThings
