### ISSUE TITLE
Animated text: New Block

### ISSUE THREAD

**Issue by YogaindoCR** [TurboWarp/extensions#704]
Can we have this?
![Can we have this](https://github.com/TurboWarp/extensions/assets/132117105/d2619003-9497-42c1-be18-56484cec2d8a)

**Comment by BlueDome77** [comment]
Where is this from?

**Comment by YogaindoCR** [comment]
> Where is this from?

Ahh it's just a block example idea

**Comment by YogaindoCR** [comment]
I found this block on Gandi IDE
![Gandi](https://github.com/TurboWarp/extensions/assets/132117105/da5cc7cc-5896-4539-9798-d6f1564a569e)
Would be great if we have this too

**Comment by SharkPool-SP** [comment]
I believe Animated Text has been updated and has these blocks now
