### ISSUE TITLE
Shapes Extension

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/extensions#711]
![image](https://github.com/TurboWarp/extensions/assets/131917462/2e676a6f-7240-47f4-b444-c91eb1ba4955)
Allows for shapes to be created through blocks, without any extra processes. 
If you are confused with anything ask

Please make this!

**Comment by David-Orangemoon** [comment]
> You can achieve something similar with [Pen+](https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/penplus.js)

Pen+ is getting a sizable update soon so give it a moment also.

**Comment by BlueDome77** [comment]
> > You can achieve something similar with [Pen+](https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/penplus.js)
> 
> Pen+ is getting a sizable update soon so give it a moment also.

Just curious does Pen+ use the same methods as the normal pen extension does?

**Comment by David-Orangemoon** [comment]
Pen+ draws directly to the pen layer (on v6 and above) But this sounds like
a good idea also. Though if it is constantly changing I would recommend pen+

**Comment by David-Orangemoon** [comment]
> 

Yeah because its pen.

**Comment by BlueDome77** [comment]
Extension Concept (Non-functional): [Shapes.txt](https://github.com/TurboWarp/extensions/files/12027466/Shapes.txt)

**Comment by SharkPool-SP** [comment]
@UndermanReal to tackle your issue for creating shapes, take a look at Sharktilities on my gallery:
https://sharkpools-extensions.vercel.app/

There is a block that allows you to create shapes based on points. It can be exported as a svg/png as well. Which in turn can act as a sprite

**Comment by CubesterYT** [comment]
Achievable using Pen+ V7
