### ISSUE TITLE
Camera With interploatation

### ISSUE THREAD

**Issue by Azulcat** [TurboWarp/extensions#715]
I rlly need the camera extension working with **interploatation**

**Comment by Flappy25** [comment]
> I rlly need the camera extension working with **interploatation**

Just use the basic scratch smoothing tricks

**Comment by penta-quark-neutro** [comment]
What you are looking for is that the camera moves smoothly to its target and not abruptly, right?

**Comment by penta-quark-neutro** [comment]
![Captura de pantalla (225)](https://github.com/TurboWarp/extensions/assets/134885702/ca542250-1eb4-48f9-833a-67c60a22e24b)
you can try with this.
I hope that the behavior you are looking for for the camera.
where it says "suavidad" is a variable that controls the displacement behavior of the camera.

**Comment by Azulcat** [comment]
Thank you imma try this
@penta-quark-neutro

**Comment by Azulcat** [comment]
suavidad?

**Comment by penta-quark-neutro** [comment]
"módulo" in the interface in English is mod.
the "suavidad" variable can be any value, I recommend a value between 5 and 10.
or not be a variable and just put a number that works well.

**Comment by penta-quark-neutro** [comment]
What this does is look for the distance between coordinates and by dividing the first distance by a number greater than 1 and pass it through the mod function and on the other side the same distance function of a coordinate without dividing, it gives very useful results.

**Comment by Azulcat** [comment]
IT's SMOOTH but for some reason camera switches to NaN @penta-quark-neutro

**Comment by Azulcat** [comment]
wait I think 1.5 works fine i will close when eveything is good

**Comment by Azulcat** [comment]
1.3 is good for me thank you!

**Comment by Azulcat** [comment]
I have been experiencing this with a cam x and cam y variable I made (like real cam x and cam y variables) and when I tried interpolation it was clean, some people say it was because of laggy projects but I tried a simple project with the cam x and cam y extension and it lagged! (I need this to get fixed)

https://github.com/TurboWarp/extensions/assets/134739700/1aecbb9c-c539-4df3-bcbe-79dca0e79385

**Comment by Flappy25** [comment]
> I have been experiencing this with a cam x and cam y variable I made (like real cam x and cam y variables) and when I tried interpolation it was clean, some people say it was because of laggy projects but I tried a simple project with the cam x and cam y extension and it lagged! (I need this to get fixed)
> 
> https://github.com/TurboWarp/extensions/assets/134739700/1aecbb9c-c539-4df3-bcbe-79dca0e79385
> 
> 

Maybe try to fix collisions or just divide the distance to the goal

**Comment by Azulcat** [comment]
@Flappy25 lemme simplify so I meant that the camera extension with interplotation is it a bug.

**Comment by Flappy25** [comment]
> @Flappy25 lemme simplify so I meant that the camera extension with interpolation does not work, is it a bug?

Maybe, I'll test myself

**Comment by Azulcat** [comment]
alright!

**Comment by Flappy25** [comment]
> @Flappy25 lemme simplify so I meant that the camera extension with interpolation does not work, is it a bug?

Why do you need interpolation anyways?

**Comment by Azulcat** [comment]
delta timing does not work with my game das why

**Comment by Flappy25** [comment]
The camera extension uses the scratch VM to move the stage camera, it doesn't move the sprites themselves. Interpolation is only for sprites moving, not the scratch VM camera. I think that's the problem

**Comment by Azulcat** [comment]
bruh so no fix right? or maybe they might be a solution?

**Comment by Flappy25** [comment]
> delta timing does not work with my game das why

Delta timing is for different framerates. Not interpolation

**Comment by Flappy25** [comment]
> bruh so no fix right? or maybe they might be a solution?

I think you just need to stop using interpolation, it just won't work with the camera. There isn't another fix unless you just move the other sprites themselves and not use the camera extension

**Comment by Azulcat** [comment]
that's the problem ùy game code is against this

**Comment by Flappy25** [comment]
> that's the problem my game code is against this

Your game <strong>needs</strong> interpolation?

**Comment by Azulcat** [comment]
yes but it did not work with camera like i said

**Comment by Flappy25** [comment]
> I told you why already

**Comment by Azulcat** [comment]
why did you ask if my game needs interpolation?

**Comment by Flappy25** [comment]
> why did you ask if my game needs interpolation?

Because you shouldn't use it

**Comment by Azulcat** [comment]
alright sorry for brothering you

**Comment by LilyMakesThings** [comment]
Interpolation as an option is very unreliable, and a lot of extensions are not designed to work with it.

In a recent update to camera I added a function to automatically disable interpolation on a project with camera when you load the extension.

**Comment by Azulcat** [comment]
Thank you for the info! but unfortunately, my game does not work with delta time for some reason

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
