### ISSUE TITLE
I need help with a broadcasting substitute extension!

### ISSUE THREAD

**Issue by Turquioii** [TurboWarp/extensions#718]
I'm trying to make a block that broadcasts a value or two, but I can't seem to send values from point A to point B. 
I read the TurboWarp documentation and found out it might be challenging or impossible to transfer non-field menu values, so I wanna find a way to work around it. Allow me to provide some insight:

Let's say I have a broadcaster block with two inputs (A) and (B) as strings. -Trigger Block
Let's also say we have Hat Blocks, with two more inputs (A) and (B), also strings. -Event Block

When the trigger block runs, it tells all event blocks with (A) and (B) values matching to the trigger to run their scripts, like a filter. 
Is there a way to accomplish this using Vanilla TurboWarp extension features? 

Thanks for reading.

**Comment by SurvExe1Pc** [comment]
like this?
![image](https://github.com/TurboWarp/extensions/assets/135030944/2c86f9f5-eb7f-407b-829f-fc2511a2d7bf)

**Comment by qxsck** [comment]
> 喜欢这个？ ![图像](https://usercontent.githubfast.com/user-images/135030944/252261951-2c86f9f5-eb7f-407b-829f-fc2511a2d7bf.png)

how to achieve it?

**Comment by GarboMuffin** [comment]
More Events should be what you're looking for, I think?
