### ISSUE TITLE
LMS utilities gone

### ISSUE THREAD

**Issue by LIZARD-OFFICIAL** [TurboWarp/extensions#719]
Recently i noticed that LMS utilities extension just disappeared.

**Comment by CST1229** [comment]
#429
Basically: Almost all of its blocks were in other extensions but better.

**Comment by penta-quark-neutro** [comment]
LMS still accessible.
it just uses your JS file as a custom extension.
I still use LMS.

**Comment by LIZARD-OFFICIAL** [comment]
> LMS still accessible. it just uses your JS file as a custom extension. I still use LMS.

Its removed from the gallery but in the os im making it works.
