### ISSUE TITLE
Joysticks Are Laggy

### ISSUE THREAD

**Issue by thecoolestcat** [TurboWarp/extensions#72]
Whenever I try to access an control stick on my controller it works, then stops, then works again, before stopping again. If i feed the input of the joystick into a controller it shows a solid input that stays the same number it should be.

**Comment by GarboMuffin** [comment]
What browser & operating system are you using?

**Comment by thecoolestcat** [comment]
At the time I was using the Turbowarp desktop app, however when I use my browser the inputs are no longer flickery.

**Comment by GarboMuffin** [comment]
The desktop app does not support these extensions very well for now. If you install https://github.com/TurboWarp/desktop/releases/tag/v1.7.0-beta.0 then it should work a lot better.
