### ISSUE TITLE
Add an overlay extension

### ISSUE THREAD

**Issue by ClaytonTDM** [TurboWarp/extensions#720]
It would be awesome to have an HTML overlay extension, like the one proposed for [TurboLoader](https://greasyfork.org/en/scripts/437432-turboloader)
Here's the description from the extension (the dev for TurboLoader hasn't created the extension yet)
```
Plugin for rendering overlays.
For example, play YouTube or local videos, draw HTML,
view some websites, use code editors, unleash your creativity.
```

**Comment by BlueDome77** [comment]
Snippet from [CONTRIBUTING.md](https://github.com/TurboWarp/extensions/blob/master/CONTRIBUTING.md): `Extensions must not use eval(), new Function(), untrusted <script> or <iframe> tags, or similar arbitrary JS/CSS/HTML/etc.`
