### ISSUE TITLE
Gamejolt / Unpackager

### ISSUE THREAD

**Issue by lolpng944** [TurboWarp/extensions#739]
I have a problem.

I use the gamejolt api but basically everyone can see the api key if they unpackage my html file to sb3 so how can i prevent this cause the extension gamejolt documentation said that it is safe????

**Comment by LilyMakesThings** [comment]
Even without the unpackager it was unsafe, I was able to get my friend's API keys just by using inspect element.

**Comment by lolpng944** [comment]
thats pain do you know any alternative way?

**Comment by LilyMakesThings** [comment]
> thats pain do you know any alternative way?

I don't, someone else might.

**Comment by lolpng944** [comment]
Okay, thanks.

**Comment by SurvExe1Pc** [comment]
sadly because turbowarp packager does not have some sort of environment variables system I don't think it is currently possible 😭

**Comment by ClaytonTDM** [comment]
Although you could make it connect to some sort of external server and grab the api keys

**Comment by David-Orangemoon** [comment]
> sadly because turbowarp packager does not have some sort of environment variables system I don't think it is currently possible sob

Maybe custom JS?

**Comment by SurvExe1Pc** [comment]
> > sadly because turbowarp packager does not have some sort of environment variables system I don't think it is currently possible sob
> 
> Maybe custom JS?

Thats just thrown into a script tag for anyone to see.


> Although you could make it connect to some sort of external server and grab the api keys

people could snoop the network.

**Comment by penta-quark-neutro** [comment]
You could put the key in a variable and use the reporter of sensing plus and LMS or more events to detect if it is packed or not, and if it is not, delete the variable with the key and for more security you could encrypt the key.
![Captura de pantalla (224)](https://github.com/TurboWarp/extensions/assets/134885702/1f35c59f-5932-4c0a-a813-41c6c0bc8f48)

**Comment by ClaytonTDM** [comment]
Maybe just have your own server handle making sensitive requests so the API key isn't ever in the project

**Comment by lolpng944** [comment]
> Maybe just have your own server handle making sensitive requests so the API key isn't ever in the project

Thats really not safe why shouldn't people be able to see it in the console?

**Comment by ClaytonTDM** [comment]
Because the API key is saved in an environment variable on the server and never exposed

> > Maybe just have your own server handle making sensitive requests so the API key isn't ever in the project
> 
> Thats really not safe why shouldn't people be able to see it in the console?

**Comment by lolpng944** [comment]
> Because the API key is saved in an environment variable on the server and never exposed
> 
> > > Maybe just have your own server handle making sensitive requests so the API key isn't ever in the project
> > 
> > 
> > Thats really not safe why shouldn't people be able to see it in the console?

Could you give an example how this would work in blocks

**Comment by SurvExe1Pc** [comment]
well the app would just tell the server to make the requests and return the output

**Comment by lolpng944** [comment]
> You could put the key in a variable and use the reporter of sensing plus and LMS or more events to detect if it is packed or not, and if it is not, delete the variable with the key and for more security you could encrypt the key. ![Captura de pantalla (224)](https://user-images.githubusercontent.com/134885702/254331424-1f35c59f-5932-4c0a-a813-41c6c0bc8f48.png)



> Because the API key is saved in an environment variable on the server and never exposed
> 
> > > Maybe just have your own server handle making sensitive requests so the API key isn't ever in the project
> > 
> > 
> > Thats really not safe why shouldn't people be able to see it in the console?

I mean in the console of the packaged html file if i play the game

**Comment by penta-quark-neutro** [comment]
I believe that in the consoles extension there is a block that allows you to remove all information from the console.
Just make it active all the time.

**Comment by SurvExe1Pc** [comment]
you can save the console history before its cleared 🪄
________________________________

**Comment by ClaytonTDM** [comment]
Even if it clears the console, you can still see keys in the network tab.

**Comment by softedco** [comment]
> I have a problem.
> 
> I use the gamejolt api but basically everyone can see the api key if they unpackage my html file to sb3 so how can i prevent this cause the extension gamejolt documentation said that it is safe????

don't make it downloadable
