### ISSUE TITLE
bug in Camera Controls

### ISSUE THREAD

**Issue by scoobydoofacethingdie** [TurboWarp/extensions#741]
there's a bug in the extension "Camera Controls" where the bubble of the "say" and "think" block does not go outside the stage size, it stays clamped inside the stage even if "Remove Fencing" has been enabled in advanced

![image](https://github.com/TurboWarp/extensions/assets/85052868/d79f1c7e-1351-4b38-9840-70b17760823f)

**Comment by scoobydoofacethingdie** [comment]
![image](https://github.com/TurboWarp/extensions/assets/85052868/de84c799-9769-4e46-b399-e705731008b2)
another example

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
