### ISSUE TITLE
Camera Controls screws up dragging.

### ISSUE THREAD

**Issue by TheCrowModder** [TurboWarp/extensions#742]
I'm not sure how to describe the problem with this. Basically moving camera controls moves where scratch thinks the sprite is. So if you try to drag it in the editor or in game it's where the red box is and not the actual object.
![image](https://github.com/TurboWarp/extensions/assets/135927010/be58ffb6-6397-4150-8a0b-d5c0cf37d152)

**Comment by TheCrowModder** [comment]
This also screws up any other thing in the editor relating to clicking on the sprite

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
