### ISSUE TITLE
turbowarp "say" block glitch messing with position

### ISSUE THREAD

**Issue by scoobydoofacethingdie** [TurboWarp/extensions#743]
in turbowarp there's a glitch with the "say" block which for some reason changes the position of the player, im using the "camera controls" extension and NO extension that lets me see what the sprite is saying (like the "looks+" extension)
here's an example:
https://www.youtube.com/watch?v=ysD8o8tQUFA
none of my code is doing anything with what the sprite is saying, except for the example script in the example video

**Comment by scoobydoofacethingdie** [comment]
> camera controls is just a broken mess

i wonder how that even is possible, the position of the say bubble somewhat messing with the sprite's position? (this glitch doesn't work if I manually run ONLY the say block by clicking on it)

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
