### ISSUE TITLE
cant stamp with pen outside stage with "camera controls" extension

### ISSUE THREAD

**Issue by scoobydoofacethingdie** [TurboWarp/extensions#744]
cant stamp a costume outside the stage with "camera controls" extension and remove fencing enabled

**Comment by TeknikSpace** [comment]
Touching Mouse Pointer Doesn't Work Either

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
