### ISSUE TITLE
Notifications Extension: Doesn't work on Windows

### ISSUE THREAD

**Issue by TeknikSpace** [TurboWarp/extensions#745]
the extension doesn't work on windows.
I have notification permission, but creating a notification doesn't work.

The project and site have notification permission

**Comment by SurvExe1Pc** [comment]
are you on dnd?
![image](https://github.com/TurboWarp/extensions/assets/135030944/e9505e06-d873-4111-89c3-b841aa5fcc6d)
and make sure you did not block the app from using notifications

**Comment by TeknikSpace** [comment]
No, I have checked

> are you on dnd? ![image](https://user-images.githubusercontent.com/135030944/253791647-e9505e06-d873-4111-89c3-b841aa5fcc6d.png) and make sure you did not block the app from using notifications

**Comment by TeknikSpace** [comment]
<img width="284" alt="image" src="https://github.com/TurboWarp/extensions/assets/107750535/2c934a52-6ba7-4640-903a-0fa273036b2a">

**Comment by SurvExe1Pc** [comment]
is the app blocked from sending notifications

**Comment by TeknikSpace** [comment]
I checked windows settings and it isn't blocked, but also not on the list (browser: chrome)

**Comment by TeknikSpace** [comment]
wait they were off oops

**Comment by TeknikSpace** [comment]
fixed, thanks!
