### ISSUE TITLE
option to run extension from link as unsandboxed

### ISSUE THREAD

**Issue by scoobydoofacethingdie** [TurboWarp/extensions#746]
i've made my own extension and put it on my website, but to use it as unsandboxed I would have to download it as a file and import it there, but takes too long. made a concept on what it would look like if the URL tab had a "run as unsandboxed" checkmark
![image](https://github.com/TurboWarp/extensions/assets/85052868/f6cc5e6f-7420-405c-a966-0ddbba8a3eb6)

**Comment by LilyMakesThings** [comment]
I think its pretty clear that if this was a safe option to add, it would e already been added by now.

**Comment by Flappy25** [comment]
Just input your extension as text

**Comment by scoobydoofacethingdie** [comment]
> Just input your extension as text
> but it takes too long
i would have to search for my file, open it in a text editor, copy it and the paste it in turbowarp

**Comment by DNin01** [comment]
What if the remotely hosted code changes to something with malicious intent?
