### ISSUE TITLE
the shovel utilits

### ISSUE THREAD

**Issue by glebik228** [TurboWarp/extensions#750]

**Comment by glebik228** [comment]
sorry

**Comment by glebik228** [comment]
sorry

**Comment by glebik228** [comment]
project block does not work

**Comment by Mickmick2012** [comment]
are you uploading a .sb3 in raw ? (ex : github.com/whatever/whatever should NOT be used, use raw option instead)

**Comment by TheShovel** [comment]
> project block does not work

It does. You are just not using it correctly. Send the link you are trying to fetch.

**Comment by glebik228** [comment]
> 

https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1DbZzNKpwb9hTCAx5Khp5dFVkGEU3T3my I've tried this

**Comment by Mickmick2012** [comment]
CORS is blocking the fetch : Access to fetch at '*URL*' from origin 'https://turbowarp.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by GarboMuffin** [comment]
It needs direct URLs that set "CORS" headers. Google Drive is not one of these. GitHub (specifically, the raw links at raw.githubusercontent.com) *are* one of these.
