### ISSUE TITLE
Cannot go to root of zip | Zip Extension

### ISSUE THREAD

**Issue by SurvExe1Pc** [TurboWarp/extensions#753]
Example of this issue:

https://github.com/TurboWarp/extensions/assets/135030944/7bf0fa35-e7b1-487c-83a7-925180bc61e9

**Comment by GarboMuffin** [comment]
@CST1229

**Comment by SurvExe1Pc** [comment]
^

**Comment by CST1229** [comment]
The PR hasn't been merged yet.
