### ISSUE TITLE
HUGE Problem With Camera Controls

### ISSUE THREAD

**Issue by TheGamingCow507** [TurboWarp/extensions#763]
I haven't read anything on here and I have almost no clue how to use GitHub, but I found a huge problem with the Camera Controls extension and just googled the problem and found this.  Don't know if it's already on here, but Camera Controls completely screws up the mouse pointer when it's loaded in a project.  I'm assuming the problem could be fixed semi-easily because I'm like 90% sure TurboWarp doesn't actually check if two things are touching, but checks if they're touching using math equations and numbers, meaning you could just add the camera x and camera y to the mouse x and mouse y.  I'm probably wrong tho, I don't know how the camera extension works and I don't know how TurboWarp or Scratch detects collisions, that's just a not so educated guess based on how the actual mouse location corresponds to the visible mouse position

**Comment by horizontal-shading** [comment]
This has been reported lots of times and will probably be fixed soon

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
