### ISSUE TITLE
Allow normal users to run workflows on their pulls

### ISSUE THREAD

**Issue by ClaytonTDM** [TurboWarp/extensions#765]
It'd make pull requests easier so that you don't have to wait for someone to approve running the linter, and you can find errors faster.

**Comment by GarboMuffin** [comment]
Just discovered GitHub lets me change that, so going forward it should lint automatically for most people

**Comment by LilyMakesThings** [comment]
I always thought that was in place as some weird safety thing but that's actually awesome

**Comment by ClaytonTDM** [comment]
:D
