### ISSUE TITLE
extensions not loading from backpack

### ISSUE THREAD

**Issue by scoobydoofacethingdie** [TurboWarp/extensions#767]
when you import a sprite or script from the backpack which contains blocks from extensions, nothing happens and the extensions wont load, but an error would appear in the console saying `Uncaught (in promise) Sprite Upload Error: Error: Unknown extension: EXTENSION-NAME` (EXTENSION-NAME is the name of the extension, for example `utilities` and `lmsLooksPlus`)

**Comment by NexusKitten** [comment]
This is intentional; just load in the extension before importing a sprite or script.

**Comment by GarboMuffin** [comment]
this is a bug, this is not intentional

**Comment by tigercoding56** [comment]
> This is intentional; just load in the extension before importing a sprite or script.

this is bad design, the user should be prompted to add the extension once they run the code

**Comment by LilyMakesThings** [comment]
> > This is intentional; just load in the extension before importing a sprite or script.
> 
> this is bad design, the user should be prompted to add the extension once they run the code, and maybe have a setting to just auto-import the extension

As pointed out by GarboMuffin, the maintainer of TW, this is considered a bug. It's not by design.

**Comment by NexusKitten** [comment]
> > This is intentional; just load in the extension before importing a sprite or script.
> 
> this is bad design, the user should be prompted to add the extension once they run the code, and maybe have a setting to just auto-import the extension

I aplogize, I figured it was a feature however as GarboMuffin said, it is in fact a bug and will hopefully be patched out in the near future.

**Comment by DNin01** [comment]
The same thing happens when uploading a sprite from local files.

**Comment by GarboMuffin** [comment]
This will be fixed in the next batch of updates for *newly exported sprites*

Unfortunately for sprites already exported or backpacked, the information needed to load the extensions just doesn't exist

**Comment by scoobydoofacethingdie** [comment]
> Unfortunately for sprites already exported or backpacked, the information needed to load the extensions just doesn't exist

can i just load extensions, import the sprite and then export it back into the backpack?
Is it also gonna work with extensions that are loaded via text or files?

**Comment by GarboMuffin** [comment]
Yes and yes
