### ISSUE TITLE
Problems with new extensions

### ISSUE THREAD

**Issue by samuellouf** [TurboWarp/extensions#769]
Hi everyone, I'm trying to make a fullscreen extension.
It works everywhere but on the TurboWarp Website and the Mac OS package.
I would appreciate it if somebody told me how to switch to fullscreen (at least for the TurboWarp Website).

**Comment by samuellouf** [comment]
I think it has something to do with the vm but I haven't found anything yet.

**Comment by CubesterYT** [comment]
@samuellouf No need to make a fullscreen extension. My upcoming window controls extension has a block for Fullscreen. #706

**Comment by GarboMuffin** [comment]
it sounds like you're writing an extension and want help. it would be a good idea to post the source code in such instances, otherwise there is nothing we can do to help you

**Comment by samuellouf** [comment]
> @samuellouf No need to make a fullscreen extension. My upcoming window controls extension has a block for Fullscreen. https://github.com/TurboWarp/extensions/pull/708

Ok, I'm closing the issue
