### ISSUE TITLE
"close window" block from Window Controls extension not working

### ISSUE THREAD

**Issue by samuellouf** [TurboWarp/extensions#773]
@CubesterYT, the block below this text doesn't work.
![Capture d’écran 2023-07-24 à 06 16 05](https://github.com/TurboWarp/extensions/assets/104774504/4187af50-bc21-441d-b028-489413ff3ddd)
It doesn't work because the browser doesn't allow a script to close a window.
![Capture d’écran 2023-07-24 à 06 18 20](https://github.com/TurboWarp/extensions/assets/104774504/f93c8a00-4e0a-4391-b2ec-e8ade3719693)
There isn't any script to close a window.
You can have a look at [this](https://stackoverflow.com/questions/19761241/window-close-and-self-close-do-not-close-the-window-in-chrome/19768082#19768082).

**Comment by CubesterYT** [comment]
You wouldn't be able to tell, but I specify in the documentation for Window Controls that "close window" only works in html and electron. And also most possibly web apps/popups. Basically it's specified as a block that doesn't work in browser tabs.

**Comment by NexusKitten** [comment]
In the future, please report issues from pull requests on the main pull request rather than the issues board

**Comment by idoinfactexist** [comment]
close window works on chrome, it just closes the tab

**Comment by GarboMuffin** [comment]
I'm closing this because the extension has not yet been merged

**Comment by idoinfactexist** [comment]
[close window test.txt](https://github.com/TurboWarp/extensions/files/12168344/close.window.test.txt)
download the file and then rename it as an html file, then open it in chrome and press any key
