### ISSUE TITLE
A better way to credit contributors to extensions in the gallery

### ISSUE THREAD

**Issue by DNin01** [TurboWarp/extensions#777]
Currently, the way we credit the creators of extensions is by adding a note to the description. But what if multiple people worked hard on the features? There's not enough room to go on forever with contributors and creators.

I'm imagining an information button to the top-right of each extension card. When clicking it, extra information about the extension would be displayed, such as its contributors and credits (and maybe even version number).

**Comment by DNin01** [comment]
That's a lucky issue number!

**Comment by LilyMakesThings** [comment]
We tend to work on extensions solo, collaborations are very very rare. I tend to just add a comment above the stuff I added to an extension.

Not many of us are actually that fussy about credit, some of us would just be happy our extensions got merged at all.

**Comment by GarboMuffin** [comment]
there is plenty of room to just list everyone :)
