### ISSUE TITLE
CORS blocking github

### ISSUE THREAD

**Issue by LIZARD-OFFICIAL** [TurboWarp/extensions#782]
CORS Blocks projects from accessing github

**Comment by LIZARD-OFFICIAL** [comment]
Almost any url that is not turbowarp.You can bypass with corsproxy.io

**Comment by NexusKitten** [comment]
Just use a CORS proxy to get around it, there's not much we can do other than that considering it's an issue on Github's side.

**Comment by LIZARD-OFFICIAL** [comment]
> Use GitHub Pages or the raw links at raw.githubusercontent.com, it'll work

thanks but there aint a problem anyways
