### ISSUE TITLE
How do you add a variable that can be accessed by the clones+ extention? 

### ISSUE THREAD

**Issue by aguyhello** [TurboWarp/extensions#784]
When I use a code block that uses a variable, such as "create clone with [] set to 1", it doesn't show any variables, how do I create one?

**Comment by CST1229** [comment]
...by creating a variable in the Variables category. (Clones+ uses normal Scratch variables.)

**Comment by aguyhello** [comment]
I have normal scratch variables though, but it doesn't show up.

**Comment by CST1229** [comment]
They show up for me (the variables have to be for this sprite only for them to show up).

**Comment by aguyhello** [comment]
Oh yeah that's why, all of mine are global, thanks!

**Comment by BlueDome77** [comment]
Please close the issue

**Comment by aguyhello** [comment]
Oh ok

**Comment by horizontal-shading** [comment]
The comments are live?!

**Comment by aguyhello** [comment]
How do you close it?

**Comment by aguyhello** [comment]
Oh I found out
