### ISSUE TITLE
Text Limit Fonts ;(

### ISSUE THREAD

**Issue by Azulcat** [TurboWarp/extensions#786]
How could I add fonts to TurboWarp? if it is not implemented then why not add it :D

**Comment by NexusKitten** [comment]
There's a folder in Scratch-GUI that contains all fonts added to Scratch. The current system makes it rather difficult to import fonts (the ways you may see it done in PenguinMod and other Scratch Mods aren't perfect by any means), and it would be quite a large undertaking to rework the system.
With that being said, Scratch Also has support for built-in web fonts, so you can technically use fonts such as Comic Sans MS, Impact, etc, however cannot import then through the font menu.

**Comment by BlueDome77** [comment]
https://meeeeeeeep1.github.io/haven.scratch-tools/customScratchFont/

**Comment by Azulcat** [comment]
can i add more to these? @BlueDome77

**Comment by BlueDome77** [comment]
> can i add more to these? @BlueDome77

You can type in the name of the font you want to add. (you have to have that font installed on your computer too I think)

**Comment by Azulcat** [comment]
COOL

**Comment by Azulcat** [comment]
Thank you!

**Comment by BlueDome77** [comment]
> Thank you!

np!

**Comment by Azulcat** [comment]
wait a secim using the font for the text extension will it work? (if you don't kno what it is check it out)

**Comment by BlueDome77** [comment]
> wait a sec
> using the font for the text extension will it work? (if you don't kno what it is check it out)

no

**Comment by Azulcat** [comment]
ah that is the problem

**Comment by Azulcat** [comment]
@NexusKitten the penguin mod i could give that a try can you explain how to do it plz

**Comment by BlueDome77** [comment]
> @NexusKitten the penguin mod i could give that a try can you explain how to do it plz

Penguin Mod changes the VM to accept fonts from files so that would not work in Turbowarp

**Comment by Azulcat** [comment]
Oh how can i install mods in it?

**Comment by BlueDome77** [comment]
> Oh how can i install mods in it?

you can't

**Comment by Azulcat** [comment]
i meant fonts (i hate my auto correct)

**Comment by BlueDome77** [comment]
> i meant fonts (i hate my auto correct)

Currently the only way is to use the website I gave you earlier but maybe you should create an issue in the SA repo about this

**Comment by Azulcat** [comment]
Oh but it did not show me my system fonts

**Comment by Azulcat** [comment]
should i restart my computer?

**Comment by BlueDome77** [comment]
> should i restart my computer?

Mac or PC?

**Comment by Azulcat** [comment]
pc

**Comment by BlueDome77** [comment]
> pc

Sorry but i'm a Mac user so I don't now much about PC

**Comment by BlueDome77** [comment]
maybe try a different browser?

**Comment by Azulcat** [comment]
sure

**Comment by Azulcat** [comment]
it did work (a font glitch fixed) but not all of my fonts are apearing i'll try to restart

**Comment by Azulcat** [comment]
Nor work

**Comment by BlueDome77** [comment]
> No work

idk what else

**Comment by GarboMuffin** [comment]
Custom fonts are a thing now
