### ISSUE TITLE
(files extension) Cant download stuff correctly.

### ISSUE THREAD

**Issue by Martinelplayz** [TurboWarp/extensions#789]
honestly i think this probably has something to do with the way i'm trying to do it, but i tried to use looks+ and the zip extension to download zips and images. the result? an unopenable zip, and unviewable png files. is there any way around this?

**Comment by LilyMakesThings** [comment]
Cna you please send a picture of the code?

**Comment by GarboMuffin** [comment]
If this still happens, please provide more details
