### ISSUE TITLE
save & open file extension

### ISSUE THREAD

**Issue by piw-piw** [TurboWarp/extensions#8]
4 blocks:
Save file with name and data, save automatic in project folder
![scratchblocks (7)](https://user-images.githubusercontent.com/76477070/137000034-e4aec97e-26ef-4a9e-a7b8-3539a1b1b2e5.png)
Save file with name and data, save in selected by user folder
![scratchblocks (8)](https://user-images.githubusercontent.com/76477070/137000082-4ff90ca0-14ae-48c1-ba53-c55325389a5b.png)
Open file with name, open automatic from project folder
![scratchblocks (9)](https://user-images.githubusercontent.com/76477070/137000088-0c85077a-2d39-473c-94e9-28d5f2272979.png)
Open file with name, open from selected by user folder
![scratchblocks (10)](https://user-images.githubusercontent.com/76477070/137000092-f8be529b-1eb0-47f0-906d-d6448bf5c0b6.png)

**Comment by mollthecoder** [comment]
> I want include this to packager.

I'm sorry but it's just not possible. I request that you close this issue, please.

**Comment by piw-piw** [comment]
> > Chcę to dołączyć do pakującego.
> 
> Przepraszam, ale to po prostu niemożliwe. Proszę o zamknięcie tego problemu.

Why?

**Comment by mollthecoder** [comment]
> > > I want include this to packager.
> > 
> > 
> > I'm sorry but it's just not possible. I request that you close this issue, please.
> 
> Why?

Because this will not happen.

**Comment by GarboMuffin** [comment]
Opening and writing to specific files is probably not viable but opening file pickers and downloading files is perfectly viable from a website.

As I've said in other places, custom extensions just aren't very good. Perhaps some more things can be added to the packager.

**Comment by piw-piw** [comment]
> Opening and writing to specific files is probably not viable but opening file pickers and downloading files is perfectly viable from a website.
> 
> As I've said in other places, custom extensions just aren't very good. Perhaps some more things can be added to the packager.

> I want include this to packager.

**Comment by GarboMuffin** [comment]
Follow https://github.com/TurboWarp/scratch-gui/issues/633
