### ISSUE TITLE
camera extension mouse translation

### ISSUE THREAD

**Issue by RedMan13** [TurboWarp/extensions#828]
when using the camera extension zooming out breaks the mouse position, but only if the camera is moved away from 0,0
when its at 0,0 there is no error in the reported possition, but when the camera isnt at 0,0 it all breaks down and the mouse position starts reporting wrong values by significant bit

**Comment by RedMan13** [comment]
[Screen recording 2023-08-02 4.20.17 AM.webm](https://github.com/TurboWarp/extensions/assets/74981904/2d28d507-5788-46da-9bd9-e88a773fc9ba)
here is an example video of the bug

**Comment by Flappy25** [comment]
> [Screen recording 2023-08-02 4.20.17 AM.webm](https://github.com/TurboWarp/extensions/assets/74981904/2d28d507-5788-46da-9bd9-e88a773fc9ba)
> here is an example video of the bug

The camera is only showing the costume, not the actual position

**Comment by RedMan13** [comment]
> > [Screen recording 2023-08-02 4.20.17 AM.webm](https://github.com/TurboWarp/extensions/assets/74981904/2d28d507-5788-46da-9bd9-e88a773fc9ba)
> > here is an example video of the bug
> 
> The camera is only showing the costume, not the actual position

i feel like you have missed the entire point of the video

**Comment by NotEmbin** [comment]
> [Screen recording 2023-08-02 4.20.17 AM.webm](https://github.com/TurboWarp/extensions/assets/74981904/2d28d507-5788-46da-9bd9-e88a773fc9ba) here is an example video of the bug


https://github.com/TurboWarp/extensions/assets/113154360/a61db7d2-a501-449d-8221-b6c6fb7ccb4d

here is another example

**Comment by GarboMuffin** [comment]
Merging into #930
