### ISSUE TITLE
LZ Compress Doesn't Actually Compress

### ISSUE THREAD

**Issue by TeknikSpace** [TurboWarp/extensions#829]
I have a save system, and am improving it to make it better compressed with the new Zip extension

Old Save Size: ~9 Megabytes
New Save Size: ~4.77 Megabytes
New (LZ Compress Raw): 5.63 Megabytes
New (LZ Compress Base64): 7.72 Megabytes
New (LZ Compress EncodedURLComponent): 7.72 Megabytes
and some are up to 17 Megabytes

my point is, this is actually Largening the size than compressing it like it should.

please fix this!

**Comment by CST1229** [comment]
Usually, compressing compressed data (since zips are also compressed) doesn't yield much better results, or may increase the size of the data.

**Comment by TeknikSpace** [comment]
Okay, so it's basically intended behaviour?

**Comment by GarboMuffin** [comment]
Yeah. Sb3 files are already compressed and compressing compressed data doesn't really help.

The extension might be useful to combine with eg. Local storage or other places that aren't compressed
