### ISSUE TITLE
How do i play sound from folders?

### ISSUE THREAD

**Issue by Gaypatapon** [TurboWarp/extensions#835]
I tried to use the sound extension to play audio files from a folder but it doesnt work, idk if i did something wrong or not. btw im making a patapon fangame

**Comment by SurvExe1Pc** [comment]
are you using this extension:
![image](https://github.com/TurboWarp/extensions/assets/135030944/93dd1b4f-0cc9-4d60-a5c6-8ff644efef85)
if so no you have to play sounds from urls and not sounds in the sprite, if its sound expanded 
![image](https://github.com/TurboWarp/extensions/assets/135030944/6fc20a3e-3601-4170-afa7-f0cd3b8d29fd)
it seems to work, otherwise send what your using, and maybe check your audio file.

**Comment by Gaypatapon** [comment]
> are you using this extension: ![image](https://user-images.githubusercontent.com/135030944/258500953-93dd1b4f-0cc9-4d60-a5c6-8ff644efef85.png) if so no you have to play sounds from urls and not sounds in the sprite, if its sound expanded ![image](https://user-images.githubusercontent.com/135030944/258501461-6fc20a3e-3601-4170-afa7-f0cd3b8d29fd.png) it seems to work, otherwise send what your using, and maybe check your audio file.

the audio file is mp3, and also the folder name is bgm, i tried putting in the folder url but it doesnt work

**Comment by Gaypatapon** [comment]
and also im trying to play the sound from the folder, not from sprites

**Comment by Gaypatapon** [comment]
> are you using this extension: ![image](https://user-images.githubusercontent.com/135030944/258500953-93dd1b4f-0cc9-4d60-a5c6-8ff644efef85.png) if so no you have to play sounds from urls and not sounds in the sprite. ![image](https://user-images.githubusercontent.com/135030944/258501807-5ac976e8-6903-4c6f-b225-6ec4eed257fb.png) if its sound expanded ![image](https://user-images.githubusercontent.com/135030944/258501461-6fc20a3e-3601-4170-afa7-f0cd3b8d29fd.png) it seems to work, otherwise send what your using, and maybe check your audio file.

im trying to load audio files from the dir

**Comment by SurvExe1Pc** [comment]
> > are you using this extension: ![image](https://user-images.githubusercontent.com/135030944/258500953-93dd1b4f-0cc9-4d60-a5c6-8ff644efef85.png) if so no you have to play sounds from urls and not sounds in the sprite, if its sound expanded ![image](https://user-images.githubusercontent.com/135030944/258501461-6fc20a3e-3601-4170-afa7-f0cd3b8d29fd.png) it seems to work, otherwise send what your using, and maybe check your audio file.
> 
> the audio file is mp3, and also the folder name is bgm, i tried putting in the folder url but it doesnt work

if its a datauri or file url and your using the "sound" extension its not going to work, and if the file is on an external server, try putting it through a proxy, like corsproxy.io

**Comment by Gaypatapon** [comment]
> > > are you using this extension: ![image](https://user-images.githubusercontent.com/135030944/258500953-93dd1b4f-0cc9-4d60-a5c6-8ff644efef85.png) if so no you have to play sounds from urls and not sounds in the sprite, if its sound expanded ![image](https://user-images.githubusercontent.com/135030944/258501461-6fc20a3e-3601-4170-afa7-f0cd3b8d29fd.png) it seems to work, otherwise send what your using, and maybe check your audio file.
> > 
> > 
> > the audio file is mp3, and also the folder name is bgm, i tried putting in the folder url but it doesnt work
> 
> if its a datauri or file url and your using the "sound" extension its not going to work, and if the file is on an external server, try putting it through a proxy, like corsproxy.io

its just that i wanted it to be offline like i wanted to play the sound from a folder dir, is there a way around it like using fetch or other extensions?

**Comment by SurvExe1Pc** [comment]
> > > > are you using this extension: ![image](https://user-images.githubusercontent.com/135030944/258500953-93dd1b4f-0cc9-4d60-a5c6-8ff644efef85.png) if so no you have to play sounds from urls and not sounds in the sprite, if its sound expanded ![image](https://user-images.githubusercontent.com/135030944/258501461-6fc20a3e-3601-4170-afa7-f0cd3b8d29fd.png) it seems to work, otherwise send what your using, and maybe check your audio file.
> > > 
> > > 
> > > the audio file is mp3, and also the folder name is bgm, i tried putting in the folder url but it doesnt work
> > 
> > 
> > if its a datauri or file url and your using the "sound" extension its not going to work, and if the file is on an external server, try putting it through a proxy, like corsproxy.io
> 
> its just that i wanted it to be offline like i wanted to play the sound from a folder dir, is there a way around it like using fetch or other extensions?

if your trying to play a file that is stored on your computer and attempting to access it you cannot do that.

**Comment by Gaypatapon** [comment]
> > > > > are you using this extension: ![image](https://user-images.githubusercontent.com/135030944/258500953-93dd1b4f-0cc9-4d60-a5c6-8ff644efef85.png) if so no you have to play sounds from urls and not sounds in the sprite, if its sound expanded ![image](https://user-images.githubusercontent.com/135030944/258501461-6fc20a3e-3601-4170-afa7-f0cd3b8d29fd.png) it seems to work, otherwise send what your using, and maybe check your audio file.
> > > > 
> > > > 
> > > > the audio file is mp3, and also the folder name is bgm, i tried putting in the folder url but it doesnt work
> > > 
> > > 
> > > if its a datauri or file url and your using the "sound" extension its not going to work, and if the file is on an external server, try putting it through a proxy, like corsproxy.io
> > 
> > 
> > its just that i wanted it to be offline like i wanted to play the sound from a folder dir, is there a way around it like using fetch or other extensions?
> 
> if your trying to play a file that is stored on your computer and attempting to access it you cannot do that.

Thats ashame, maybe i should do a suggestion

**Comment by SurvExe1Pc** [comment]
it might be possible if the extension asks for access to a specific folder but i have no idea how that would work

**Comment by SurvExe1Pc** [comment]
anyways i think you can close the issue.

**Comment by Gaypatapon** [comment]
> anyways i think you can close the issue.

I closed the issue and i also made a suggestion
