### ISSUE TITLE
FPS Extension

### ISSUE THREAD

**Issue by lolpng944** [TurboWarp/extensions#848]
I dont mean like a normal fps extension. i mean a extension that fix the bug: when the fps is lower the game is also slower so a character for example runs 40 steps but if i have just the half of fps it will only walk 20 steps

i need a fix for that

**Comment by LilyMakesThings** [comment]
Interpolation is your only option, this is the price to pay for a faster FPS.

**Comment by CST1229** [comment]
> Interpolation is your only option, this is the price to pay for a faster FPS.

I think they're talking about *slower* FPS. In this case, the only option is to implement [delta time](https://scratch.mit.edu/projects/487694716/) into your project.

**Comment by DNin01** [comment]
Another workaround is "get framerate limit" in [Runtime Options](https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/runtime-options.js).
