### ISSUE TITLE
Camera <-> Pen Incompatability

### ISSUE THREAD

**Issue by Martinelplayz** [TurboWarp/extensions#849]
The pen apparently can't draw outside of the stage. i mean, why would it need to right? but the problem begins to become apparent when you are using the camera as . . . well, an actual camera because when you move the camera off of (0, 0), the pen can't draw outside of the original stage location. meaning if you moved the camera to (10000, 10000) the pen wouldn't be able to draw AT ALL.

when i say draw i also mean stamping.

**Comment by GarboMuffin** [comment]
Merging into #930
