### ISSUE TITLE
Please upvote 👍 the extensions and issues you care about

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/extensions#855]
If there's an issue or pull request you want to see, please click on it, the press the emoji icon at the end of the description, then add a :+1:

I am using this list as one factor while whittling away at the review queue:

 - https://github.com/TurboWarp/extensions/pulls?q=is%3Apr+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by NexusKitten** [comment]
o̶r̶ m̶a̶k̶e̶ a̶n̶ a̶l̶t̶e̶r̶n̶a̶t̶i̶v̶e̶ a̶c̶c̶o̶u̶n̶t̶ t̶o̶ b̶o̶o̶s̶t̶ y̶o̶u̶r̶ o̶w̶n̶ e̶x̶t̶e̶n̶s̶i̶o̶n̶s̶
