### ISSUE TITLE
I can't fetch files from my directory folder

### ISSUE THREAD

**Issue by Gaypatapon** [TurboWarp/extensions#866]
I tried to do what @TheShovel said but it doesn't work. here's the comment:  You can just use the fetch extension. If you want a file directly from the same directory, just put the file name + extension (level.json for example) in the fetch extension block. Same with folders. Just do `foldername/level.json` .

_Originally posted by @TheShovel in https://github.com/TurboWarp/extensions/issues/444#issuecomment-1556033026_

**Comment by NexusKitten** [comment]
Can you send a picture of your console logs? If the fetch request is failing, you probably have an error.

**Comment by Gaypatapon** [comment]
> Can you send a picture of your console logs? If the fetch request is failing, you probably have an error.

The console log is blank

**Comment by NexusKitten** [comment]
Are you sure the console log (press Ctrl + Shift + i and go to the "console" tab) is empty? I have a feeling I know what your issue is but I'd like to see what errors you get to make sure we're on the same page.

**Comment by TheShovel** [comment]
> I tried to do what @TheShovel said but it doesn't work. here's the comment: You can just use the fetch extension. If you want a file directly from the same directory, just put the file name + extension (level.json for example) in the fetch extension block. Same with folders. Just do `foldername/level.json` .
> 
> _Originally posted by @TheShovel in [#444 (comment)](https://github.com/TurboWarp/extensions/issues/444#issuecomment-1556033026)_

Doing `foldername/level.json` won't work if you are in the editor, since the editor is not running in the root directory of the project file. I assume that you didn't know about this.

**Comment by Gaypatapon** [comment]
> > I tried to do what @TheShovel said but it doesn't work. here's the comment: You can just use the fetch extension. If you want a file directly from the same directory, just put the file name + extension (level.json for example) in the fetch extension block. Same with folders. Just do `foldername/level.json` .
> > _Originally posted by @TheShovel in [#444 (comment)](https://github.com/TurboWarp/extensions/issues/444#issuecomment-1556033026)_
> 
> Doing `foldername/level.json` won't work if you are in the editor, since the editor is not running in the root directory of the project file. I assume that you didn't know about this.

Oh, well thanks for answering my question, though i wish it worked in the editor
