### ISSUE TITLE
Add other keys

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/extensions#869]
![image](https://github.com/TurboWarp/extensions/assets/131917462/c15965a2-7046-4345-80f4-2f6c7384db17)
(I mean like this block)
Add all the function keys (f1, f2, f3, f4, etc)
Add Alt key
Add Tab key

**Comment by SurvExe1Pc** [comment]
you could also add it to the vm right?

**Comment by NexusKitten** [comment]
> you could also add it to the vm right?

Yeah, Garbo could add it to ioDevices. I think some of the keys may be specific enough not to need it though (just using events)

**Comment by SurvExe1Pc** [comment]
i mean having the alt key would be nice 🫠

**Comment by snowboyz0825** [comment]
> ![image](https://user-images.githubusercontent.com/131917462/259600988-c15965a2-7046-4345-80f4-2f6c7384db17.png) (I mean like this block) Add all the function keys (f1, f2, f3, f4, etc) Add Alt key Add Tab key

I don't entirely know if this is allowed, but there's this rejected extension that will report any key
`// Name: Key Press Extension
// ID: keypressed
// Description: It has a reporter block reporting what key has been pressed, allowing for more supported keys and easier detection
// By: snowboyz0825 <https://scratch.mit.edu/users/Dat_Snow_Kid/>
// Mostly by chatGPT, I just added a few edits after training the chatbot to code extensions. I take no creative credit. 
class KeyPressExtension {
  constructor(runtime) {
    this.runtime = runtime;
    this.currentKey = null;
    // Attach event listener for keydown and keyup events
    document.addEventListener('keydown', this.handleKeyDown.bind(this));
    document.addEventListener('keyup', this.handleKeyUp.bind(this));
  }

  getInfo() {
    return {
      id: 'keyPress',
      name: 'Key Press Extension',
      blocks: [
        {
          opcode: 'getCurrentKey',
          blockType: Scratch.BlockType.REPORTER,
          text: 'current key',
          arguments: {},
        },
      ],
    };
  }

  getCurrentKey() {
    return this.currentKey || 'No key pressed';
  }

  handleKeyDown(event) {
    // Get the name of the pressed key
    this.currentKey = event.key;
    this.runtime.requestRedraw(); // Notify Scratch to update the block value
  }

  handleKeyUp() {
    // Reset the currentKey when the key is released
    this.currentKey = null;
    this.runtime.requestRedraw(); // Notify Scratch to update the block value
  }
}

Scratch.extensions.register(new KeyPressExtension());
`

**Comment by snowboyz0825** [comment]
> ![image](https://user-images.githubusercontent.com/131917462/259600988-c15965a2-7046-4345-80f4-2f6c7384db17.png) (I mean like this block) Add all the function keys (f1, f2, f3, f4, etc) Add Alt key Add Tab key

https://github.com/snowboyz0825/snowscodestuff/blob/main/keypressed.js
This extension should work on virtually any key
