### ISSUE TITLE
Box2D extension incompatibility between original and TurboWarp version

### ISSUE THREAD

**Issue by Xeltalliv** [TurboWarp/extensions#87]
In original extension all block dropdowns are round inputs, in TurboWarp version they are square inputs.

Because of this mismatch, when trying to open projects that were made in original, in TurboWarp, all dropdowns reset to the first option from the list. When trying to open projects that were made in TurboWarp, in original, all dropdowns become empty round inputs.

**Comment by GarboMuffin** [comment]
this is rather unfortunate and probably unfixable at this point

**Comment by showierdata9978** [comment]
Load box2D from original url (;

**Comment by CST1229** [comment]
> this is rather unfortunate and probably unfixable at this point

I think the only way is to add migration logic in scratch-vm to convert between droppable and non-droppable dropdowns.



> Load box2D from original url (;

There is *no* original URL, because it was a built-in extension in griffpatch's fork.
