### ISSUE TITLE
I used the looks+ to change my clone's color but everytime i change it to many diffrent colors it colors all of my clones to the same colors

### ISSUE THREAD

**Issue by Gaypatapon** [TurboWarp/extensions#882]
I'm making a patapon fangame and i wanted to add rarepons but the problem is that i wanted the patapons to have a diffrent colors the (insert) color) to (insert color) block from looks+ always colors all the patapons the same color, this is a huge problem since i wanted the patapons to have diffrent colors and not the same colors.

**Comment by SurvExe1Pc** [comment]
shovel said looks+ does not work on clones.

**Comment by Gaypatapon** [comment]
> shovel said looks+ does not work on clones.

Oh well is there gonna be support for clones?

**Comment by LilyMakesThings** [comment]
> > shovel said looks+ does not work on clones.
> 
> Oh well is there gonna be support for clones?

There is a Skins extension

**Comment by Gaypatapon** [comment]
> > > shovel said looks+ does not work on clones.
> > 
> > 
> > Oh well is there gonna be support for clones?
> 
> There is a Skins extension

Ok but how do i change color for all of my costumes with skins?

**Comment by GarboMuffin** [comment]
So Looks+ can only apply effects to the *original* sprite, not clones. If you want to change the color of the clones, it's probably easiest to use the normal set color effect inside of the clone you want to color. You could make a broadcast called like "randomize colors" and each clone will receive that and update their color accordingly

**Comment by Gaypatapon** [comment]
> So Looks+ can only apply effects to the _original_ sprite, not clones. If you want to change the color of the clones, it's probably easiest to use the normal set color effect inside of the clone you want to color. You could make a broadcast called like "randomize colors" and each clone will receive that and update their color accordingly

I know but the problem is that the costume is white and black and i wanted to find a easier way to color them without having to make more costumes for diffrent colors, i could use the skins extention but i don't know how

**Comment by Gaypatapon** [comment]
> > > shovel said looks+ does not work on clones.
> > 
> > 
> > Oh well is there gonna be support for clones?
> 
> There is a Skins extension

I used the skin extention to make rarepons and it worked very great, i think i can close this now
