### ISSUE TITLE
about return

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/extensions#890]
![image](https://github.com/TurboWarp/extensions/assets/118588391/aef0ea35-5799-4214-9720-2249c7a2ccaf)
How to handle multiple types of return?

**Comment by CST1229** [comment]
I think custom reporters can always be placed in both boolean and string/number inputs, regardless of shape

**Comment by qxsck** [comment]
> 我认为自定义报告器始终可以放置在布尔值和字符串/数字输入中，无论形状如何。

Allowing three forms to switch is better.

**Comment by LilyMakesThings** [comment]
> > 我认为自定义报告器始终可以放置在布尔值和字符串/数字输入中，无论形状如何。
> 
> Allowing three forms to switch is better.

It's completely unnecessary when it has output: null

**Comment by DNin01** [comment]
I mean, you could right-click and switch between different reporter shapes, but in general, we don't usually write functions that could return multiple different types of data.

**Comment by GarboMuffin** [comment]
For the given script, a boolean shape for the reporter would just be wrong anyways. It'll always let you drop the block anywhere you want.
