### ISSUE TITLE
bug with argument system when creating extension

### ISSUE THREAD

**Issue by n-d-v** [TurboWarp/extensions#902]
this code 
![image](https://github.com/TurboWarp/extensions/assets/139984277/ab31c8d4-576b-4e56-9510-f0d2e29e0f74)
lead to this block
![image](https://github.com/TurboWarp/extensions/assets/139984277/af6f8317-19c2-4e6f-a1aa-1969554ec894)
when it should have looked somewhat like
Is () a (boolean v)

**Comment by CST1229** [comment]
You're specifying USERINPUT twice:
![image](https://github.com/TurboWarp/extensions/assets/68464103/cb5e4fac-6c23-446b-b297-01dbd885e40f)

**Comment by GarboMuffin** [comment]
see above

**Comment by n-d-v** [comment]
> You're specifying USERINPUT twice: ![image](https://user-images.githubusercontent.com/68464103/261793417-cb5e4fac-6c23-446b-b297-01dbd885e40f.png)

oh sorry, I didn't notice it

**Comment by n-d-v** [comment]
i fixed it now
