### ISSUE TITLE
MP3 player extension

### ISSUE THREAD

**Issue by Mickmick2012** [TurboWarp/extensions#92]
An extension that can can play mp3s via url and hard drive
i know that there is a Spotify extension from Scratch X
Example block:
![g891](https://user-images.githubusercontent.com/110345721/209468338-26598c2b-3578-49fb-96c7-1c1e0b203e6a.svg)

menu selection:
From URL
From File

**Comment by SIPC** [comment]
wow

**Comment by Mickmick2012** [comment]
i tried to do a prototype (with ABSOLUTELY NO KNOWLEDGE of java) with the spotify extension

**Comment by SIPC** [comment]
Lazy loading?

**Comment by softedco** [comment]
> Lazy loading?

I think it's just a suggestion

**Comment by Mickmick2012** [comment]
Closing this as the extension is added
