### ISSUE TITLE
 I need extension in-app shopping

### ISSUE THREAD

**Issue by Yoyoreg** [TurboWarp/extensions#933]
It prepares the purchase on play store and creates a variable in which it records if the purchase was made or an error occurred

**Comment by DNin01** [comment]
I don't really see the use for this on the TurboWarp website because all projects are open-source. The only way this could work is if it was only usable in the packager.

**Comment by LIZARD-OFFICIAL** [comment]
Its impossible.Unless you have an old phone/rassberry pi 4 lying around which you can host a server to handle purchases

**Comment by Yoyoreg** [comment]
This can be done by contacting Google Play

**Comment by softedco** [comment]
Turbowarp currently can't package projects into applications for mobile devices so this isn't really possible. There is an alternative though, itch.io has an API that allows for purchasing sub products for your game aka microtransactions and I might just be able to figure out how it works.

**Comment by GarboMuffin** [comment]
I am conflicted as to whether we allow in-app-purchase extensions into the official gallery

**Comment by LIZARD-OFFICIAL** [comment]
> softedco:Turbowarp currently can't package projects into applications for mobile devices so this isn't really possible. There is an alternative though, itch.io has an API that allows for purchasing sub products for your game aka microtransactions and I might just be able to figure out how it works.

There is a way.Just package to html, then convert that into apk using some software

**Comment by Yoyoreg** [comment]
How do I add the shopping extension to my programs?

**Comment by bubzilla** [comment]
it doesn't exist

**Comment by Yoyoreg** [comment]
[This can help](https://developer.android.com/google/play/billing?hl=fr)

**Comment by GarboMuffin** [comment]
You're going to be on your own here. I am unable to accept a payment processing in this repository because:

 - It is unlikely whatever payment library you use will be GPL-compatible
 - It goes against the spirit of a free open-source project
 - I (a volunteer) don't want to be getting support requests from people relying on it to make money when it inevitably breaks (as payment APIs frequently do)

I remind you that you can write your own extensions without submitting them here or find extensions written by others that are not uploaded here.

**Comment by GarboMuffin** [comment]
If you are serious about making money from something, you ought to be ready to pay for it in the first place.

I am easy to contact (contact@turbowarp.org), but really you could hire anyone you want, I know nothing about how Play Store payments work

**Comment by LIZARD-OFFICIAL** [comment]
> Turbowarp currently can't package projects into applications for mobile devices so this isn't really possible. There is an alternative though, itch.io has an API that allows for purchasing sub products for your game aka microtransactions and I might just be able to figure out how it works.

You could just turn the html format to apk though

**Comment by softedco** [comment]
> > Turbowarp currently can't package projects into applications for mobile devices so this isn't really possible. There is an alternative though, itch.io has an API that allows for purchasing sub products for your game aka microtransactions and I might just be able to figure out how it works.
> 
> You could just turn the html format to apk though

how

**Comment by LIZARD-OFFICIAL** [comment]
with a program for windows you can search html to apk on google
