### ISSUE TITLE
Window Controls creator miscredit

### ISSUE THREAD

**Issue by LilyMakesThings** [TurboWarp/extensions#966]
If you kept up with the Window Controls PR, you'll know that BlueDome was actually the original creator.

BlueDome created the PR for "Window Utils" first, after which Cubester left this comment:
![image](https://github.com/TurboWarp/extensions/assets/127533508/108ff8a6-4088-4fc6-ab8c-2bcbfdb2e560)

Then the PR for "Window Controls" was created and it was clear that the code for Window Utils served as the main basis for the extension.

![image](https://github.com/TurboWarp/extensions/assets/127533508/b7d1cc11-f3ad-478f-9b29-46e4f66e4ac3)

There's currently no "Updated by" like there was for Bitwise, perhaps consider adding that.

**Comment by CubesterYT** [comment]
I've already discussed with BlueDome through emails during the entire process of Window Controls. Window Controls was in development prior to the addition of the Window Utils PR. Window Controls already had the same code but more than what Window Utils had, after everything was done planned, we decided that it would be my code all the way, his thumbnail and color scheme and some suggestions. And a bunch more we would like to keep private. We've been in contact and had mutual understandings about everything.

**Comment by CubesterYT** [comment]
So indeed, Window Controls is made by me only.

**Comment by LilyMakesThings** [comment]
![image](https://github.com/TurboWarp/extensions/assets/127533508/dd9b60ee-67e1-4c1d-bf5c-6fc5c37c51e7)
![image](https://github.com/TurboWarp/extensions/assets/127533508/cf268c31-7fb9-456d-8f64-da786d623648)

**Comment by LilyMakesThings** [comment]
I don't think it's particularly fair for someone to have submitted a perfectly serviceable extension in a pull request, only to have it closed to be converted into a "collaboration" that ended with you taking full credit anyway.

**Comment by CubesterYT** [comment]
*sigh* I can't talk about everything that has happened in between, the comments you show here are from when I first gobin contact with BlueDome with no groundwork yet. Like I said, after everything thing was planned, we decided it be my extension since I had a very well developed one prior to his, and BlueDome would contribute suggestions and asthetics.

**Comment by GarboMuffin** [comment]
I see absolutely no reason not to put `// Original: BlueDome77`

I will note that there are a lot of unique code style and block name choices from Window Utils that made it in very late or merged versions of Window Controls which indicate to me some amount of copy+paste

**Comment by CubesterYT** [comment]
> I see absolutely no reason not to put `// Original: BlueDome77`
> 
> I will note that there are a lot of unique code style and block name choices from Window Utils that made it in very late or merged versions of Window Controls which indicate to me some amount of copy+paste
> 

I would like to say one last thing, is that there was no copy paste, it's just that we had the same ideas, we even laugh about it on how we had some similar types.

**Comment by LilyMakesThings** [comment]
Just from what's returned in getInfo() it's really clear there's a least some copy/paste. Maybe some reformatting for the block arguments but some blocks are genuinely identical.
