### ISSUE TITLE
JSON can't get nested keys

### ISSUE THREAD

**Issue by gomiigg** [TurboWarp/extensions#967]
I don't know the proper term for this, but look at the screenshots below. The JSON extension cannot return the value, but CloudLink can. The problem is, I don't want to add the whole CL extension just to use a better parser. Shouldn't this already be a feature in the JSON extension or am I doing something wrong?

![image](https://github.com/TurboWarp/extensions/assets/91437192/5f11217b-4dcb-43d9-91f0-1785972b17c6)
![image](https://github.com/TurboWarp/extensions/assets/91437192/72d23cb4-a578-42d5-aa7f-1b8465889e95)

**Comment by qxsck** [comment]
> 

![image](https://github.com/TurboWarp/extensions/assets/118588391/23e9f5fb-e570-46e4-84c6-112339e17daf)
It seems like can only do this, but will be even more cumbersome.

**Comment by LilyMakesThings** [comment]
the block is also in utilities, if you don't want to add CloudLink

**Comment by Skyhigh173** [comment]
tbh i can add this

**Comment by Skyhigh173** [comment]
I have added it in v2.6.
Will merge later
