### ISSUE TITLE
New block for Canvas Effects

### ISSUE THREAD

**Issue by horizontal-shading** [TurboWarp/extensions#996]
A new block for canvas effects.

Change canvas effect by N,

rather than having to use,

Set canvas effect to "get canvas effect + N"

**Comment by horizontal-shading** [comment]
Almost to 1000!

**Comment by NexusKitten** [comment]
This has been considered before, but likely isn't a good idea as it'd encourage using Canvas Effects in a loop (forever loop, repeat until, etc.). Canvas Effects can have massive performance issues when used like this, so it's best just to avoid it.

**Comment by horizontal-shading** [comment]
> This has been considered before, but likely isn't a good idea as it'd encourage using Canvas Effects in a loop (forever loop, repeat until, etc.). Canvas Effects can have massive performance issues when used like this, so it's best just to avoid it.

I didn't knew that

**Comment by BlueDome77** [comment]
> This has been considered before, but likely isn't a good idea as it'd encourage using Canvas Effects in a loop (forever loop, repeat until, etc.). Canvas Effects can have massive performance issues when used like this, so it's best just to avoid it.

What would be a better solution for "change x effect by number" ?
